- web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaXmlGenerator.java
checking in fix code for this reported bug
I'm removing the white spaces for item labels and values
> OC-6201 PForm: Data not saved correctly if Single-select Pull Down item with long string and/or contains comma 

- web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
revert the NoSuchRequestMethodHandlingException throwing when study is null from OpenRosaServices.getParentStudy()
> remove null-study check from OpenRosaServices.java

- web/src/main/java/org/akaza/openclinica/web/filter/OpenClinicaSecurityContextLogoutHandler.java
- web/src/main/java/org/akaza/openclinica/web/filter/OpenClinicaSessionRegistryImpl.java
- web/src/main/resources/org/akaza/openclinica/applicationContext-security.xml
The CRFLocker was not cleared when a session-time out occurs. Tested this fix by changing the session-time in the datainfo.properties to 20 seconds and waiting until the auditLogout method of the OpenClinicaSessionRegistryImpl was triggered. 
* this change was not included in the OpenClinica-ws source because I noticed that the OpenClinicaUsernamePasswordAuthenticationFilter class in the WS-war does not use the CRFLocker.
* the OpenClinicaSessionRegistryImpl in the WS does not retrieve the user information from LDAP, the Web however it does use LDAP.
> Fix for OC-6061 CRF locked error message

- core/src/main/resources/migration/3.9/2015-12-07-OC-6483.xml
- core/src/main/resources/migration/3.9/release.xml
Notification Rule with more than 255 characters in <Message> and
<Subject> elements generate Oops Error
> OC-6483 Notification Rule with more than 255 characters in <Message> and <Subject> elements generate Oops Error

- core/src/main/java/org/akaza/openclinica/domain/rule/action/RuleActionBean.java
- core/src/main/java/org/akaza/openclinica/service/rule/RulesPostImportContainerService.java
- core/src/main/java/org/akaza/openclinica/service/rule/expression/ExpressionService.java
- core/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
- web/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
Rules not working when absolute paths (versus relative paths) are used in the expression or action
> Oc 2047 Rules not working when absolute paths (versus relative paths) are used in the expression or action

- web/src/main/webapp/WEB-INF/jsp/admin/viewFullStudy.jsp
Participate Study Configuration Should not Appear on the View Study Page
if Participant Portal is not Enabled
> OC-6649 Participate Study Configuration Should not Appear on the View Study Page if Participant Portal is not Enabled 

- core/src/main/java/org/akaza/openclinica/service/rule/RulesPostImportContainerService.java
- core/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
- web/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
Notification Rule with more than 255 characters in <Message> and
<Subject> elements generate Oops Error
> OC-6483 Added validation to avoid oops page on upload for characters/ bytes over specified #

- web/src/main/java/org/akaza/openclinica/controller/StudyModuleController.java
Issue description:
> Disabling Participate under Build Study page by clicking [X] does change the
> status to Disabled while it does not change the actual status in OCUI, and
> the status is back into Enabled when user log back in.
> OC-6900 Bugfix, disable Participate in Build Study

- core/src/main/java/org/akaza/openclinica/logic/expressionTree/OpenClinicaExpressionParser.java
- core/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
- web/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
Extend rule_expression.value data type beyond 1025 characters
> OC-1176 Validating rule_expression_value length at rule upload to OC

- core/src/main/java/org/akaza/openclinica/service/rule/expression/ExpressionService.java
Rules not working when absolute paths (versus relative paths) are used
in the expression or action
> OC-2047 Absolute vs Relative Rule Expression

- web/src/main/java/org/akaza/openclinica/controller/StudyModuleController.java
At Randomize Access Request where OCUI is not running , the user gets
email notification for the request.
> OC-6847 Randomize Module

- web/src/main/java/org/akaza/openclinica/control/submit/DataEntryServlet.java
The rule does not fired with <Run InitialDataEntry="false"
DoubleDataEntry="true" > setting
> OC-3333 The rule does not fired with <Run InitialDataEntry="false" DoubleDataEntry="true" > setting 

- web/src/main/webapp/WEB-INF/jsp/managestudy/viewEventDefinitionReadOnly.jsp
OC3.10 Dev Bug: Event Definition page has extra empty <td> tag that
stops UPOQ to work
> OC-7106 OC3.10 Dev Bug: Event Definition page has extra empty <td> tag that stops UPOQ to work

- web/src/main/java/org/akaza/openclinica/control/submit/DataEntryServlet.java
Audit Log does not record correctly the user name who performed the
Double Data Entry
> OC-7116 Audit Log does not record correctly the user name who performed the Double Data Entry

- core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- web/src/main/java/org/akaza/openclinica/control/submit/DataEntryServlet.java
OC doesn't allow user to Mark CRF Complete when required item is not answered but has a Discrepancy Note
> Oc 7136 OC doesn't allow user to Mark CRF Complete when required item is not answered but has a Discrepancy Note

- web/src/main/webapp/WEB-INF/jsp/printcrf.jsp
The look and readability of printable CRFs would be improved with some
whitespace in the margins.
> OC-7015 Add margins to printable CRFs

- web/src/main/java/org/akaza/openclinica/control/submit/DataEntryServlet.java
Hidden items in the repeating group causes undesirable forced reason for
change during administrative editing (no data update)
> OC-2049 Hidden items in the repeating group causes undesirable forced reason for change during administrative editing (no data update)

- web/src/main/java/org/akaza/openclinica/control/form/Validator.java
OpenClinica username length requirement (min. 5 chars) might conflict
with LDAP
> OC-7150 OpenClinica username length requirement (min. 5 chars) might conflict with LDAP

- .gitignore
I just noticed that Idea generated `stormpath/Stormpath.iml` file which was not excluded from version control. Then I started fixing that and made some cleaning in `.gitignore`. Maybe those changes will be useful for you as well. 
I've done the following changes:
- instead of mentioning file by file I've just excluded all the *.iml files from version control;
- moved all the IntelliJ related lines to special block(similar to Git and NetBeans blocks).
Please, accept this pull request if you think that it makes sense.
> Some .gitignore improvements

- web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
Fixed.
View this error at https://jira.openclinica.com/browse/OC-7499
> OC7499 : Now, empty end date events can be saved.

- core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- core/src/main/java/org/akaza/openclinica/bean/extract/odm/MetaDataReportBean.java
To be consistent in ODM output, IsDefaultVersion and OpenClinica:Removed properties should have Yes/No values instead of true/fale
> OC-7845 minor changes to ODM for consistency

- core/src/main/resources/properties/item_form_metadata_dao.xml
Oops Error occurs when attempting to view metadata of a second CRF AFTER
uploading the first CRF
> OC-8055 Oops Error occurs when attempting to view metadata of a second CRF AFTER uploading the first CRF

- web/src/main/java/org/akaza/openclinica/controller/helper/OCUserDTO.java
Adding JsonIgnoreProperties to OCUserDTO to prevent OC from breaking in case new properties are added to SBS before being added to Bridge
> Adding JsonIgnoreProperties to OCUserDTO to prevent OC from breaking

- core/src/main/java/org/akaza/openclinica/bean/core/ResolutionStatus.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
- web/src/main/java/org/akaza/openclinica/control/submit/EnterDataForStudyEventServlet.java
- web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudyEvent.jsp
- web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
- web/src/main/webapp/includes/global_functions_javascript.js
Fixed issue where parent window query icon was not updated when a new Query was created.
Note: as with 3.x, this logic only applies to creating new queries.  Modifying an existing query does not update the parent window query icon.
> 4x update query icon colors new

- web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
- web/src/main/webapp/WEB-INF/jsp/include/showTable.jsp
- web/src/main/webapp/WEB-INF/jsp/showMessage.jsp
- web/src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpressNew.jsp
- web/src/main/webapp/includes/styles.css
- For Bridge search boxes, change the default text to be blank (instead of “Study Subject ID”). For the top left header subject search box only, make the default text be “Study Subject ID”. Specifically, the following search boxes should be blank by default:
1. Tasks > CRFs
2. Tasks > Sites
3. Tasks > View Events
4. Tasks > View Datasets
5. Subject Matrix > View a subject 
- When optional fields are enabled for a study, the Add New Subject Window has a couple issues:
1. The labels for the optional fields (Person ID & Date of Birth) do not match the standard fields (see below).
2. If Date of Birth, Sex, or Person ID is configured to be required, those fields should have the same required style asterisk (*) as the other required fields. Make the asterisks red and put them right after the …
> Misc Cosmetic Issue Bridge

- web/src/main/resources/org/akaza/openclinica/i18n/notes.properties
- web/src/main/webapp/WEB-INF/jsp/admin/viewFullStudy.jsp
- web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
- web/src/main/webapp/WEB-INF/jsp/managestudy/findSubjects.jsp
- web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
On View Event screen forms that are not yet started are not displaying the correct icon (see top icon for Form 9 in this screenshot). On View Subject screen, all forms (started or not started) are displaying the wrong icon. On Subject Matrix, locked event is displaying the wrong icon. The icon for Locked Forms should be the “lock” icon for all started or not started forms on View Event and View Subject. The icon for Locked Events should also be the “lock” icon on the Subject Matrix.
before:
after:
> Manual Testing/Bug Fixing - Misc Cosmetic Issues (Oct 16 progress)

- web/src/main/webapp/WEB-INF/jsp/admin/viewCRF.jsp
- web/src/main/webapp/WEB-INF/jsp/admin/viewFullStudy.jsp
Tasks > Monitor and Manage Data > CRFs > Click the view icon for a CRF to open the View CRF Details page: Remove the text at the bottom - “Studies Using This CRF For Data Entry”
before:
after:
> Manual Testing/Bug Fixing - Misc Cosmetic Issues (Oct 19 progress)

- web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectServlet.java
- web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
- web/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
- web/src/main/webapp/WEB-INF/jsp/admin/viewCRF.jsp
- web/src/main/webapp/WEB-INF/jsp/include/sideInfo.jsp
- web/src/main/webapp/WEB-INF/jsp/managestudy/viewEventDefinitionReadOnly.jsp
- web/src/main/webapp/WEB-INF/jsp/managestudy/viewSite.jsp
- web/src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpressNew.jsp
View CRF Details page (in Bridge)
Remove Description field
before:
after:
Versions Table:
Remove Description and Revision Notes columns
before:
after:
Items Table
Remove Description column
after:
The repeating event “x2” should be made a hyperlink and placed closer to the visit status icon.
Data Specialist, Data Entry Person, Investigator, Clinical Research Coordinator - These roles get the Subject Matrix on login. Can we expand the Info pane on the left bar? Without this pane expanded, the user doesn’t see the study name, status, etc. We can probably just have it open on page load all the time for all users.
> Manual Testing/Bug Fixing - Misc Cosmetic Issues

- web/src/main/java/org/akaza/openclinica/controller/StudyController.java
- web/src/main/java/org/akaza/openclinica/service/LiquibaseOnDemandServiceImpl.java
- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
- web/src/main/webapp/WEB-INF/jsp/admin/viewFullStudy.jsp
- web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
- Brief Summary (in Overview and Section A) should show the study Description defined in Study Manager.
- Section B - Study Phase - Show the Display Text that is visible in the dropdown in Study Manager (example: “Phase I” not “PHASEI”)
Note:
I found out that description from study-manager not saved yet to database bridge so I save it to parameter protocolDescription.(let me know if that not proper place for it)
> Tasks > Monitor and Manage Data > View Study:

- core/src/main/java/org/akaza/openclinica/service/managestudy/ViewNotesFilterCriteria.java
- core/src/main/resources/queries/postgres/viewnotes.properties
- web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
- Queries table - Add Queries to Event End Date or Start Date and Subject Enrollment Date or Date of Birth. Go to the Queries table. Filter the table by the Item Name column and type “Date”. No results are returned even though this is an exact case match for the event/subject items. Filter by “date”. This returns all of the rows for the event/subject queries even though it is not a case match for the event/subject items. To match the behavior of other columns, filters should only return results that match the case entered (so “Date” should return each of the event/subject queries and “date” should not return any of them. See OC-8388
Note: 
- Filter incasensitive work fine on all column except for "Site ID" and "Item Type" somehow it failed to show any row after rendering(I still find the …
> OC-8388 Queries table

- web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
- web/src/main/resources/org/akaza/openclinica/i18n/notes.properties
- web/src/main/webapp/WEB-INF/jsp/admin/showCRFRow.jsp
- web/src/main/webapp/WEB-INF/jsp/admin/viewCRF.jsp
- web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
Login as a new user. Then remove that user from all studies. Then login to Bridge as that user.  You’ll see a screen like this:
Change the text from “Your current active study is [active study], but no role.” to “Your current active study is [active study], but you have not been assigned a role.”.
before:
after:
I'm still seeing the description column on cust7.dev-runtime. The Detailed Notes filter is working now, though. The Detailed Notes filter is working now, though.
View Subject Page
Page title is wrong. It now says “Subject Matrix for STUDYNAME”. It needs to be changed back to “View Subject: SUBJECTID”
> Edit Manual Testing/Bug Fixing - Misc Cosmetic Issues (27/10/17 progress)

- core/src/main/java/org/akaza/openclinica/service/managestudy/ViewNotesFilterCriteria.java
- Queries table - Add Queries to Event End Date and Start Date. Go to the Queries table. Filter the table by the Item Name column and type “Date”. End Date and Start Date are returned. Filter by “End”. End Date is returned. Filter by “End Date” (which is an exact match for what is displayed) and nothing is returned. I expect this filter should still return all rows that match “End Date”.
> Queries table - Problem filtering translate value

- core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoAPI.java
- web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
- web/src/main/webapp/WEB-INF/jsp/admin/showCRFRow.jsp
- web/src/main/webapp/WEB-INF/jsp/admin/viewCRF.jsp
- View CRF Details page (in Bridge)
Versions Table: Change View icon to open Preview view
- Manage Case Report Forms page - When you click the view button for a Form version (not the first view link for the top level form), it should open the form in Preview mode like how it opens when you click Preview in Study Designer. Right now it is opening it in Read-only mode.
NOTE:
There is no postMessage event fired after finish validating form in preview mode so I made it open in new tab.
> View CRF in preview mode

- web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
- web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableToolbar.java
Queries Table - Change order of columns when Show More is clicked - Move Date Created to between Site ID and Date Updated. Move Item Name, Item Value, and Item Type to between CRF Status and Detailed Notes.
Queries Table - Change order of columns in Brief (Hide) views - Move Item Name and  Item Value to between CRF and Detailed Notes.
> OC Cosmetic

- web/src/main/java/org/akaza/openclinica/control/admin/ListCRFServlet.java
- web/src/main/java/org/akaza/openclinica/control/admin/ViewCRFServlet.java
- web/src/main/resources/org/akaza/openclinica/i18n/notes.properties
CRF Details Page (Tasks > CRFs > click the View link for a CRF) - Remove all of the text from the left side Info (Other Info) section.
before:
after:
Manage CRFs Page (Tasks > CRFs) - Remove all of the text from the left side Info (Other Info) section.
before:
after:
Manage CRFs Page (Tasks > CRFs) - Change the text in the left side Instructions section to: “The Case Report Form (CRF) Library shows all CRFs available for use in this study. CRFs may have one or more versions, each with its own version name.”
before:
after:
> Edit Manual Testing/Bug Fixing - Misc Cosmetic Issues (012/11/17 progress)

- web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
If the current study/site status is “Locked” (for locked), “Frozen” (for frozen), or “Design” (for design/pending), show the status in the title bar in an orange box. 
If it is a Production study, show this between the study name and “ | Change” link.
Example:    PAB 19 (PAB19)  Locked  |   Change
before:
after:
If it is a Test study, show this between “Test Environment | “ and “ | Change” link.
Example:    PAB 19 (PAB19)  Test Environment  |  Frozen  |   Change
before:
after:
If status is Available, do not display the status in the title bar.
result:
> Edit Manual Testing/Bug Fixing - Misc Cosmetic Issues (17/11/17 progress)

- web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
- web/src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpressNew.jsp
- OC-8548 AWS Bridge instance is missing the Calendar Widget in the Add Subject Window
> OC-Cosmetic-Master

- core/src/main/java/org/akaza/openclinica/dao/managestudy/DiscrepancyNoteDAO.java
- core/src/main/java/org/akaza/openclinica/service/DiscrepancyNoteUtil.java
- core/src/main/resources/properties/discrepancy_note_dao.xml
- web/src/main/java/org/akaza/openclinica/control/managestudy/SignStudySubjectServlet.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
- web/src/main/webapp/WEB-INF/jsp/managestudy/signStudySubject.jsp
- web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudyEventSigned.jsp
Fixes for the following features:
The query count should reflect only the last entry for each query 
The Sign Subject page Edit and View links give me oops pages for a form that is not yet started. 
Sign Subject page table structure needs to be fixed.
Sign Event page issues are not as bad, but ideally will be fixed.
> Oc 8565 Show count of queries by form and status on Signature Page

- web/src/main/webapp/WEB-INF/jsp/managestudy/showEventByDefinitionRow.jsp
- web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudySubject.jsp
The Subject ID message still overlaps if a duplicate value is entered (see screenshot I just added here). The other error messages do not appear to overlap.
before:
after:
> Edit Manual Testing/Bug Fixing - Misc Cosmetic Issues (29/11/17 progress)

- web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudySubject.jsp
Edit Study Subject Details - Error messages for Subject ID, Secondary ID, and Person ID should not display overlapping text.
after:
> Edit Manual Testing/Bug Fixing - Misc Cosmetic Issues (30/11/17 progress)

- web/src/main/webapp/js/com/openclinica/renderer/ItemDefRenderer.js
- web/src/main/webapp/js/com/openclinica/renderer/StudyDataLoader.js
- web/src/main/webapp/js/com/openclinica/renderer/StudyRenderer.js
Short and similar item names in the same form can create mismatch values
in Print Crf HTML format in some cases.
> OC-8627 Short and similar item names in the same form can create mismatch values in Print Crf HTML format in some cases.

- web/src/main/resources/auth0.properties
OC-8818 Editing a user profile is not reflected in query widget dropdown
- Added two client properties as a default
> OC-8818 Editing a user profile is not reflected in query widget dropdown

- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
- web/src/main/webapp/WEB-INF/jsp/include/sideInfo.jsp
- web/src/main/webapp/WEB-INF/jsp/managestudy/restoreStudySubject.jsp
- web/src/main/webapp/WEB-INF/jsp/submit/createNewStudyEvent.jsp
- Bug on Instruction link(sidebar) after clicked(missing arrow and cannot be clicked anymore) on RestoreStudySubject page
- Bug on sidebar(dobel link show up after open) on CreateNewStudyEvent page (Task > Schedule Event)
> OC-8695 Add Quick Links section to left pane in Runtime and fixed some bugs on sidebar

- web/src/main/java/org/akaza/openclinica/control/managestudy/SignStudySubjectServlet.java
When a Participant is signed, forms opened do not show the signature attestation
> OC-9569 When a Participant is signed, forms opened do not show the signature attestation

- core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
Migrating fix from OC 3.14 - OC-8141: XML extract itemgroupdata issue using PGSQL 9.5
> Migrating fix from OC 3.14 - OC-8141: XML extract itemgroupdata issue using PGSQL 9.5

- core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/controller/OdmController.java
Webservice to get scheduled participate event forms from OC for the given participant
includes fixes for the following:
At publish time , enable participate. Now, it will display participatForm property
Changed formdata status to Initial data entry when available
Updated null json object into odm object with clinicalData and subjectData (if exist) in usecases where study is not available, subject is removed , no events scheduled..
> OC-9646 Webservice to get scheduled participate event forms from OC for the given participant

- web/src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java
When participant audit log is downloaded in xls format, participant's first name,email and phone number should be masked.
> OC-10441 When participant audit log is downloaded in xls format, participant's first name,email and phone number should be masked.

- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/java/org/akaza/openclinica/controller/KeycloakController.java
Reverting changes to Secure and Keyclock Controller where requestSchema was pointing to Public
when getting the status of Contacts Module
> OC-10507 Reverting changes to Secure and Keyclock Controller

- web/src/main/webapp/WEB-INF/jsp/managestudy/advancedSearch.jsp
- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
- remove calls to make audit log entry (backend now does that automatically)
- move Contacts API call so it's only when Participate/Advanced Search is enabled
- move Access Code API call so it's only when View Access Code is clicked
- Underline the "Show All" link
- Clear search inputs when Show All is clicked
> OC-10310 Advanced search (feedback)

- core/src/main/resources/migration/tenant/4.0-2019-04-05-OC-10127.xml
- core/src/main/resources/migration/tenant/release.xml
OC Item data table supports 3999 characters in a text field whereas Enketo form seems to fail on 2000 characters limit
> OC-10127 OC Item data table supports 3999 characters in a text field whereas Enketo form seems to fail on 2000 characters limit

- core/src/main/java/org/akaza/openclinica/service/participant/ParticipantServiceImpl.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/controller/UserController.java
- web/src/main/java/org/akaza/openclinica/service/ValidateServiceImpl.java
Wrong user is shown in audit log when PII entered through API, if the participant is already created
This PR also includes fixes for the OC-10634 and OC-10636 in addtion to OC-10631
> OC-10631 Wrong user is shown in audit log when PII entered through API, if the participant is already created

- web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
Completing an empty form causes a null user_id entry in the auditlog database table
> OC-10679 Completing an empty form causes a null user_id entry in the auditlog database table

- core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java
Unarchived Common Event does not appear on Participant Details page if it does not contain any form data
> OC-10753 Unarchived Common Event does not appear on Participant Details page if it does not contain any form data

- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
1. The import is unused, so the removal has no effect (actually optimizing, even)
2. Importing sun.* breaks compilation on non-Sun JDK (e.g. OpenJDK)
3. From Sun's Oracle themselves: "Why Developers Should Not Write Programs That Call 'sun' Packages": https://www.oracle.com/technetwork/java/faq-sun-packages-142232.html
> Remove unused sun.misc import

- core/src/main/java/org/akaza/openclinica/dao/hibernate/JobDetailDao.java
Logs for imported jobs are not shown at study level when CRF data is imported.
> OC-10842 Logs for imported jobs are not shown at study level when CRF data is imported.

- core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
Advanced Search Last Name and Secondary ID fields are displaying in Casebook audit log as encrypted values instead of "Masked"
> OC-10655 Advanced Search Last Name and Secondary ID fields are displaying in Casebook audit log as encrypted values instead of "Masked"

- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/service/UtilService.java
- web/src/main/java/org/akaza/openclinica/service/UtilServiceImpl.java
When a user with no role on site A, tries to update the participant PII that resides in site A, no error is shown
> OC-10641 When a user with no role on site A, tries to update the participant PII that resides in site A, no error is shown

- web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
OpenClinica:Current attribute not being included in cross-form data files for Non-Repeating Visit-Based event forms
> OC-11526 OpenClinica:Current attribute not being included in cross-form data files for Non-Repeating Visit-Based event forms

- pom.xml
- src/main/java/core/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
After failed publish, the customer is blocked to re-publish due to technical reason
> OC-11929 After failed publish, the customer is blocked to re-publish due to technical reason

- src/main/java/core/org/akaza/openclinica/service/crfdata/xform/EnketoAPI.java
oops error is reported while viewing form in participant matrix, with event status not scheduled
> OC-12567 oops error is reported while viewing form in participant matrix, with event status not scheduled

- src/main/java/org/akaza/openclinica/control/admin/DeleteEventCRFServlet.java
- src/main/java/org/akaza/openclinica/control/managestudy/RemoveEventCRFServlet.java
- src/main/java/org/akaza/openclinica/control/managestudy/RemoveStudyEventServlet.java
When user removes and restores a form under a signed event then event should become unsigned
> OC-10309 When user removes and restores a form under a signed event then event should become unsigned

- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
This PR include fixes for the following stories:
OC-12708 Workflow Status Display - Visit Events on Participant Details Page
OC-12709 Workflow Status Display - Visit Event Forms on Participant Details Page
OC-12748 Workflow Status Display - Visit Event Forms on Single Event Page
OC-12749 Workflow Status Display - Visit Events on Single Event Page
> OC-12708 Workflow Status Display - Visit Events on Participant Details Page

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- src/main/java/core/org/akaza/openclinica/bean/managestudy/StudyEventBean.java
- src/main/java/core/org/akaza/openclinica/domain/datamap/StudyEvent.java
- src/main/java/org/akaza/openclinica/control/managestudy/RestoreStudyEventServlet.java
This PR contains fixes for the following stories.
OC-12933 Signature attestation is appearing when form is getting unsigned
OC-10309 When user removes and restores a form under a signed event or the event itself then event should become unsigned
OC-12926 If completed signed common event is removed and then restored, no sign button appears after form is restored
> OC-12933 Signature attestation is appearing when form is getting unsigned

- src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
When visit based event is stopped, its getting extra attribute locked="No" in participant casebook and audit log
> OC-12867 When visit based event is stopped, its getting extra attribute locked="No" in participant casebook and audit log

- src/main/java/core/org/akaza/openclinica/dao/managestudy/ViewNotesDaoImpl.java
- src/main/resources/core/queries/postgres/viewnotes.properties
query table is not filtering item values for integer, decimal, and multi-selects
> OC-12421 query table is not filtering item values for integer, decimal, and multi-selects

- src/main/webapp/includes/styles.css
Remove redundant import that caused log error on console. Font source already handled on icomoon-style.css.
[OC-9536](https://jira.openclinica.com/browse/OC-9536)
> OC-9536 Runtime pages load with error about external font resource

- src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
Since first Eventcrf is created after studyEvent is fetched from db and hence null when fetched studyEvent.getEventCrfs()
> OC-12659: Reverted OC-12563 fetching eventCrfs from EventCrfDao

- src/main/java/org/akaza/openclinica/control/login/ChangeStudyServlet.java
In my last PR, When moving the populateCustomUserRoles() from SecureController to ChangeStudyServlet (https://github.com/OpenClinica/OpenClinica/pull/3124), wrongly copied the old code with null condition. So removed it now
> OC-13088: Removed the Null condition to get all the latest values from userRoles

- src/main/java/core/org/akaza/openclinica/dao/core/CoreResources.java
- src/main/java/core/org/akaza/openclinica/web/rest/client/auth/impl/KeycloakConfig.java
- src/main/java/core/org/akaza/openclinica/web/rest/client/auth/impl/MasterKeycloakConfig.java
- src/main/java/org/akaza/openclinica/config/CustomKeycloakConfigResolver.java
- src/main/resources/auth.properties
- src/main/resources/datainfo.properties
This commit will remove the existing auth.properties file and move it to datainfo.properties.
auth.realm:
auth.client-id:
auth.client-secret:
auth.base-url
I will manually update the datainfo.properties on dev to reflect this change. Staging and production will be scripted.
Devs will have to update their local datainfo.properties.
> Merging auth.properties into datainfo.properties
