- core/src/main/java/org/akaza/openclinica/bean/rule/FileProperties.java
- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
Large file uploads to a form fail
> OC-10029 Large file uploads to a form fail

- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
Removing rules in RT showing a Oops page
> OC-9944 Removing rules in RT showing a Oops page

- core/src/main/java/org/akaza/openclinica/domain/rule/action/ActionProcessorFacade.java
- core/src/main/java/org/akaza/openclinica/domain/rule/action/NotificationActionProcessor.java
- core/src/main/java/org/akaza/openclinica/logic/rulerunner/BeanPropertyRuleRunner.java
Notification Rule not firing on Participate participant
> OC-10139     Notification Rule not firing on Participate participant

- core/src/main/java/org/akaza/openclinica/domain/rule/action/ActionProcessorFacade.java
- core/src/main/java/org/akaza/openclinica/domain/rule/action/NotificationActionProcessor.java
- core/src/main/java/org/akaza/openclinica/logic/rulerunner/BeanPropertyRuleRunner.java
Notification Rule not firing on Participate participant
> 10139  Notification Rule not firing on Participate participant

- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
https://jira.openclinica.com/browse/OC-10165
> OC-10165 Contact information modal window header needs to be updated

- core/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
https://jira.openclinica.com/browse/OC-9621
> OC-9621 Update Message displayed after user deletes Participant Form

- core/src/main/java/org/akaza/openclinica/domain/rule/action/NotificationActionProcessor.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
- web/src/main/java/org/akaza/openclinica/web/pform/PFormCache.java
Notification Rule not firing on Participate participant
> 10139 Notification Rule not firing on Participate participant

- web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
Don't load cross form data if cross form not specified in form
> OC-10258 Don't load cross form data if cross form not specified in form 

- core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- core/src/main/java/org/akaza/openclinica/dao/core/CoreResources.java
Cross form logic issue with displaying correct user role
> 10076 Cross form logic issue with displaying correct user role

- core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
Improve load time of details page
> 10260 Improve load time of details page

- web/src/main/webapp/WEB-INF/jsp/admin/viewCRF.jsp
https://jira.openclinica.com/browse/OC-9714
> OC-9714 CRF page needs to remove Rule links

- core/src/main/java/org/akaza/openclinica/service/participant/ParticipantServiceImpl.java
- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/ReassignStudySubjectServlet.java
- web/src/main/java/org/akaza/openclinica/control/submit/AddNewSubjectServlet.java
Incorrect System-Generated Participant ID is Created After participant reassignment
> OC-9644 Incorrect System-Generated Participant ID is Created After participant reassignment

- core/src/main/java/org/akaza/openclinica/service/rule/RuleSetListenerService.java
- core/src/main/resources/migration/tenant/inserts.xml
- web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/EventProcessor.java
- web/src/main/java/org/akaza/openclinica/service/ParticipateServiceImpl.java
- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
Notification action - multiple emails are getting sent
> Oc 10279 Notification action - multiple emails are getting sent

- core/src/main/java/org/akaza/openclinica/dao/hibernate/StudyDao.java
- core/src/main/resources/properties/study_dao.xml
- web/src/main/java/org/akaza/openclinica/control/MainMenuServlet.java
- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/java/org/akaza/openclinica/control/login/ChangeStudyServlet.java
- web/src/main/java/org/akaza/openclinica/controller/KeycloakController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyController.java
- web/src/main/java/org/akaza/openclinica/service/CallbackServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/StudyBuildService.java
- web/src/main/java/org/akaza/openclinica/service/StudyBuildServiceImpl.java
OC-10247 Study Role display missing in RT after Go from SM
>  OC-10269 Update handling of user role changes during a user's session

- core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- core/src/main/resources/org/akaza/openclinica/applicationContext-core-hibernate.xml
- core/src/main/resources/properties/audit_dao.xml
- core/src/main/resources/properties/study_dao.xml
- web/src/main/java/org/akaza/openclinica/control/MainMenuServlet.java
- web/src/main/java/org/akaza/openclinica/control/core/CoreSecureController.java
- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/java/org/akaza/openclinica/control/login/ChangeStudyServlet.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectAuditLogServlet.java
- web/src/main/java/org/akaza/openclinica/controller/helper/SetUpStudyRole.java
- web/src/main/java/org/akaza/openclinica/service/AuditLogEventServiceImpl.java
- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
Audit add and change actions of a user on participant contact information
> OC-9858 Audit add and change actions of a user on participant contact information

- core/src/main/java/org/akaza/openclinica/domain/datamap/CrfVersion.java
- core/src/main/java/org/akaza/openclinica/domain/datamap/FormLayout.java
- core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java
- core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java
Performance improvement. Changed getEventCrf() fetch property from EAGER into LAZY
> Performance improvement. 

- core/src/main/java/org/akaza/openclinica/logic/importdata/ImportDataHelper.java
> OC-10233 NonRepeating Common Event data duplicated

- core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- core/src/main/java/org/akaza/openclinica/bean/odmbeans/AuditLogBean.java
- core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
- core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
- core/src/main/resources/org/akaza/openclinica/applicationContext-core-hibernate.xml
- core/src/main/resources/properties/audit_dao.xml
- core/src/main/resources/properties/study_dao.xml
- web/src/main/java/org/akaza/openclinica/control/MainMenuServlet.java
- web/src/main/java/org/akaza/openclinica/control/core/CoreSecureController.java
- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/java/org/akaza/openclinica/control/login/ChangeStudyServlet.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectAuditLogServlet.java
- web/src/main/java/org/akaza/openclinica/controller/helper/SetUpStudyRole.java
- web/src/main/java/org/akaza/openclinica/service/AuditLogEventServiceImpl.java
- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
Audit events for add and change participant information in casebook and extracts
> OC-10321 Audit events for add and change participant information in casebook and extracts

- web/src/main/java/org/akaza/openclinica/control/submit/ImportRuleServlet.java
https://jira.openclinica.com/browse/OC-9409
> OC-9409 Some user roles are unable to download the Data Import template

- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
(Jing's feedback)
https://jira.openclinica.com/browse/OC-10185?focusedCommentId=171725&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-171725
> OC-10185 UI issues for the Invite and View access code modal windows

- core/src/main/java/org/akaza/openclinica/dao/hibernate/StudyDao.java
- core/src/main/java/org/akaza/openclinica/dao/hibernate/StudyEventDao.java
- core/src/main/java/org/akaza/openclinica/domain/rule/action/NotificationActionProcessor.java
- core/src/main/java/org/akaza/openclinica/service/EventService.java
- core/src/main/java/org/akaza/openclinica/service/JobTriggerService.java
- core/src/main/java/org/akaza/openclinica/service/crfdata/BeanPropertyService.java
- web/src/main/java/org/akaza/openclinica/control/login/ChangeStudyServlet.java
- web/src/main/java/org/akaza/openclinica/controller/KeycloakController.java
- web/src/main/java/org/akaza/openclinica/controller/UserController.java
- web/src/main/java/org/akaza/openclinica/service/CallbackService.java
- web/src/main/java/org/akaza/openclinica/service/CallbackServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/StudyBuildService.java
- web/src/main/java/org/akaza/openclinica/service/StudyBuildServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/UserService.java
- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/rest/client/auth/impl/KeycloakClientImpl.java
- web/src/main/java/org/akaza/openclinica/web/rest/client/cs/impl/CustomerServiceClientImpl.java
Run on schedule is not working with Event action rule
> OC-10300 Run on schedule is not working with Event action rule

- core/src/main/java/org/akaza/openclinica/bean/extract/odm/FullReportBean.java
- core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
- web/src/main/java/org/akaza/openclinica/controller/ODMClinicalDataController.java
- web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
- web/src/main/java/org/akaza/openclinica/web/restful/MetadataCollectorResource.java
- web/src/main/java/org/akaza/openclinica/web/restful/ODMClinicaDataResource.java
Load Participant Details page metadata first to improve loading of large participant records
> OC-10332 Load Participant Details page metadata first to improve loading of large participant records

- core/pom.xml
- core/src/main/java/org/akaza/openclinica/domain/rule/action/NotificationActionProcessor.java
- core/src/main/java/org/akaza/openclinica/logic/rulerunner/BeanPropertyRuleRunner.java
- core/src/main/java/org/akaza/openclinica/service/NotificationService.java
- core/src/main/java/org/akaza/openclinica/service/dto/CustomerDTO.java
- core/src/main/java/org/akaza/openclinica/service/dto/ModuleConfigAttributeDTO.java
- core/src/main/java/org/akaza/openclinica/service/dto/ModuleConfigDTO.java
- core/src/main/java/org/akaza/openclinica/service/dto/StudyEnvironmentDTO.java
- core/src/main/java/org/akaza/openclinica/service/rule/RuleSetService.java
- core/src/main/resources/org/akaza/openclinica/applicationContext-core-service.xml
Run on schedule is not working with Notification action rule
> OC-10343 Run on schedule is not working with Notification action rule

- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp
- Fix double-entries bug reported by Krikor
- Add loading indicator
> OC-10332: Improve Participant Details Page performance

- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
Don't store participant details in user account table
> OC-10366 Don't store participant details in user account table

- web/src/main/java/org/akaza/openclinica/control/submit/ImportCRFDataServlet.java
- web/src/main/java/org/akaza/openclinica/controller/DataController.java
- web/src/main/java/org/akaza/openclinica/service/DataImportService.java
- web/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFDataService.java
- web/src/main/java/org/akaza/openclinica/web/job/ImportSpringJob.java
solution option 2 ---change current implementation pattern, for common events, will finish all validation first, if pass validation, then insert into database
> OC-10254 v2 Empty Common Event created on failed import

- web/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFDataService.java
XML import into non-repeating common event does not allow overwrite
> OC-10365:XML import into non-repeating common event does not allow overwrite

- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
- web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
- web/src/main/webapp/includes/styles.css
https://jira.openclinica.com/browse/OC-10329
> OC-10329 Update Participant ID Search box UI

- core/src/main/java/org/akaza/openclinica/dao/hibernate/StudyEventDao.java
- core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
- core/src/main/resources/org/akaza/openclinica/applicationContext-core-service.xml
Rest call returning all participants data points are duplicating the first participant's data to the others - Present in Staging not Prod
> OC-10343 Rest call returning all participants data points are duplicating the first participant's data to the others - Present in Staging not Prod

- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
https://jira.openclinica.com/browse/OC-10397
> OC-10397 Update Participant Details Page default view and persistence to include Collapsed Common Events

- web/src/main/java/org/akaza/openclinica/control/submit/ImportCRFDataServlet.java
- web/src/main/java/org/akaza/openclinica/controller/DataController.java
- web/src/main/java/org/akaza/openclinica/controller/helper/RestfulServiceHelper.java
- web/src/main/java/org/akaza/openclinica/service/DataImportService.java
- web/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFDataService.java
- web/src/main/java/org/akaza/openclinica/web/job/ImportSpringJob.java
majorly focuse testing the fix of OC-10254 and 10374
> merge fix from OC-10254_v2 branch to branch staging 464---

- core/src/main/java/org/akaza/openclinica/bean/login/ParticipantDTO.java
- core/src/main/java/org/akaza/openclinica/dao/hibernate/StudySubjectDao.java
- core/src/main/java/org/akaza/openclinica/domain/datamap/StudySubjectDetail.java
- core/src/main/java/org/akaza/openclinica/domain/rule/action/NotificationActionProcessor.java
- core/src/main/java/org/akaza/openclinica/service/OCParticipantDTO.java
- core/src/main/java/org/akaza/openclinica/service/OCUserDTO.java
- core/src/main/resources/migration/tenant/4.0-2019-01-08-OC-10065.xml
- core/src/main/resources/migration/tenant/4.0-2019-02-14-OC-10324.xml
- core/src/main/resources/migration/tenant/release.xml
- web/src/main/java/org/akaza/openclinica/controller/UserController.java
- web/src/main/java/org/akaza/openclinica/service/UserService.java
- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
OC-10324 Participant identifier requirements for advanced search
OC-10312 Configure Study to use Participant Advanced Search 
We need to add a property in datainfo.properties file. (participantAdvanceSearch=enabled)
Also this PR include fix for OC-10424. Participant mobile number is not being captured
> OC-10324 Participant identifier requirements for advanced search

- web/src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java
When participant audit log is downloaded in xls format, participant's first name,email and phone number should be masked.
> OC-10441 When participant audit log is downloaded in xls format, participant's first name,email and phone number should be masked.

- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
https://jira.openclinica.com/browse/OC-10108
> OC-10108 Add Character limit on name, email and phone numbers

- web/src/main/java/org/akaza/openclinica/controller/UserController.java
- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
Advanced Participant Search functionality
> OC-10315 Advanced Participant Search functionality

- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/java/org/akaza/openclinica/service/CallbackServiceImpl.java
> OC-10468 Oops Error on new user invite next tab beside an existing user

- core/src/main/java/org/akaza/openclinica/validator/ParticipantValidator.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/controller/UserController.java
- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/UtilService.java
- web/src/main/java/org/akaza/openclinica/service/UtilServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ValidateService.java
- web/src/main/java/org/akaza/openclinica/service/ValidateServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/util/ErrorConstants.java
- web/src/main/java/org/akaza/openclinica/web/util/HeaderUtil.java
Add participant endpoints should not generate participant ID when study is set to system generated
> OC-10456 Add participant endpoints should not generate participant ID when study is set to system generated

- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
- web/src/main/webapp/WEB-INF/jsp/managestudy/advancedSearch.jsp
- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
[OC-10315](https://jira.openclinica.com/browse/OC-10315)
[OC-10316](https://jira.openclinica.com/browse/OC-10316)
> OC-10310 Advanced search

- core/src/main/java/org/akaza/openclinica/bean/service/StudyParameterConfig.java
- core/src/main/resources/migration/tenant/4.0-2018-04-17-OC-9318.xml
- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/java/org/akaza/openclinica/controller/ContactsModuleController.java
- web/src/main/java/org/akaza/openclinica/controller/dto/ContactsModuleDTO.java
- web/src/main/java/org/akaza/openclinica/service/ContactsModuleService.java
- web/src/main/java/org/akaza/openclinica/service/ContactsModuleServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ValidateService.java
- web/src/main/java/org/akaza/openclinica/service/ValidateServiceImpl.java
API endpoint to enable/disable contacts module
> OC-10495 API endpoint to enable/disable contacts module

- core/src/main/java/org/akaza/openclinica/dao/login/UserAccountDAO.java
- core/src/main/java/org/akaza/openclinica/service/auth/TokenServiceImpl.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/controller/helper/MessageLogger.java
- web/src/main/java/org/akaza/openclinica/controller/helper/RestfulServiceHelper.java
- web/src/main/java/org/akaza/openclinica/service/StudyEventService.java
- web/src/main/java/org/akaza/openclinica/service/StudyEventServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
--- more changes focus on Async and write to log files
> OC-10413:Ability to schedule events for a list of participants

- web/src/main/java/org/akaza/openclinica/control/managestudy/AdvancedSearchServlet.java
- web/src/main/java/org/akaza/openclinica/controller/KeycloakController.java
- web/src/main/java/org/akaza/openclinica/controller/UserController.java
- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
- web/src/main/resources/org/akaza/openclinica/i18n/exceptions.properties
- web/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
This PR will fix the following issues.
View Participant page does not load PII when participate is Disabled.
Change study throwing Oops error page with Root user.
/ParticipantsSearch page should not load when ContactsModule is disabled or the User does not have appropiate roles.
> OC-10507 Details Page Participate/Contacts table/modal not populating

- core/src/main/java/org/akaza/openclinica/bean/managestudy/SubjectTransferBean.java
- core/src/main/java/org/akaza/openclinica/domain/datamap/StudySubjectDetail.java
- core/src/main/java/org/akaza/openclinica/service/dto/AuditLogEventDTO.java
- core/src/main/java/org/akaza/openclinica/service/participant/ParticipantService.java
- core/src/main/java/org/akaza/openclinica/service/participant/ParticipantServiceImpl.java
- core/src/main/java/org/akaza/openclinica/validator/ParticipantValidator.java
- core/src/main/resources/migration/tenant/inserts.xml
- core/src/main/resources/properties/audit_dao.xml
- web/src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectAuditLogServlet.java
- web/src/main/java/org/akaza/openclinica/controller/AuditLogEventController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/controller/dto/ParticipantRestfulRequestDTO.java
- web/src/main/java/org/akaza/openclinica/service/AuditLogEventService.java
- web/src/main/java/org/akaza/openclinica/service/AuditLogEventServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/UtilServiceImpl.java
- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
Provide an ability to capture participant PII using a webservice
> OC-9682 Provide an ability to capture participant PII using a webservice

- core/src/main/java/org/akaza/openclinica/dao/hibernate/CryptoConverter.java
- core/src/main/java/org/akaza/openclinica/service/participant/ParticipantServiceImpl.java
- core/src/main/resources/migration/tenant/4.0-2019-03-26-OC-10529.xml
- core/src/main/resources/migration/tenant/release.xml
- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
Add Database triggers for PII auditing
> OC-10529 Add Database triggers for PII auditing

- web/src/main/webapp/WEB-INF/jsp/managestudy/advancedSearch.jsp
- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
- fix "Show All" link not working after doing search returning empty result
- fix inputs maxlength
> OC-10315 Advanced search:

- web/src/main/java/org/akaza/openclinica/controller/helper/RestfulServiceHelper.java
- web/src/main/java/org/akaza/openclinica/web/crfdata/ImportHelper.java
> OC-10469 and OC-10549

- web/src/main/webapp/includes/styles.css
- web/src/main/webapp/js/lib/bootstrap-tour.js
https://jira.openclinica.com/browse/OC-10383
> OC-10383 Confirm Participant ID from Participant Matrix(disable opening with right click)

- web/src/main/webapp/includes/styles.css
- web/src/main/webapp/js/lib/bootstrap-tour.js
- changing the "Checking" button to "Continue"
- updating the window title
- adding a label for the verification text field 
- updating the error message text for when there is no match
- extra: esc key will trigger cancel button
> OC-10383 Confirm Participant ID from Participant Matrix(feedback)

- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectsServlet.java
- web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
https://jira.openclinica.com/browse/OC-10389
> OC-10389 Disable paste into Participant ID search box

- web/src/main/webapp/includes/styles.css
- web/src/main/webapp/js/lib/bootstrap-tour.js
https://jira.openclinica.com/browse/OC-10383
> OC-10383 Confirm Participant ID from Participant Matrix(feedback: update style)

- web/src/main/java/org/akaza/openclinica/control/form/Validator.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
… the error with a errorCode and input params
> OC-10470 and OC10549

- web/src/main/java/org/akaza/openclinica/controller/JobController.java
- web/src/main/java/org/akaza/openclinica/controller/UserController.java
- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
Ability to extract participant access code for all participants
> OC-9684 Ability to extract participant access code for all participants 

- web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
Item Data is not saved on form and there is no error message shown to the user
> OC-10567 Item Data is not saved on form and there is no error message shown to the user

- core/src/main/java/org/akaza/openclinica/service/participant/ParticipantServiceImpl.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
Error creating Participant via API
> OC-10564 Error creating Participant via API

- web/src/main/java/org/akaza/openclinica/service/StudyBuildServiceImpl.java
OC-10596 Participate status is not reflected in runtime correctly on qe dev environment
> OC-10596 Participate status is not reflected in runtime correctly on qe dev environment

- web/src/main/java/org/akaza/openclinica/control/managestudy/JobsServlet.java
- web/src/main/java/org/akaza/openclinica/view/Page.java
- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
- web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
- web/src/main/webapp/WEB-INF/jsp/managestudy/jobs.jsp
- web/src/main/webapp/WEB-INF/web.xml
- web/src/main/webapp/includes/styles.css
https://jira.openclinica.com/browse/OC-10483
> OC-10483 Add a page to runtime to access the logfile of bulk operations

- web/src/main/java/org/akaza/openclinica/controller/UserController.java
Incorrect errorCode by extract participant Info endpoint when studyOID or siteOID are value but user has no role define
> OC-10612 Incorrect errorCode by extract participant Info endpoint when studyOID or siteOID are value but user has no role define

- web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
Failed to Save Changes error on form using repeat_count
> OC-10619 Failed to Save Changes error on form using repeat_count

- core/src/main/java/org/akaza/openclinica/dao/managestudy/StudyEventDAO.java
https://jira.openclinica.com/browse/OC-10488
> OC-10488 Remove and Restore Participant generate Oops errors

- web/src/main/webapp/WEB-INF/jsp/submit/viewRules.jsp
https://jira.openclinica.com/browse/OC-10175
> OC-10175 Run link on individual rules needs to be removed

- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
- web/src/main/webapp/WEB-INF/jsp/managestudy/jobs.jsp
(Joe's feedback)
https://jira.openclinica.com/browse/OC-10483?focusedCommentId=176058&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-176058
> OC-10483 feedback fix (Jobs/Bulkfile logs)

- pom.xml
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
OC 10635 : Alphabets are being allowed in phone numbers when PII is entered through API. 
OC-10637: When PII is added through API, syntax for email is not validated
> OC 10635 Alphabets are being allowed in phone numbers when PII is entered through API. 

- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
Subject OID is not included in the bulk add participant endpoints
> Oc 10666 Subject OID is not included in the bulk add participant endpoints

- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
Add participant at study level API to be removed
Note: Once done, then Nginx configuration to block these endpoint including the get Participants list endpoint to be removed so that get participant list endpoint could be available again.
> OC-10632 Add participant at study level API to be removed

- core/src/main/java/org/akaza/openclinica/bean/login/ResponseSuccessStudyParticipantDTO.java
- core/src/main/java/org/akaza/openclinica/bean/managestudy/SubjectTransferBean.java
- core/src/main/java/org/akaza/openclinica/service/OCUserDTO.java
- core/src/main/java/org/akaza/openclinica/service/participant/ParticipantService.java
- core/src/main/java/org/akaza/openclinica/service/participant/ParticipantServiceImpl.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/controller/UserController.java
- web/src/main/java/org/akaza/openclinica/service/ValidateService.java
- web/src/main/java/org/akaza/openclinica/service/ValidateServiceImpl.java
Wrong user is shown in audit log when PII entered through API, if the participant is already created
> OC-10631 Wrong user is shown in audit log when PII entered through API, if the participant is already created

- core/src/main/java/org/akaza/openclinica/bean/login/ResponseSuccessStudyParticipantDTO.java
- core/src/main/java/org/akaza/openclinica/bean/managestudy/SubjectTransferBean.java
- core/src/main/java/org/akaza/openclinica/service/OCUserDTO.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/controller/UserController.java
- web/src/main/java/org/akaza/openclinica/service/ValidateService.java
- web/src/main/java/org/akaza/openclinica/service/ValidateServiceImpl.java
Provide an ability to register a participant for Participate using a webservice
> OC-10455 Provide an ability to register a participant for Participate using a webservice

- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
Feedback from Paul:
https://jira.openclinica.com/browse/OC-10565?focusedCommentId=177203&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-177203
> OC-10565 The title of Edit Contact Info needs to be user friendly

- core/src/main/resources/migration/tenant/4.0-2019-04-10-OC-10430.xml
- core/src/main/resources/migration/tenant/4.0-2019-04-24-OC-10430.xml
- core/src/main/resources/migration/tenant/release.xml
In the audit log event table, Some records have user ID as null in the database for some studies
> OC-10430 added foreign key and not null constriant to user_id column in audit_log_event table

- core/src/main/java/org/akaza/openclinica/bean/core/Term.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/controller/UserController.java
- web/src/main/java/org/akaza/openclinica/service/ValidateService.java
- web/src/main/java/org/akaza/openclinica/service/ValidateServiceImpl.java
user-control extractParticipantsInfo Swagger API call by DM fails
> OC-10695 user-control extractParticipantsInfo Swagger API call by DM fails

- web/src/main/java/org/akaza/openclinica/controller/JobController.java
- web/src/main/java/org/akaza/openclinica/web/util/ErrorConstants.java
When an invalid job uuid is passed to download file then appropriate error message should be returned
> OC-10674 When an invalid job uuid is passed to download file then appropriate error message should be returned

- web/src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableToolbar.java
- web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableToolbar.java
https://jira.openclinica.com/browse/OC-10407
> OC-10407 Default results count resets to 15 when user filters the list

- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp
https://jira.openclinica.com/browse/OC-10744
> OC-10744 Details Page Won't Load in Customer Prod environment, will load in Test

- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
https://jira.openclinica.com/browse/OC-10675
> OC-10675 Stopper when capturing Mobile number: fix incorrect flag

- web/src/main/webapp/js/app.js
- web/src/main/webapp/js/com/openclinica/renderer/ODMRenderer.js
- web/src/main/webapp/js/com/openclinica/renderer/PageHeaderRenderer.js
- web/src/main/webapp/js/com/openclinica/renderer/StudyDataLoader.js
- web/src/main/webapp/js/com/openclinica/renderer/StudyRenderer.js
- web/src/main/webapp/template/print_page_header.html
Reverts OpenClinica/OpenClinica#1514
> Revert "Oc 3214"

- web/src/main/webapp/js/app.js
- web/src/main/webapp/js/com/openclinica/renderer/ODMRenderer.js
- web/src/main/webapp/js/com/openclinica/renderer/PageHeaderRenderer.js
- web/src/main/webapp/js/com/openclinica/renderer/StudyDataLoader.js
- web/src/main/webapp/js/com/openclinica/renderer/StudyRenderer.js
- web/src/main/webapp/template/print_page_header.html
Reverts OpenClinica/OpenClinica#2049
> Revert "Revert "Oc 3214""

- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/service/StudyEventServiceImpl.java
Create study event endpoint is always returning error code that no subject found
> OC-10743     Create study event endpoint is always returning error code that no subject found

- web/src/main/webapp/WEB-INF/jsp/managestudy/jobs.jsp
https://jira.openclinica.com/browse/OC-10771
> OC-10771 Add site name information to each job on the jobs page

- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/controller/UserController.java
- web/src/main/java/org/akaza/openclinica/service/ValidateService.java
- web/src/main/java/org/akaza/openclinica/service/ValidateServiceImpl.java
Using a REST client, sometimes an authorized user is returned an noSufficientPrivileges message
> OC-10769 Using a REST client, sometimes an authorized user is returned an noSufficientPrivileges message

- web/src/main/java/org/akaza/openclinica/controller/JobController.java
- web/src/main/webapp/WEB-INF/jsp/managestudy/jobs.jsp
https://jira.openclinica.com/browse/OC-10733
> OC-10733 Ability to view the logfile of each job within openclinica

- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
XML Import data case sensitivity
> OC-10803 XML Import data case sensitivity

- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/dto/DataImportReport.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
Sometimes the XML file with just one or two event data gets stuck in "in progress" status
> OC-10810     Sometimes the XML file with just one or two event data gets stuck in "in progress" status

- core/src/main/java/org/akaza/openclinica/bean/submit/crfdata/StudyEventDataBean.java
- core/src/main/java/org/akaza/openclinica/domain/datamap/StudyEvent.java
- core/src/main/resources/properties/cd_odm_mapping.xml
- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/controller/UserController.java
- web/src/main/java/org/akaza/openclinica/controller/dto/DataImportReport.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ValidateService.java
- web/src/main/java/org/akaza/openclinica/service/ValidateServiceImpl.java
This merge will fix OC-10802 mark complete issue, 
also 10769 noRoleSetup and noSuffPrivelege
also study event end date issues
> OC 10802     Marking a form complete in XML import makes the event also complete when event has other forms in not started status

- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
Import should be allowed for a site participant with a study OID in the study tag
> OC-10801     Import should be allowed for a site participant with a study OID in the study tag

- web/src/main/java/org/akaza/openclinica/controller/OdmController.java
Participate does not pass Form name with non-ASCII (UTF-8) chars to Dashboard
> OC-9938     Participate does not pass Form name with non-ASCII (UTF-8) chars to Dashboard

- core/src/main/java/org/akaza/openclinica/dao/hibernate/JobDetailDao.java
- web/src/main/java/org/akaza/openclinica/controller/JobController.java
- web/src/main/java/org/akaza/openclinica/service/JobServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/util/ErrorConstants.java
> OC-10772  Jobs UI access issue

- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
Import should be allowed for a site participant with a study OID in the study tag
> OC-10801 Import should be allowed for a site participant with a study OID in the study tag

- core/src/main/java/org/akaza/openclinica/dao/hibernate/JobDetailDao.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
Site level user is unable to import data into site level participant using REST API
> OC-10841 Site level user is unable to import data into site level participant using REST API

- core/src/main/java/org/akaza/openclinica/domain/xform/dto/Bind.java
- core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- core/src/main/resources/properties/xformMapping.xml
- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
- web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
- web/src/main/java/org/akaza/openclinica/controller/EditFormController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/controller/dto/DataImportReport.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
- web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
Remove study level endpoints for create study event and bulk create study event in bulk
> OC-10742 Remove study level endpoints for create study event and bulk create study event in bulk

- core/src/main/java/org/akaza/openclinica/domain/xform/dto/Bind.java
- core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- core/src/main/resources/properties/xformMapping.xml
- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
- web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
- web/src/main/java/org/akaza/openclinica/controller/EditFormController.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
- web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
Save data from forms using contact data reserved keywords
> OC-10709     Save data from forms using contact data reserved keywords

- core/src/main/java/org/akaza/openclinica/domain/xform/dto/Bind.java
- core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- core/src/main/resources/properties/xformMapping.xml
- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
- web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
- web/src/main/java/org/akaza/openclinica/controller/EditFormController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/controller/dto/DataImportReport.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
- web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
Add timestamp information in the import logfile for each record
> Oc 10843 Add timestamp information in the import logfile for each record

- core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- core/src/main/java/org/akaza/openclinica/domain/rule/action/NotificationActionProcessor.java
- core/src/main/java/org/akaza/openclinica/service/participant/ParticipantServiceImpl.java
- core/src/main/resources/migration/tenant/4.0-2019-05-22-OC-10631.xml
- core/src/main/resources/migration/tenant/release.xml
- web/src/main/java/org/akaza/openclinica/control/admin/DeleteEventCRFServlet.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/RemoveEventCRFServlet.java
- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
- web/src/main/webapp/WEB-INF/jsp/admin/deleteEventCRF.jsp
- web/src/main/webapp/WEB-INF/jsp/managestudy/removeEventCRF.jsp
Wrong user is shown in audit log when PII entered through API, if the participant is already created
> OC 10631 Wrong user is shown in audit log when PII entered through API, if the participant is already created

- core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- core/src/main/java/org/akaza/openclinica/domain/rule/action/NotificationActionProcessor.java
Expose participant ID, study ID, site ID, and site name variables for the Notification Action rules
> OC 9687 Expose participant ID, study ID, site ID, and site name variables for the Notification Action rules

- core/src/main/java/org/akaza/openclinica/logic/importdata/PipeDelimitedDataHelper.java
- web/src/main/java/org/akaza/openclinica/controller/helper/RestfulServiceHelper.java
- web/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFDataService.java
> OC10832:ata got skipped when the expected result was to import the data

- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
https://jira.openclinica.com/browse/OC-10770
> OC-10770 Participate/Contact show/hide in Detail page gets Role confused when Study jump

- core/src/main/java/org/akaza/openclinica/dao/managestudy/StudySubjectDAO.java
- core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- core/src/main/resources/properties/cd_odm_mapping.xml
- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
- web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
- web/src/main/java/org/akaza/openclinica/controller/EditFormController.java
- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/JobController.java
- web/src/main/java/org/akaza/openclinica/controller/OdmController.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ParticipateServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ValidateService.java
- web/src/main/java/org/akaza/openclinica/service/ValidateServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
- web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
Job Log File name brakes if Study Name contains UTF-8
> OC 10887 Job Log File name brakes if Study Name contains UTF-8

- core/src/main/java/org/akaza/openclinica/dao/managestudy/StudySubjectDAO.java
- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ValidateService.java
- web/src/main/java/org/akaza/openclinica/service/ValidateServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
Add timestamp information in the import logfile for each record
> OC-10843 Add timestamp information in the import logfile for each record

- core/src/main/java/org/akaza/openclinica/dao/managestudy/StudySubjectDAO.java
- core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
- web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
- web/src/main/java/org/akaza/openclinica/controller/EditFormController.java
- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/OdmController.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ParticipateServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ValidateService.java
- web/src/main/java/org/akaza/openclinica/service/ValidateServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
- web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
Allow Participant users to open forms with contact information and save data
> Oc 10876 Allow Participant users to open forms with contact information and save data

- core/src/main/java/org/akaza/openclinica/dao/managestudy/StudySubjectDAO.java
- core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- core/src/main/resources/properties/cd_odm_mapping.xml
- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
- web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
- web/src/main/java/org/akaza/openclinica/controller/EditFormController.java
- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/OdmController.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ParticipateServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ValidateService.java
- web/src/main/java/org/akaza/openclinica/service/ValidateServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
- web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
OC 10884  XML file with non-ODM schema
OC-10881 New XML Import breaks when StudyEventRepeatKey attribute is null
OC-10879 Ability to import data in a calculate item via XML import API
> OC 10884 XML file with non-ODM schema

- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
https://jira.openclinica.com/browse/OC-10556
> OC-10556 View Events - Edit option should not be displayed for Monitors

- web/src/main/webapp/WEB-INF/jsp/managestudy/jobs.jsp
https://jira.openclinica.com/browse/OC-10828
> OC-10828 Provide an ability to view the log file content in data table format	

- web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
https://jira.openclinica.com/browse/OC-9270
> OC-9270 Detailed note for an event level query does not get updated

- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp
https://jira.openclinica.com/browse/OC-10762
> OC-10762 Participant Details Page should not fail to load if there is a problem with part of the Participant's ClinicalData/Metadata

- core/src/main/java/org/akaza/openclinica/dao/managestudy/StudySubjectDAO.java
- core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- core/src/main/resources/properties/cd_odm_mapping.xml
- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
- web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
- web/src/main/java/org/akaza/openclinica/controller/EditFormController.java
- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/JobController.java
- web/src/main/java/org/akaza/openclinica/controller/OdmController.java
- web/src/main/java/org/akaza/openclinica/controller/dto/StudyEventScheduleRequestDTO.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ParticipateServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ValidateService.java
- web/src/main/java/org/akaza/openclinica/service/ValidateServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
- web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
Move participant ID as part of the JSON body in the create study event endpoint
> OC 10861 Move participant ID as part of the JSON body in the create study event endpoint

- web/src/main/java/org/akaza/openclinica/controller/JobController.java
Job Log File name brakes if Study Name contains UTF-8
> OC-10887 Job Log File name brakes if Study Name contains UTF-8

- web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
View Query Only mode throwing Oops Error page
> OC-10901 View Query Only mode throwing Oops Error page

- web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectsServlet.java
- web/src/main/webapp/WEB-INF/jsp/managestudy/findSubjects.jsp
- web/src/main/webapp/includes/styles.css
- web/src/main/webapp/js/lib/bootstrap-tour.js
https://jira.openclinica.com/browse/OC-10896
> OC-10896 Run reconcilation report check box should be available ONLY under DDE sites

- core/src/main/java/org/akaza/openclinica/bean/submit/crfdata/StudyEventDataBean.java
- core/src/main/java/org/akaza/openclinica/domain/enumsupport/EndpointType.java
- core/src/main/java/org/akaza/openclinica/service/crfdata/ErrorObj.java
- core/src/main/resources/properties/cd_odm_mapping.xml
- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/JobController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/controller/dto/StudyEventResponseDTO.java
- web/src/main/java/org/akaza/openclinica/controller/dto/StudyEventUpdateRequestDTO.java
- web/src/main/java/org/akaza/openclinica/controller/helper/table/ItemCountInForm.java
- web/src/main/java/org/akaza/openclinica/service/ImportService.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/StudyEventService.java
- web/src/main/java/org/akaza/openclinica/service/StudyEventServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
> OC-10927 XML import code refactoring

- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/controller/dto/StudyEventUpdateRequestDTO.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
Error updating status for repeating Visit-Based Events
> OC - 10940 Error updating status for repeating Visit-Based Events

- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
If itemgroup OID is missing, no data is being added to the common event, but the common event is getting status completed
> OC 10932 If itemgroup OID is missing, no data is being added to the common event, but the common event is getting status completed

- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
Non repeating visit based event is getting completed during Import through REST API, when start date is missing
> OC-10942 Non repeating visit based event is getting completed during Import through REST API, when start date is missing

- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/service/CSVServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ParticipantService.java
- web/src/main/java/org/akaza/openclinica/service/ParticipantServiceImpl.java
OC-10929 Bulk add API returning noSufficientPrivileges error for a study level role when they are authorized users
- Fixed a bug where inivalid header will be skipped: OC-10426 Ability to register bulk list of participants for participate with or without capturing their PII
> OC-10928 Bulk add API returning noRole setup message when user has access to the given site

- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/service/ImportService.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/StudyEventServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
Incorrect error code when repeatKey is missing in the update study event endpoint
> OC-10947 Incorrect error code when repeatKey is missing in the update study event endpoint

- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
New study events are getting created when study or site is not available
> OC-10944 New study events are getting created when study or site is not available 

- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
Study OID and Site OID path parameters in study event REST endpoints should be case insensitive
> OC 10951 Study OID and Site OID path parameters in study event REST endpoints should be case insensitive

- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
For a removed participant, study event creation is permitted via the REST endpoint
> OC-10945 For a removed participant, study event creation is permitted via the REST endpoint

- core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
Participate form breaks with special characters in inputs
> OC-10953 Participate form breaks with special characters in inputs

- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/StudyEventServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
Status of event is getting completed when user asked the form status as initial data entry with Rest Import
> OC - 10935 Status of event is getting completed when user asked the form status as initial data entry with Rest Import

- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/service/StudyEventServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
Change the errorCode for the scenarios where repeatKey is not found for the given participant when study event update API is called
> OC-10950 Change the errorCode for the scenarios where repeatKey is not found for the given participant when study event update API is called

- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/service/StudyEventServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
Add support to validate study / site status in XML import endpoint
> OC - 10880 Add support to validate study / site status in XML import endpoint

- web/src/main/java/org/akaza/openclinica/control/login/ChangeStudyServlet.java
- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
https://jira.openclinica.com/browse/OC-10770
> OC-10770 Participate/Contact show/hide in Detail page and Advanced Search link get Role confused when Study jump(feedback)

- core/src/main/java/org/akaza/openclinica/bean/submit/crfdata/StudyEventDataBean.java
- core/src/main/java/org/akaza/openclinica/bean/submit/crfdata/SubjectDataBean.java
- core/src/main/java/org/akaza/openclinica/domain/enumsupport/JobType.java
- core/src/main/resources/properties/cd_odm_mapping.xml
- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/controller/UserController.java
- web/src/main/java/org/akaza/openclinica/controller/dto/DataImportReport.java
- web/src/main/java/org/akaza/openclinica/controller/helper/table/ItemCountInForm.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
- web/src/main/java/org/akaza/openclinica/service/ImportService.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/StudyEventServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ValidateService.java
- web/src/main/java/org/akaza/openclinica/service/ValidateServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
REST endpoint to Import clinical data using XML file
> OC-10767 REST endpoint to Import clinical data using XML file

- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
when formOID of visit based event is invalid or use case insensitive form id in common event, import job never completes
> OC-10968 when formOID of visit based event is invalid or use case insensitive form id in common event, import job never completes

- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
https://jira.openclinica.com/browse/OC-10860
> OC-10860 Invite modal window tab key behavior update

- core/src/main/java/org/akaza/openclinica/domain/rule/action/NotificationActionProcessor.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/service/ParticipantServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
Add participant endpoint makes the participant from removed to available in the study
> OC-10819 Add participant endpoint makes the participant from removed to available in the study

- core/src/main/java/org/akaza/openclinica/domain/rule/action/NotificationActionProcessor.java
Expose participant ID, study ID, site ID, and site name variables for the Notification Action rules
> OC-9687 Expose participant ID, study ID, site ID, and site name variables for the Notification Action rules

- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
Overwriting a non repeating common event form with different version creates a new event.
(cherry picked from commit 5cfd1be838e67f7292ccb0931e54b90a03ca86e8)
> OC-10975 Overwriting a non repeating common event form with different version creates a new event.

- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
Overwriting a non repeating common event form with different version creates a new event.
> OC-10975 Overwriting a non repeating common event form with different version creates a new event. 

- web/src/main/java/org/akaza/openclinica/control/managestudy/JobsServlet.java
- web/src/main/java/org/akaza/openclinica/controller/JobController.java
- web/src/main/java/org/akaza/openclinica/service/JobServiceImpl.java
- web/src/main/java/org/akaza/openclinica/view/Page.java
- web/src/main/java/org/akaza/openclinica/web/util/ErrorConstants.java
- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
- web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
- web/src/main/webapp/WEB-INF/jsp/managestudy/jobs.jsp
- web/src/main/webapp/WEB-INF/web.xml
> OC-4.7.3 Committing Job UI files

- web/src/main/java/org/akaza/openclinica/control/login/ChangeStudyServlet.java
https://jira.openclinica.com/browse/OC-10800
> OC-10800 Invite modal window is not present when the user first logs in

- core/src/main/resources/migration/tenant/4.0-2019-06-13-OC-10998.xml
Send multiple queries per item to Enketo
> OC-10988 Multiple Queries

- core/src/main/java/org/akaza/openclinica/bean/managestudy/DiscrepancyNoteBean.java
- core/src/main/java/org/akaza/openclinica/dao/managestudy/DiscrepancyNoteDAO.java
- core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- core/src/main/java/org/akaza/openclinica/service/crfdata/xform/PFormCacheSubjectContextEntry.java
- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
- web/src/main/java/org/akaza/openclinica/control/submit/CreateDiscrepancyNoteServlet.java
- web/src/main/java/org/akaza/openclinica/control/submit/CreateOneDiscrepancyNoteServlet.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/QueryServiceHelperBean.java
- web/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
OC-11021 Autoqueries for Closed-Modified not being added as expected
OC-11022 Autoquery when Closing form with an active error not being added as expected
> OC 11021 Autoqueries for Closed-Modified not being added as expected

- core/src/main/java/org/akaza/openclinica/bean/managestudy/DiscrepancyNoteBean.java
- core/src/main/java/org/akaza/openclinica/dao/managestudy/DiscrepancyNoteDAO.java
- core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- core/src/main/java/org/akaza/openclinica/service/crfdata/xform/PFormCacheSubjectContextEntry.java
- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
- web/src/main/java/org/akaza/openclinica/control/submit/CreateDiscrepancyNoteServlet.java
- web/src/main/java/org/akaza/openclinica/control/submit/CreateOneDiscrepancyNoteServlet.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/QueryServiceHelperBean.java
- web/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
OC-11013 View Query Within Record opens to specific Query thread
OC-11019 Add Query Name to Query Notification email
> OC-11013 View Query Within Record opens to specific Query thread

- core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- core/src/main/java/org/akaza/openclinica/bean/odmbeans/DiscrepancyNoteBean.java
- core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
- core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
- web/src/main/java/org/akaza/openclinica/controller/UserController.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/UserService.java
- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
> OC-11012 Add Query ID to ODM

- web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
After update, Queries Table displays incorrect date created.
> OC-10617 After update, Queries Table displays incorrect date created.

- web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
Large repeat key like 3 was used in repeating group are not getting ignored during REST Import
> OC-10984  Large repeat key like 3 was used in repeating group are not getting ignored during REST Import

- web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
When study event with repeatKey 1 is sent once but contains more than one form data sections then ONLY first section should get processed
> OC-10980 When study event with repeatKey 1 is sent once but contains more than one form data sections then ONLY first section should get processed

- core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
Assigned to value in Query is showing the wrong assignee
> OC- 11050 Assigned to value in Query is showing the wrong assignee

- core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- web/src/main/java/org/akaza/openclinica/controller/UserController.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/UserService.java
- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
When user is invited via mobile or email then 'participant access code viewed' audit entry is also getting created
> OC-10905 When user is invited via mobile or email then 'participant access code viewed' audit entry is also getting created

- core/src/main/java/org/akaza/openclinica/service/managestudy/StudySubjectServiceImpl.java
https://jira.openclinica.com/browse/OC-11019
> OC-11019 Form status does not update to complete when a form contains ONLY the participant contact info

- web/src/main/webapp/js/lib/bootstrap-tour.js
https://jira.openclinica.com/browse/OC-11041
> OC-11041 Word change on the participant ID verification modal window

- pom.xml
- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
https://jira.openclinica.com/browse/OC-10337
> OC-10337 Participant access code need to reset

- web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
https://jira.openclinica.com/browse/OC-11006
> OC-11006 Add Annotations to Query Manager table

- core/src/main/java/org/akaza/openclinica/dao/managestudy/DiscrepancyNoteDAO.java
https://jira.openclinica.com/browse/OC-11035
This bug found when I working on OC-10617
> OC-11035 Update query error

- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
https://jira.openclinica.com/browse/OC-10979
> OC-10979 Remove Japan from the country list on the Invite modal window

- core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
Oops error on opening a form with Query
> OC-11059 Oops error on opening a form with Query

- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
https://jira.openclinica.com/browse/OC-11057
> OC-11057 Invitation email format update

- web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
https://jira.openclinica.com/browse/OC-11062
> OC-11062 Time being displayed in "Date Started" field in Visits section of Participant Detail Page

- core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- web/src/main/java/org/akaza/openclinica/control/submit/CreateDiscrepancyNoteServlet.java
- web/src/main/java/org/akaza/openclinica/control/submit/CreateOneDiscrepancyNoteServlet.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
Update Query ID display to be all numeric with no padding or prefix
> OC-11072 Update Query ID display to be all numeric with no padding or prefix

- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
User can import through REST API to a form version that is not available to a site
> OC-10993 User can import through REST API to a form version that is not available to a site

- web/src/main/webapp/WEB-INF/jsp/managestudy/jobs.jsp
https://jira.openclinica.com/browse/OC-10734
> OC-10734 Page description on the jobs page(feedback)

- web/src/main/webapp/WEB-INF/jsp/managestudy/jobs.jsp
https://jira.openclinica.com/browse/OC-10915
> OC-10915 While viewing jobs at site level, the top right hand side is appearing chopped

- web/src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- web/src/main/java/org/akaza/openclinica/control/submit/ListDiscNotesForCRFTableFactory.java
- web/src/main/java/org/akaza/openclinica/control/submit/ListDiscNotesSubjectTableFactory.java
- web/src/main/webapp/WEB-INF/jsp/submit/eventCrfLayer.jsp
- web/src/main/webapp/WEB-INF/jsp/submit/eventLayer.jsp
https://jira.openclinica.com/browse/OC-10480
> OC-10480 Apostrophe in Participant ID prevents from scheduling an Event

- web/src/main/webapp/WEB-INF/jsp/managestudy/jobs.jsp
https://jira.openclinica.com/browse/OC-10811?focusedCommentId=181464&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-181464
> OC-10811 jobUI page sorting and column name relabeling

- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
https://jira.openclinica.com/browse/OC-11057
> OC-11057 Invitation email format update (feedback)

- web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
- web/src/main/java/org/akaza/openclinica/service/AuditLogEventService.java
- web/src/main/java/org/akaza/openclinica/service/AuditLogEventServiceImpl.java
https://jira.openclinica.com/browse/OC-10834
> OC-10834 OC4 - Signature not recorded when signing an event if the event status is already Signed

- core/src/main/java/org/akaza/openclinica/bean/extract/DownloadDiscrepancyNote.java
- core/src/main/java/org/akaza/openclinica/dao/managestudy/ViewNotesDaoImpl.java
- core/src/main/java/org/akaza/openclinica/service/managestudy/ViewNotesFilterCriteria.java
- core/src/main/java/org/akaza/openclinica/service/managestudy/ViewNotesSortCriteria.java
- core/src/main/resources/migration/tenant/4.0-2019-06-28-OC-11007.xml
- core/src/main/resources/migration/tenant/release.xml
- core/src/main/resources/queries/postgres/viewnotes.properties
- web/src/main/java/org/akaza/openclinica/control/extract/DiscrepancyNoteOutputServlet.java
- web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
- web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableToolbar.java
- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
- web/src/main/webapp/WEB-INF/jsp/managestudy/viewNotesPrint.jsp
- web/src/main/webapp/WEB-INF/jsp/submit/chooseDownloadFormat.jsp
https://jira.openclinica.com/browse/OC-11007
> OC-11007 Add Query ID column to Query Manager table

- web/src/main/java/org/akaza/openclinica/config/SwaggerConfig.java
- web/src/main/java/org/akaza/openclinica/controller/ContactsModuleController.java
- web/src/main/java/org/akaza/openclinica/controller/JobController.java
- web/src/main/java/org/akaza/openclinica/controller/ODMClinicalDataController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/controller/SystemController.java
- web/src/main/java/org/akaza/openclinica/controller/UserController.java
https://jira.openclinica.com/browse/OC-9519
> OC-9519 Swagger UI cleanup

- web/src/main/webapp/js/lib/bootstrap-tour.js
https://jira.openclinica.com/browse/OC-11081
> OC-11081 Wording change on the verify participant ID page

- web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
This reverts commit 14bf66d01b5e5f48c1d27d433351602fddeba9e5.
> Revert "OC-11062 Time being displayed in "Date Started" field in Visits section of Participant Detail Page"

- web/src/main/webapp/js/lib/bootstrap-tour.js
https://jira.openclinica.com/browse/OC-11081
> OC-11081 Wording change on the verify participant ID page(feedback)

- web/src/main/java/org/akaza/openclinica/controller/ContactsModuleController.java
- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/JobController.java
- web/src/main/java/org/akaza/openclinica/controller/ODMClinicalDataController.java
https://jira.openclinica.com/browse/OC-11093
> OC 11093 Swagger - Rename import section as clinical data and move get Clinical data API under this section

- web/src/main/java/org/akaza/openclinica/controller/ContactsModuleController.java
- web/src/main/java/org/akaza/openclinica/controller/JobController.java
https://jira.openclinica.com/browse/OC-9519
> OC-9519 Swagger UI cleanup(feedback)

- web/src/main/java/org/akaza/openclinica/controller/ContactsModuleController.java
- web/src/main/java/org/akaza/openclinica/controller/JobController.java
- web/src/main/java/org/akaza/openclinica/controller/ODMClinicalDataController.java
https://jira.openclinica.com/browse/OC-11092
> OC 11092 Swagger documentation update for get clinical data endpoint

- core/src/main/java/org/akaza/openclinica/dao/hibernate/StudyEventDao.java
- core/src/main/java/org/akaza/openclinica/dao/hibernate/StudySubjectDao.java
- core/src/main/java/org/akaza/openclinica/dao/managestudy/DiscrepancyNoteDAO.java
- core/src/main/java/org/akaza/openclinica/domain/enumsupport/EndpointType.java
- core/src/main/java/org/akaza/openclinica/domain/rule/action/NotificationActionProcessor.java
- core/src/main/java/org/akaza/openclinica/service/EventService.java
- core/src/main/resources/properties/discrepancy_note_dao.xml
- web/src/main/java/org/akaza/openclinica/control/admin/DeleteEventCRFServlet.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/RemoveEventCRFServlet.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/RemoveStudyEventServlet.java
- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/controller/UserController.java
- web/src/main/java/org/akaza/openclinica/controller/dto/DataImportReport.java
- web/src/main/java/org/akaza/openclinica/controller/dto/StudyEventScheduleDTO.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/CSVService.java
- web/src/main/java/org/akaza/openclinica/service/CSVServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ImportService.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/StudyEventService.java
- web/src/main/java/org/akaza/openclinica/service/StudyEventServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
Deleting Event CRF not closing all queries threads
> OC-11076 Deleting Event CRF not closing all queries threads

- core/src/main/java/org/akaza/openclinica/dao/hibernate/StudyEventDao.java
- core/src/main/java/org/akaza/openclinica/dao/hibernate/StudySubjectDao.java
- core/src/main/java/org/akaza/openclinica/domain/enumsupport/EndpointType.java
- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/controller/dto/DataImportReport.java
- web/src/main/java/org/akaza/openclinica/controller/dto/StudyEventScheduleDTO.java
- web/src/main/java/org/akaza/openclinica/service/CSVService.java
- web/src/main/java/org/akaza/openclinica/service/CSVServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ImportService.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/StudyEventService.java
- web/src/main/java/org/akaza/openclinica/service/StudyEventServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
Ability to batch create given study events for a given list of participants
> OC-10917 Ability to batch create given study events for a given list of participants

- core/src/main/java/org/akaza/openclinica/dao/hibernate/StudyEventDao.java
- core/src/main/java/org/akaza/openclinica/dao/hibernate/StudySubjectDao.java
- core/src/main/java/org/akaza/openclinica/domain/enumsupport/EndpointType.java
- core/src/main/java/org/akaza/openclinica/domain/rule/action/NotificationActionProcessor.java
- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
- web/src/main/java/org/akaza/openclinica/controller/dto/DataImportReport.java
- web/src/main/java/org/akaza/openclinica/controller/dto/StudyEventScheduleDTO.java
- web/src/main/java/org/akaza/openclinica/service/CSVService.java
- web/src/main/java/org/akaza/openclinica/service/CSVServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/ImportService.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/StudyEventService.java
- web/src/main/java/org/akaza/openclinica/service/StudyEventServiceImpl.java
- web/src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
Rules does not seem to be triggering in dev
> OC-11082 Rules does not seem to be triggering in dev 

- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/controller/UserController.java
https://jira.openclinica.com/browse/OC-11097
> OC-11097 Swagger documentation update for all participant endpoints

- web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
https://jira.openclinica.com/browse/OC-11098
> OC-11098 Query Manager Query Status not filtering as expected

- web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
- OC-10717 Update the Invite/Edit Participant Window to use consistent logic for email and phone number as data collected on a form
(Paul/Jigyasa's feedback): https://jira.openclinica.com/browse/OC-10717?focusedCommentId=182491&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-182491
- OC-11090 Invite Modal Window Mobile field does not work with TAB
https://jira.openclinica.com/browse/OC-11090
- OC-11091 Invite Modal Window Mobile field validator should not invalidate empty field
https://jira.openclinica.com/browse/OC-11091
> OC-10717, OC-11090, and OC-11091; all related -- three sides of the same co... uh, cylinder

- web/src/main/webapp/WEB-INF/jsp/managestudy/jobs.jsp
https://jira.openclinica.com/browse/OC-10999
> OC-10999 View Job Log page needs to have a link to go back to Job page

- web/src/main/webapp/WEB-INF/jsp/managestudy/jobs.jsp
https://jira.openclinica.com/browse/OC-10915
> OC-10915 While viewing jobs at site level, the top right hand side is appearing chopped(feedback)

- core/src/main/java/org/akaza/openclinica/service/EventService.java
- web/src/main/java/org/akaza/openclinica/control/admin/DeleteEventCRFServlet.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/RemoveEventCRFServlet.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/RemoveStudyEventServlet.java
- web/src/main/java/org/akaza/openclinica/service/ParticipantServiceImpl.java
Queries auto-closed from outside the form should have status Closed-Modified
> OC-9549 Queries auto-closed from outside the form should have status Closed-Modified

- web/src/main/java/org/akaza/openclinica/service/ParticipantServiceImpl.java
System should not add or update participant when given study or site is not available
> OC-11063 System should not add or update participant when given study or site is not available

- web/src/main/java/org/akaza/openclinica/controller/OdmController.java
https://jira.openclinica.com/browse/OC-10019
> OC-10019 Add participant's first name on the participate UI(feedback: set contentType)

- core/src/main/resources/properties/rules_template.xml
- web/src/main/java/org/akaza/openclinica/control/submit/ViewRuleAssignmentNewServlet.java
- web/src/main/java/org/akaza/openclinica/control/submit/ViewRuleAssignmentTableToolbar.java
- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
https://jira.openclinica.com/browse/OC-11124
> OC-11124 Rules page update

- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- web/src/main/java/org/akaza/openclinica/service/UtilService.java
- web/src/main/java/org/akaza/openclinica/service/UtilServiceImpl.java
XML Import breaking with jobs in perpetual IN_PROGRESS status
> OC - 11119 XML Import breaking with jobs in perpetual IN_PROGRESS status

- core/src/main/java/org/akaza/openclinica/validator/ParticipantValidator.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
- web/src/main/java/org/akaza/openclinica/service/UtilServiceImpl.java
Email and phone number validations in add participant and Bulk add participant endpoints to be updated
> OC -11002 Email and phone number validations in add participant and Bulk add participant endpoints to be updated

- web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
Support on-form Participant phone number entry in US or international format
> OC-10958     Support on-form Participant phone number entry in US or international format

- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
https://jira.openclinica.com/browse/OC-11103
> OC-11103 User is unable to update the participant contact information

- web/src/main/java/org/akaza/openclinica/controller/UserController.java
Fix the spelling issue in the extractParticipantInfo endpoint
> OC-11164 Fix the spelling issue in the extractParticipantInfo endpoint

- core/src/main/java/org/akaza/openclinica/validator/ParticipantValidator.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/service/UtilServiceImpl.java
REST API call for adding participant is not returning an error message when Bad site OID is used
> OC-11168 REST API call for adding participant is not returning an error message when Bad site OID is used

- web/src/main/webapp/WEB-INF/jsp/submit/import.jsp
https://jira.openclinica.com/browse/OC-11156
> OC-11156 Hide the bulk job log link from the Import data page

- web/src/main/java/org/akaza/openclinica/controller/DataController.java
- web/src/main/webapp/includes/prototype.js
https://jira.openclinica.com/browse/OC-11133
> OC-11133 Swagger documentation update for Import section and APIs

- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/service/ParticipantServiceImpl.java
User is able to register participant through REST API when participate module is inactive
> OC-11099 User is able to register participant through REST API when participate module is inactive

- web/src/main/java/org/akaza/openclinica/service/ParticipateServiceImpl.java
date_completed field in event_crf table does not populate when an event is marked completed via Participate
> OC-11163 date_completed field in event_crf table does not populate when an event is marked completed via Participate

- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
Hide bulk add participant API from swagger UI
> OC - 11187 Hide bulk add participant API from swagger UI

- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
date_completed field in event_crf table does not populate when a form is marked completed via New XML Import
> OC-11184 date_completed field in event_crf table does not populate when a form is marked completed via New XML Import

- core/src/main/java/org/akaza/openclinica/bean/core/ApplicationConstants.java
- core/src/main/java/org/akaza/openclinica/service/UserType.java
- core/src/main/java/org/akaza/openclinica/web/filter/ApiSecurityFilter.java
- web/src/main/java/org/akaza/openclinica/controller/ImportController.java
- web/src/main/java/org/akaza/openclinica/web/rest/client/auth/impl/KeycloakClientImpl.java
WIP, need to add logic to see if the randomize user already exists.
> Logic for importing data as a system user

- web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
Typo in swagger for bulk study event API
> OC-11193 Typo in swagger for bulk study event API

- core/src/main/java/org/akaza/openclinica/bean/extract/ArchivedDatasetFileBean.java
- core/src/main/java/org/akaza/openclinica/bean/extract/ExtractPropertyBean.java
- core/src/main/java/org/akaza/openclinica/dao/core/CoreResources.java
- core/src/main/java/org/akaza/openclinica/dao/extract/ArchivedDatasetFileDAO.java
- core/src/main/java/org/akaza/openclinica/domain/enumsupport/JobStatus.java
- core/src/main/java/org/akaza/openclinica/job/QuartzConfiguration.java
- core/src/main/java/org/akaza/openclinica/job/XsltStatefulJob.java
- core/src/main/java/org/akaza/openclinica/job/XsltTransformJob.java
- core/src/main/java/org/akaza/openclinica/service/extract/XsltTriggerService.java
- core/src/main/resources/migration/tenant/4.0-2019-07-24-OC-11067.xml
- core/src/main/resources/migration/tenant/release.xml
- core/src/main/resources/properties/archived_dataset_file_dao.xml
- web/src/main/java/org/akaza/openclinica/control/admin/CreateJobExportServlet.java
- web/src/main/java/org/akaza/openclinica/control/admin/UpdateJobExportServlet.java
- web/src/main/java/org/akaza/openclinica/control/extract/ExportDatasetServlet.java
- web/src/main/java/org/akaza/openclinica/control/extract/ShowFileServlet.java
- web/src/main/java/org/akaza/openclinica/controller/ExtractController.java
- web/src/main/resources/extract.properties
- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
- web/src/main/webapp/WEB-INF/jsp/extract/showArchivedDatasetFileRow.jsp
Provide an ability to see the extract jobs that are currently in progress
> OC-11067 Provide an ability to see the extract jobs that are currently in progress

- web/src/main/webapp/WEB-INF/jsp/managestudy/jobs.jsp
https://jira.openclinica.com/browse/OC-10985
> OpenClinicaOC-10985 UI issues with the 'view log file content' page

- core/src/main/java/org/akaza/openclinica/bean/extract/DownloadDiscrepancyNote.java
https://jira.openclinica.com/browse/OC-9724
> OC-9724 OC4- "event date" not exported/printed for discrepancies

- web/src/main/java/org/akaza/openclinica/controller/SDVController.java
- web/src/main/java/org/akaza/openclinica/web/table/sdv/SDVUtil.java
- web/src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
https://jira.openclinica.com/browse/OC-8969
https://jira.openclinica.com/browse/OC-9337
https://jira.openclinica.com/browse/OC-11108
> OC-8969/9337/11108 (SDV-related bugfixes)

- web/src/main/webapp/includes/sessionTimeout.js
https://jira.openclinica.com/browse/OC-11287
> OC-11287 IE11 unable to open any pull down menu

- core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
- web/src/main/java/org/akaza/openclinica/control/extract/ExportDatasetServlet.java
Improve performance for extract with large data
> OC-10302 Improve performance for extract with large data

- core/src/main/java/org/akaza/openclinica/bean/managestudy/StudyEventBean.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectServlet.java
- web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
Support custom item value display for Visit-Based events in Participant Matrix
> OC-11318 Support custom item value display for Visit-Based events in Participant Matrix

- web/src/main/java/org/akaza/openclinica/control/managestudy/RemoveStudySubjectServlet.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/RestoreStudySubjectServlet.java
https://jira.openclinica.com/browse/OC-10792
> OC-10792 Alert message for Remove/Restore Participent needs improvement

- core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
Audit detail for Repeating Events is not correct in XML extract
> OC-11109 Audit detail for Repeating Events is not correct in XML extract

- core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
OC4 StudyEventRepeatKey Attribute for Non-Repeating Events
> OC-10936 OC4 StudyEventRepeatKey Attribute for Non-Repeating Events

- web/src/main/java/org/akaza/openclinica/service/StudyParticipantServiceImpl.java
https://jira.openclinica.com/browse/OC-11095
> OC-11095 Adding Contact information Through Rest API on a signed participant is failing (feedback)

- web/src/main/java/org/akaza/openclinica/web/table/sdv/SDVUtil.java
https://jira.openclinica.com/browse/OC-11313
> OC-11313 SDV with checkbox returns blank screen

- web/src/main/java/org/akaza/openclinica/config/AppConfig.java
> OC-11290 Randomize configuration is loaded on Runtime startup

- web/src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
https://jira.openclinica.com/browse/OC-11378
> OC-11378 fix: Error 400 upon unchecking SDV a Participant

- core/src/main/java/org/akaza/openclinica/bean/extract/odm/MetaDataReportBean.java
Notification Action breaks Participate Detail page if message contains &lt; and/or &amp;
> OC-11304 Notification Action breaks Participate Detail page if message contains &lt; and/or &amp;

- web/src/main/java/org/akaza/openclinica/control/AbstractTableFactory.java
- web/src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableToolbar.java
- web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
- web/src/main/java/org/akaza/openclinica/web/table/sdv/SDVUtil.java
https://jira.openclinica.com/browse/OC-11213
> OC-11213 Participant Matrix is persistent to 50 view

- core/src/main/java/org/akaza/openclinica/dao/hibernate/StudyEventDao.java
- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
Import no long firing rules when Event status is set to data entry started
> OC-11430 Import no long firing rules when Event status is set to data entry started

- web/src/main/resources/datainfo.properties
Cleaning up properties and setting default dev fields
> Updates to datainfo.properties file

- web/src/main/webapp/WEB-INF/jsp/managestudy/viewNotesPrint.jsp
https://jira.openclinica.com/browse/OC-9633
> OC-9633 Using the Print option for Queries table is missing a column

- web/src/main/webapp/WEB-INF/jsp/managestudy/viewSite.jsp
https://jira.openclinica.com/browse/OC-11478
> OC-11478 View Site Details page UI issues

- web/src/main/webapp/WEB-INF/jsp/extract/showDatasetRow.jsp
- web/src/main/webapp/WEB-INF/jsp/include/showTable.jsp
https://jira.openclinica.com/browse/OC-11457
> OC-11457 fix: Removed datasets no longer have "Removed" icon

- core/src/main/java/org/akaza/openclinica/dao/managestudy/FindSubjectsFilter.java
- core/src/main/java/org/akaza/openclinica/dao/managestudy/StudySubjectDAO.java
- core/src/main/java/org/akaza/openclinica/service/OdmImportService.java
- core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java
- core/src/main/java/org/akaza/openclinica/service/PermissionService.java
- core/src/main/java/org/akaza/openclinica/service/PermissionServiceImpl.java
- core/src/main/java/org/akaza/openclinica/service/PublishDTO.java
- core/src/main/resources/properties/study_subject_dao.xml
- web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
- web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableToolbar.java
- web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectsServlet.java
- web/src/main/java/org/akaza/openclinica/controller/OdmImportController.java
- web/src/main/java/org/akaza/openclinica/controller/ViewStudySubjectController.java
- web/src/main/java/org/akaza/openclinica/service/ViewStudySubjectService.java
- web/src/main/java/org/akaza/openclinica/service/ViewStudySubjectServiceImpl.java
OC-11369 Display custom columns in Participant Matrix
> OC-11369 Display custom columns in Participant Matrix

- web/src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableToolbar.java
https://jira.openclinica.com/browse/OC-11201
> OC-11201 Matrix shows only 15 Participates where as it says 50

- core/src/main/java/org/akaza/openclinica/dao/core/CoreResources.java
- core/src/main/resources/org/akaza/openclinica/applicationContext-core-spring.xml
OC-11459: Changed the bean properties from xml to Environment Object
> Place holder

- core/src/main/java/org/akaza/openclinica/bean/login/ResponseSuccessListAllParticipantsByStudyDTO.java
- web/src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
https://jira.openclinica.com/browse/OC-11414
> OC-11414 Get Participants endpoint is showing internal site ID

- web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
- web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
Custom columns in Queries Table should have dropdowns to filter select items
> OC-11557     Custom columns in Queries Table should have dropdowns to filter select items

- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
- web/src/main/webapp/WEB-INF/jsp/managestudy/jobs.jsp
https://jira.openclinica.com/browse/OC-11332
> OC-11332 Bulk Action Log Enhancement View's

- web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
Custom columns in Participant Matrix should have dropdowns to filter select items
> OC-11491 Custom columns in Participant Matrix should have dropdowns to filter select items

- core/src/main/java/org/akaza/openclinica/bean/extract/odm/MetaDataReportBean.java
- core/src/main/java/org/akaza/openclinica/bean/odmbeans/ItemDefBean.java
- core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
- core/src/main/java/org/akaza/openclinica/domain/datamap/Item.java
- core/src/main/java/org/akaza/openclinica/domain/xform/XformItem.java
- core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java
- core/src/main/resources/migration/tenant/4.0-2019-10-15-OC-8893.xml
- core/src/main/resources/migration/tenant/release.xml
- web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
- web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
Upload forms with Item Short Descriptions
> OC-8893 Upload forms with Item Short Descriptions

- core/src/main/java/org/akaza/openclinica/dao/core/CoreResources.java
- pom.xml
- web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
- web/src/main/resources/datainfo.properties
- web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
https://jira.openclinica.com/browse/OC-11576
> OC-11576 Remove WalkMe from RT

- web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
- web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/EventProcessor.java
Opening form after version migration is causing duplicate entries for the form to be created in the database
> OC-11566 Opening form after version migration is causing duplicate entries for the form to be created in the database

- web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
- web/src/main/webapp/WEB-INF/jsp/managestudy/findSubjects.jsp
https://jira.openclinica.com/browse/OC-11616
> fix OC-11616 Participant Matrix is displaying HTML code on any click

- web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
Can't "View" forms with no data saved in runtime
> OC-11631 Can't "View" forms with no data saved in runtime

- web/src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
Reason for change added when data is imported into completed form is not appearing in Queries table consistently
> OC-11626  Reason for change added when data is imported into completed form is not appearing in Queries table consistently

- src/main/resources/org/akaza/openclinica/i18n/words.properties
- src/main/webapp/WEB-INF/jsp/managestudy/studySubject/casebookGenerationForm.jsp
https://jira.openclinica.com/browse/OC-11519
> OC-11519 Add PDF Casebook UI functionality

- src/main/webapp/WEB-INF/jsp/managestudy/reassignStudySubjectConfirm.jsp
https://jira.openclinica.com/browse/OC-9471
> OC-9471 Reassign participant confirmation page message

- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
https://jira.openclinica.com/browse/OC-11512
> OC-11512 Issue w/ Schedule Button on Participant Matrix

- src/main/java/org/akaza/openclinica/control/submit/CreateDiscrepancyNoteServlet.java
- src/main/java/org/akaza/openclinica/control/submit/CreateOneDiscrepancyNoteServlet.java
- src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
https://jira.openclinica.com/browse/OC-11250
> OC-11250 Query Notification email link is not filtering by Query ID

- src/main/webapp/WEB-INF/jsp/managestudy/studySubject/casebookGenerationForm.jsp
https://jira.openclinica.com/browse/OC-11519
404 reported by Hiro. Fixed.
> OC-11519 Add PDF Casebook UI functionality: Fix 404

- src/main/java/core/org/akaza/openclinica/dao/managestudy/FindSubjectsFilter.java
- src/main/java/core/org/akaza/openclinica/dao/managestudy/FindSubjectsSort.java
- src/main/java/core/org/akaza/openclinica/dao/managestudy/StudySubjectDAO.java
- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
- src/main/resources/core/properties/study_subject_dao.xml
Custom columns in Participant Matrix should be sortable
> OC-11482 Custom columns in Participant Matrix should be sortable

- src/main/java/core/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
"Add New" Button Not Rendering in Participant Page
> OC-11536 "Add New" Button Not Rendering in Participant Page

- src/main/webapp/WEB-INF/jsp/include/navBar.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/findSubjects.jsp
https://jira.openclinica.com/browse/OC-11711
> OC-11711 fix: JQuery Add Pariticpant in Matrix returns error

- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
https://jira.openclinica.com/browse/OC-9482
> OC-9482 Participant Matrix does not have correct Form Event Action Links

- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableToolbar.java
- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableToolbar.java
- src/main/webapp/includes/permissionTagAccess.js
https://jira.openclinica.com/browse/OC-11716
> OC-11716 fix: Participant Matrix unsortable by Event Name

- src/main/java/core/org/akaza/openclinica/dao/QueryStore.java
- src/main/java/core/org/akaza/openclinica/dao/managestudy/ViewNotesDaoImpl.java
- src/main/java/core/org/akaza/openclinica/service/managestudy/ViewNotesSortCriteria.java
- src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
- src/main/resources/core/queries/postgres/viewnotes.properties
Custom columns in Queries table should be sortable
> OC-11556 Custom columns in Queries table should be sortable

- core/pom.xml
- pom.xml
- web/pom.xml
- web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
- web/src/main/resources/org/akaza/openclinica/i18n/words.properties
- ws/pom.xml
added exception to try/catch statement
> 4.9.1    stack 10.1 

- src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpressNew.jsp
https://jira.openclinica.com/browse/OC-11588
> OC-11588 Disable "Add" button on "Add New Participant" screen once clicked

- src/main/java/core/org/akaza/openclinica/dao/hibernate/StudySubjectDao.java
- src/main/java/org/akaza/openclinica/controller/UserController.java
- src/main/java/org/akaza/openclinica/service/UserService.java
- src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
- src/main/java/org/akaza/openclinica/web/restful/errors/ErrorConstants.java
Add paging to API to get Participant Access Codes also fix for removing participant failing issue
> OC-11745 Add paging to API to get Participant Access Codes

- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
https://jira.openclinica.com/browse/OC-11512?focusedCommentId=190995&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-190995
> Revert "OC-11512 Issue w/ Schedule Button on Participant Matrix"

- src/main/webapp/WEB-INF/jsp/include/navBar.jsp
https://jira.openclinica.com/browse/OC-11798
> OC-11798 Make Reports link available for Site users

- src/main/resources/org/akaza/openclinica/i18n/words.properties
- src/main/webapp/WEB-INF/jsp/managestudy/jobs.jsp
https://jira.openclinica.com/browse/OC-11787
> OC-11787 Bulk Action Log page needs updates for Casebook PDF

- src/main/java/core/org/akaza/openclinica/domain/datamap/PageLayout.java
- src/main/resources/migration/tenant/4.0-2019-12-04-OC-11725.xml
- src/main/resources/migration/tenant/release.xml
Update Custom Columns database table
> OC-11725 Update Custom Columns database table

- src/main/resources/org/akaza/openclinica/i18n/words.properties
- src/main/webapp/WEB-INF/jsp/include/navBar.jsp
https://jira.openclinica.com/browse/OC-11818
> OC-11818 Rename Insight Report link text

- src/main/webapp/WEB-INF/jsp/managestudy/embedded-reports.jsp
> Embedded Insight reports in Runtime: rule change for the Insight's address

- src/main/resources/org/akaza/openclinica/i18n/words.properties
- src/main/webapp/WEB-INF/jsp/include/navBar.jsp
https://jira.openclinica.com/browse/OC-11818
> OC-11818 Insight Report link text

- src/main/webapp/WEB-INF/jsp/managestudy/jobs.jsp
https://jira.openclinica.com/browse/OC-11786
> OC-11786 Bulk Actions Log page unable to preview PDF

- src/main/webapp/WEB-INF/jsp/submit/enketoFormServlet.jsp
https://jira.openclinica.com/browse/OC-10099
> OC-10099 Form activity should keep user session alive

- src/main/java/core/org/akaza/openclinica/dao/service/StudyConfigService.java
- src/main/java/core/org/akaza/openclinica/domain/datamap/Study.java
- src/main/java/org/akaza/openclinica/config/StudyParamNames.java
- src/main/java/org/akaza/openclinica/control/core/CoreSecureController.java
- src/main/java/org/akaza/openclinica/control/core/SecureController.java
- src/main/java/org/akaza/openclinica/controller/StudyController.java
- src/main/java/org/akaza/openclinica/controller/helper/SetUpStudyRole.java
Saving some of the default values in the db is removed and Some places creating redundant child StudyParameterValues is removed
> OC-11920: Saving some of the default values in the db is removed

- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
https://jira.openclinica.com/browse/OC-9676
> OC-9676 Allow change of Participant ID while auto generated is selected

- src/main/java/core/org/akaza/openclinica/dao/managestudy/DiscrepancyNoteDAO.java
- src/main/java/org/akaza/openclinica/control/managestudy/RemoveStudySubjectServlet.java
- src/main/resources/core/properties/discrepancy_note_dao.xml
- src/main/resources/core/properties/oracle_discrepancy_note_dao.xml
- src/main/resources/org/akaza/openclinica/i18n/words.properties
https://jira.openclinica.com/browse/OC-9585
> OC-9585 OC4 Auto close queries when a Participant is removed

- pom.xml
- src/main/java/core/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- src/main/java/org/akaza/openclinica/control/submit/AddNewSubjectServlet.java
- src/main/java/org/akaza/openclinica/controller/StudyController.java
- src/main/java/org/akaza/openclinica/controller/dto/ParticipantIdModel.java
- src/main/java/org/akaza/openclinica/controller/dto/ParticipantIdVariable.java
- src/main/java/org/akaza/openclinica/controller/helper/TemplateHelper.java
Support Participant IDs using random numbers
> OC-11871 Support Participant IDs using random numbers

- src/main/java/org/akaza/openclinica/controller/ChangeCRFVersionController.java
- src/main/resources/org/akaza/openclinica/i18n/words.properties
[OC-11580](https://jira.openclinica.com/browse/OC-11580)
> OC-11580 Auto-close queries when a form is migrated to a version that does not contain the item that is queried

- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableToolbar.java
- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableToolbar.java
- src/main/webapp/WEB-INF/jsp/include/navBar.jsp
jQuery errors on Participant Matrix:
- when switching between single-event and all-events view
- on the navbar (might affect other pages too)
> Fix jQuery errors

- src/main/java/org/akaza/openclinica/controller/StudyController.java
Update Participant ID Template validation
> OC-12001 Update Participant ID Template validation

- src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
https://jira.openclinica.com/browse/OC-11627
> OC-11627 Update Access Codes to not include characters that can be confused for each other

- src/main/resources/org/akaza/openclinica/i18n/words.properties
- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
https://jira.openclinica.com/browse/OC-11480
> OC-11480 Add Copy Button to Participant Access Code Page

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/FullReportBean.java
- src/main/java/core/org/akaza/openclinica/domain/xform/dto/Head.java
- src/main/java/core/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
- src/main/java/core/org/akaza/openclinica/web/pform/OpenRosaServices.java
- src/main/resources/core/properties/xformMapping.xml
Only send form data that is needed in the external form data file sent to Enketo
> OC-10066 Only send form data that is needed in the external form data file sent to Enketo

- src/main/java/core/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
Common Events are not loading.
> OC-12051 Common Events are not loading.

- src/main/java/core/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- src/main/java/core/org/akaza/openclinica/service/crfdata/xform/PFormCacheSubjectContextEntry.java
- src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
- src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
- src/main/java/org/akaza/openclinica/controller/EditFormController.java
Add logging to detect creation of duplicate form entries
> OC-11884 Add logging to detect creation of duplicate form entries

- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
https://jira.openclinica.com/browse/OC-11795
> OC-11795 Mobile devices: RT Matrix popup link does not jump

- src/main/resources/org/akaza/openclinica/i18n/words.properties
- src/main/webapp/WEB-INF/jsp/managestudy/studySubject/casebookGenerationForm.jsp
https://jira.openclinica.com/browse/OC-11965
> OC-11965 Participant Details Page Download/Casebook UI changes

- src/main/java/core/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
crossform_references not pulling in all occurrences of repeating common events
> OC-12103 crossform_references not pulling in all occurrences of repeating common events

- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
https://jira.openclinica.com/browse/OC-12098
> OC-12098 Participant Matrix- Form Action Links

- src/main/java/core/org/akaza/openclinica/service/PermissionService.java
- src/main/java/core/org/akaza/openclinica/service/PermissionServiceImpl.java
- src/main/java/org/akaza/openclinica/control/extract/DiscrepancyNoteOutputServlet.java
Query CSV Export Entity Names Incorrect
> OC-11703     Query CSV Export Entity Names Incorrect

- src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
Manual Data Import importing data and marking form complete when the item is missing 4digit random number
> OC-12032 Manual Data Import importing data and marking form complete when the item is missing 4digit random number

- src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
Manual Data Import importing data and marking form complete when the item is missing 4digit random number
(cherry picked from commit a206f71c0cc125b2c8f54520475857d21e8456e0)
> OC-12032 (#2635)

- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
https://jira.openclinica.com/browse/OC-12142
> OC-12142 Participate Invite window does not open in original state once the Access Code has been viewed for a Participant

- src/main/java/core/org/akaza/openclinica/service/PermissionService.java
- src/main/java/core/org/akaza/openclinica/service/PermissionServiceImpl.java
- src/main/java/org/akaza/openclinica/control/extract/DiscrepancyNoteOutputServlet.java
This reverts commit 8ac6182254b8eeab1c50b426f180884ef7446bc0.
> Revert "OC-11703 (#2624)"

- pom.xml
- src/main/java/core/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
- src/main/resources/org/akaza/openclinica/i18n/words.properties
API Endpoint ans Casebook calling for permission tagged data from site level not returning information
> OC-12203 API Endpoint ans Casebook calling for permission tagged data from site level not returning information

- src/main/java/core/org/akaza/openclinica/dao/managestudy/ViewNotesDaoImpl.java
- src/main/java/org/akaza/openclinica/control/extract/DiscrepancyNoteOutputServlet.java
- src/main/resources/core/queries/postgres/viewnotes.properties
Query CSV Export Entity Names Incorrect
> OC-11703 Query CSV Export Entity Names Incorrect

- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
https://jira.openclinica.com/browse/OC-12207
> OC-12207 QR Code is present twice in View Participant Access Code Dialog

- src/main/java/org/akaza/openclinica/service/PdfServiceImpl.java
Reverts OpenClinica/OpenClinica#2679
> Revert "OC-12168:Add Date and Time created in PDF Casebook footer"

- src/main/java/org/akaza/openclinica/control/core/SecureController.java
- src/main/java/org/akaza/openclinica/control/managestudy/ViewNotesServlet.java
- src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
Update Query Notification email to include study ID in the link
> OC-11033 Update Query Notification email to include study ID in the link

- src/main/java/core/org/akaza/openclinica/job/XsltTransformJob.java
- src/main/java/org/akaza/openclinica/control/core/SecureController.java
- src/main/java/org/akaza/openclinica/control/extract/AccessFileServlet.java
- src/main/java/org/akaza/openclinica/control/managestudy/ViewNotesServlet.java
- src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
Update Extract completion notification email to include study ID in the link
> OC-11634 Update Extract completion notification email to include study ID in the link

- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
Hide QR code until the eye icon is clicked
https://jira.openclinica.com/browse/OC-12207
> For OC-12207 (QR Code is present twice in View Participant Access Code Dialog) feedback

- src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
https://jira.openclinica.com/browse/OC-11970
> OC-11970 SDV Detailed View header

- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
Delete action should NOT be available to a form in locked status
> OC-10267 Delete action should NOT be available to a form in locked status

- src/main/java/core/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- src/main/java/core/org/akaza/openclinica/service/crfdata/xform/EnketoAPI.java
- src/main/java/core/org/akaza/openclinica/web/pform/PFormCache.java
- src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
Locked site makes Form review mode instead of Read-Only
> OC-12275 Locked site makes Form review mode instead of Read-Only

- src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
https://jira.openclinica.com/browse/OC-12263
> OC-12263 SDV Detailed View in shows items in Form order

- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
- src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectServlet.java
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
Delete action available to a form in locked status in two locations
> OC-12334 Delete action available to a form in locked status in two locations

- src/main/java/core/org/akaza/openclinica/logic/importdata/PipeDelimitedDataHelper.java
- src/main/java/org/akaza/openclinica/controller/DataController.java
(cherry picked from commit d3d6a578fdfc9bd317bd13bbe1a8683a27592c2b)
> OC-12354: Using the tenant schema for searching study events

- src/main/java/core/org/akaza/openclinica/domain/rule/RuleSetBean.java
- src/main/java/core/org/akaza/openclinica/domain/rule/RuleSetRuleBean.java
- src/main/java/core/org/akaza/openclinica/logic/rulerunner/BeanPropertyRuleRunner.java
- src/main/java/core/org/akaza/openclinica/service/rule/RuleSetService.java
- src/main/java/core/org/akaza/openclinica/web/pform/PFormCache.java
Additional Error Logging for Notification Action Rules
> OC-12338 Additional Error Logging for Notification Action Rules

- src/main/java/core/org/akaza/openclinica/domain/rule/RuleSetBean.java
- src/main/java/core/org/akaza/openclinica/domain/rule/RuleSetRuleBean.java
- src/main/java/core/org/akaza/openclinica/logic/rulerunner/BeanPropertyRuleRunner.java
- src/main/java/core/org/akaza/openclinica/service/rule/RuleSetService.java
- src/main/java/core/org/akaza/openclinica/web/pform/PFormCache.java
Additional Error Logging for Notification Action Rules
> Cherry picking OC-12338 into 4.10.3

- src/main/java/core/org/akaza/openclinica/domain/rule/RuleSetBean.java
- src/main/java/core/org/akaza/openclinica/domain/rule/RuleSetRuleBean.java
- src/main/java/core/org/akaza/openclinica/domain/rule/action/NotificationActionProcessor.java
- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
- src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectServlet.java
- src/main/java/org/akaza/openclinica/control/submit/EnterDataForStudyEventServlet.java
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
Additional Error Logging for Notification Action
> Oc 12338 Additional Error Logging for Notification Action 

- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
- src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectServlet.java
- src/main/java/org/akaza/openclinica/control/submit/EnterDataForStudyEventServlet.java
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
Study level user should not be able to enter data in Locked Site
> OC-12332 Study level user should not be able to enter data in Locked Site

- src/main/java/core/org/akaza/openclinica/domain/rule/RuleSetBean.java
- src/main/java/core/org/akaza/openclinica/domain/rule/RuleSetRuleBean.java
- src/main/java/core/org/akaza/openclinica/domain/rule/action/NotificationActionProcessor.java
- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
- src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectServlet.java
- src/main/java/org/akaza/openclinica/control/submit/EnterDataForStudyEventServlet.java
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
Study level user should not be able to enter data in Locked Site
> Merging OC-12332 and OC-12338 into 4.10.3

- src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
https://jira.openclinica.com/browse/OC-12251
> OC-12251  Update Left Side Panels for SDV page

- src/main/java/core/org/akaza/openclinica/dao/EventCRFSDVFilter.java
- src/main/java/core/org/akaza/openclinica/web/table/sdv/SDVUtil.java
OC-12252 Separate SDV columns for Form Name and Form Version
https://jira.openclinica.com/browse/OC-12252
> OC-12252 Separate SDV columns for Form Name and Form Version (AC1)

- src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
https://jira.openclinica.com/browse/OC-12272
> OC-12272 Update SDV table filters to not push columns to be too wide

- src/main/java/core/org/akaza/openclinica/job/XsltTransformJob.java
- src/main/java/org/akaza/openclinica/control/core/SecureController.java
- src/main/java/org/akaza/openclinica/control/extract/AccessFileServlet.java
- src/main/java/org/akaza/openclinica/control/managestudy/ViewNotesServlet.java
- src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
reverting changes to 11634 and 11033
> 4.10.3 reverting changes to 11634 and 11033

- src/main/java/core/org/akaza/openclinica/service/PermissionServiceImpl.java
- src/main/java/org/akaza/openclinica/control/extract/AccessFileServlet.java
OC-12480 site monitor can not log in
OC-12479 Common event is not loading and user can not enter data in visit based events
> OC-12480 site monitor can not log in

- src/main/java/core/org/akaza/openclinica/service/ParticipateServiceImpl.java
- src/main/java/core/org/akaza/openclinica/service/StudyParticipantServiceImpl.java
- src/main/java/core/org/akaza/openclinica/web/pform/PFormCache.java
- src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
- src/main/java/org/akaza/openclinica/controller/EditFormController.java
https://jira.openclinica.com/browse/OC-12448
> OC-12448: View button in SDV Item Details table should open in Review-only mode

- src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
https://jira.openclinica.com/browse/OC-12446
> fix OC-12446: SDV Item Details table doesn't scroll

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- src/main/java/core/org/akaza/openclinica/dao/core/EntityDAO.java
- src/main/java/core/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
- src/main/java/core/org/akaza/openclinica/dao/managestudy/FindSubjectsFilter.java
- src/main/java/core/org/akaza/openclinica/dao/managestudy/ListEventsForSubjectFilter.java
- src/main/java/core/org/akaza/openclinica/service/ParticipantEventService.java
- src/main/java/core/org/akaza/openclinica/web/table/sdv/SubjectEventStatusFilter.java
- src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java
- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
- src/main/java/org/akaza/openclinica/control/submit/VerifyImportedCRFDataServlet.java
- src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- src/main/java/org/akaza/openclinica/view/StudyInfoPanel.java
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
OC-12514 when user schedules event through API no report is generated in bulk action log page, and status of job is Failed
OC-12515 manual import not working on qe -dev env
> OC-12514 when user schedules event through API no report is generated in bulk action log page, and status of job is Failed

- src/main/java/org/akaza/openclinica/controller/SDVController.java
- src/main/webapp/WEB-INF/jsp/include/sideInfo.jsp
- src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
https://jira.openclinica.com/browse/OC-12251
> OC-12251 Update Left Side Panels for SDV page

- src/main/java/core/org/akaza/openclinica/web/table/sdv/SDVUtil.java
- src/main/java/org/akaza/openclinica/controller/dto/SdvItemDTO.java
- src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
https://jira.openclinica.com/browse/OC-11971
AC12: When displaying Brief Description for an item (see AC4), if the Item's Brief Description is null, the display should be "<item Label> (<Item Name>) <ordinal>". If the Item's label is also null, then the display should be "(<Item Name>) <ordinal>".
> OC-11971 SDV Detailed View item table (AC12)

- src/main/java/core/org/akaza/openclinica/service/ParticipantEventService.java
- src/main/java/core/org/akaza/openclinica/web/filter/ApiSecurityFilter.java
scheduled events are not showing on participant dashboard
> OC-12526 scheduled events are not showing on participant dashboard

- src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
https://jira.openclinica.com/browse/OC-12440
> OC-12440 Update SDV Item Details table header layout

- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
Deleting Event CRF data renders blocking new data entry
> OC-12549 Deleting Event CRF data renders blocking new data entry

- src/main/java/core/org/akaza/openclinica/web/table/sdv/SDVUtil.java
- src/main/java/org/akaza/openclinica/controller/dto/SdvItemDTO.java
- src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
AC12: When displaying Brief Description for an item (see AC4), if the Item's Brief Description is null, the display should be "<item Label> (<Item Name>) <ordinal>". If the Item's label is also null, then the display should be "(<Item Name>) <ordinal>". 
https://jira.openclinica.com/browse/OC-11971
> OC-11971 SDV Detailed View item table

- src/main/java/core/org/akaza/openclinica/service/rule/expression/ExpressionService.java
- src/main/java/core/org/akaza/openclinica/web/table/sdv/SDVUtil.java
- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
- src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
- src/main/java/org/akaza/openclinica/domain/enumsupport/EventCrfWorkflowStatusEnum.java
event action rule not working on dev
> OC-12561 event action rule not working on dev

- src/main/java/core/org/akaza/openclinica/web/table/sdv/SDVUtil.java
- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
- src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
- src/main/java/org/akaza/openclinica/domain/enumsupport/EventCrfWorkflowStatusEnum.java
Form Status: SDV page doesn't display completed forms for verification.
> OC-12564 Form Status: SDV page doesn't display completed forms for verification.

- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
- src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
- src/main/java/org/akaza/openclinica/domain/enumsupport/EventCrfWorkflowStatusEnum.java
If user marks complete an empty form, the event status stays scheduled
> OC-12563 If user marks complete an empty form, the event status stays scheduled

- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
- src/main/java/org/akaza/openclinica/domain/enumsupport/EventCrfWorkflowStatusEnum.java
Form status: Not updated in Participant Matrix
Also resolves
OC-12560  Status appearing all Caps in Participant Matrix
> OC-12559 Form status: Not updated in Participant Matrix

- src/main/java/core/org/akaza/openclinica/dao/admin/AuditDAO.java
- src/main/java/core/org/akaza/openclinica/service/StudyEventService.java
- src/main/java/core/org/akaza/openclinica/service/StudyEventServiceImpl.java
- src/main/java/org/akaza/openclinica/controller/BatchCRFMigrationController.java
- src/main/java/org/akaza/openclinica/controller/ChangeCRFVersionController.java
- src/main/resources/core/properties/audit_dao.xml
User is unable to do version change for CRF
> OC-12568 User is unable to do version change for CRF

- src/main/java/core/org/akaza/openclinica/dao/admin/AuditDAO.java
- src/main/java/core/org/akaza/openclinica/service/StudyEventService.java
- src/main/java/core/org/akaza/openclinica/service/StudyEventServiceImpl.java
- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
- src/main/java/org/akaza/openclinica/controller/BatchCRFMigrationController.java
- src/main/java/org/akaza/openclinica/controller/ChangeCRFVersionController.java
- src/main/resources/core/properties/audit_dao.xml
- src/main/resources/migration/tenant/4.0-2020-03-30-OC-12563.xml
- src/main/resources/migration/tenant/release.xml
- src/main/resources/org/akaza/openclinica/i18n/notes.properties
- src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
- src/main/resources/org/akaza/openclinica/i18n/words.properties
- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectAudit.jsp
Status appearing all Caps in Participant Matrix
> OC-12560 Status appearing all Caps in Participant Matrix

- src/main/java/core/org/akaza/openclinica/dao/admin/AuditDAO.java
- src/main/java/core/org/akaza/openclinica/service/StudyEventService.java
- src/main/java/core/org/akaza/openclinica/service/StudyEventServiceImpl.java
- src/main/java/org/akaza/openclinica/controller/BatchCRFMigrationController.java
- src/main/java/org/akaza/openclinica/controller/ChangeCRFVersionController.java
- src/main/resources/core/properties/audit_dao.xml
- src/main/resources/migration/tenant/4.0-2020-03-30-OC-12563.xml
- src/main/resources/migration/tenant/release.xml
- src/main/resources/org/akaza/openclinica/i18n/notes.properties
- src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
- src/main/resources/org/akaza/openclinica/i18n/words.properties
- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectAudit.jsp
Delete Event CRF should reset CRF status to Not Started status
> OC - 12507 Delete Event CRF should reset CRF status to Not Started status

- src/main/java/core/org/akaza/openclinica/web/table/sdv/SDVUtil.java
- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
Participant Matrix: Event Status and the corresponding Icons are reversed
> OC-12577 Participant Matrix: Event Status and the corresponding Icons are reversed

- src/main/java/core/org/akaza/openclinica/dao/hibernate/EventCrfDao.java
https://jira.openclinica.com/browse/OC-12467
> OC-12467 Audit Log capturing Incorrect information about SDV

- src/main/webapp/includes/sessionTimeout.js
[OC-12396](https://jira.openclinica.com/browse/OC-12396)
> OC-12396 Console error every minute with authentication check on SDV page

- src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
https://jira.openclinica.com/browse/OC-12447
> fix OC-12447 Verify button does not work on SDV Item Details table

- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/updateStudyEvent.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
Unable to enter data if the Participant is signed
> OC-12593 Unable to enter data if the Participant is signed

- src/main/java/core/org/akaza/openclinica/dao/submit/ItemDataDAO.java
- src/main/java/core/org/akaza/openclinica/domain/datamap/ItemData.java
- src/main/java/core/org/akaza/openclinica/domain/rule/action/InsertActionProcessor.java
- src/main/java/core/org/akaza/openclinica/logic/rulerunner/DataEntryRuleRunner.java
- src/main/java/core/org/akaza/openclinica/logic/score/ScoreCalculator.java
- src/main/java/core/org/akaza/openclinica/service/crfdata/DynamicsMetadataService.java
- src/main/java/core/org/akaza/openclinica/web/crfdata/ImportCRFDataService.java
- src/main/java/core/org/akaza/openclinica/web/job/CrfBusinessLogicHelper.java
- src/main/java/org/akaza/openclinica/control/admin/DeleteEventCRFServlet.java
- src/main/java/org/akaza/openclinica/control/admin/RemoveStudyServlet.java
- src/main/java/org/akaza/openclinica/control/admin/RestoreStudyServlet.java
- src/main/java/org/akaza/openclinica/control/managestudy/RemoveEventCRFServlet.java
- src/main/java/org/akaza/openclinica/control/managestudy/RemoveSiteServlet.java
- src/main/java/org/akaza/openclinica/control/managestudy/RestoreSiteServlet.java
- src/main/java/org/akaza/openclinica/control/managestudy/UpdateEventDefinitionServlet.java
- src/main/java/org/akaza/openclinica/control/submit/DataEntryServlet.java
- src/main/java/org/akaza/openclinica/control/submit/MarkEventCRFCompleteServlet.java
- src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
- src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
- src/main/java/org/akaza/openclinica/controller/openrosa/processor/AbstractItemProcessor.java
- src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
- src/main/java/org/akaza/openclinica/controller/openrosa/processor/ItemProcessor.java
- src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- src/main/resources/core/properties/itemdata_dao.xml
- src/main/resources/migration/tenant/4.0-2020-04-03-OC-12592.xml
- src/main/resources/migration/tenant/release.xml
> OC-12592 Remove Item Data Status field

- src/main/java/core/org/akaza/openclinica/web/table/sdv/SDVUtil.java
- src/main/java/org/akaza/openclinica/controller/SdvApiController.java
- src/main/java/org/akaza/openclinica/service/ValidateServiceImpl.java
https://jira.openclinica.com/browse/OC-12525
> fix OC-12525: Site Monitor unable to view SDV data

- src/main/java/core/org/akaza/openclinica/service/EventService.java
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
Form version selected for data entry, always opens the default version of the form
> OC-12504 Form version selected for data entry, always opens the default version of the form

- src/main/java/core/org/akaza/openclinica/service/EventService.java
Event Archival: Queries not set to Closed-Modified Status
> OC-12624 Event Archival: Queries not set to Closed-Modified Status

- src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
https://jira.openclinica.com/browse/OC-12244
> OC-12244 SDV table pushing Verify button to next line on smaller windows

- src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
CRFs with no CRF Definition block refresh of Insight database
> OC-12535 CRFs with no CRF Definition block refresh of Insight database

- src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
https://jira.openclinica.com/browse/OC-12444
> OC-12444 Update SDV Item Details table layout and style

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- src/main/java/core/org/akaza/openclinica/domain/rule/action/NotificationActionProcessor.java
- src/main/java/core/org/akaza/openclinica/domain/rule/expression/ExpressionObjectWrapper.java
- src/main/java/core/org/akaza/openclinica/logic/expressionTree/EqualityOpNode.java
- src/main/java/core/org/akaza/openclinica/logic/expressionTree/OpenClinicaExpressionParser.java
- src/main/java/core/org/akaza/openclinica/logic/rulerunner/BeanPropertyRuleRunner.java
- src/main/java/core/org/akaza/openclinica/service/rule/expression/ExpressionService.java
Notification Email not sent by Rule as expected
> OC-12248     Notification Email not sent by Rule as expected

- src/main/java/core/org/akaza/openclinica/web/table/sdv/SDVUtil.java
- src/main/webapp/includes/permissionTagAccess.js
https://jira.openclinica.com/browse/OC-12662
> fix OC-12662: Error when opening Item Data table

- src/main/java/org/akaza/openclinica/control/admin/DeleteEventCRFServlet.java
- src/main/java/org/akaza/openclinica/control/managestudy/DeleteStudyEventServlet.java
- src/main/java/org/akaza/openclinica/control/managestudy/RemoveEventCRFServlet.java
- src/main/java/org/akaza/openclinica/control/managestudy/RemoveStudyEventServlet.java
Signed Event and Participants Updates
> OC-12655 Signed Event and Participants Updates

- src/main/java/core/org/akaza/openclinica/web/table/sdv/SDVUtil.java
https://jira.openclinica.com/browse/OC-12673
> fix OC-12673: SDV errors loading Item table

- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/webapp/includes/global_functions_javascript.js
[OC-12668](https://jira.openclinica.com/browse/OC-12668)
> OC-12668 Opening an Event/Form popup on the Participant Matrix should close any popups that are already open

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- src/main/java/org/akaza/openclinica/domain/enumsupport/EventCrfWorkflowStatusEnum.java
- src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
Form status appearing incorrect in case book for completed forms
> OC-12641 Form status appearing incorrect in case book for completed forms

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
common event form version archive issue
> OC-12642 common event form version archive issue

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
User should not be able to add a new occurrence, after a common event is archived.
> OC-12700 User should not be able to add a new occurrence, after a common event is archived.

- src/main/java/core/org/akaza/openclinica/bean/login/StudyUserRoleBean.java
- src/main/java/core/org/akaza/openclinica/service/PermissionServiceImpl.java
- src/main/java/core/org/akaza/openclinica/service/extract/XsltTriggerService.java
- src/main/java/org/akaza/openclinica/control/admin/CreateJobExportServlet.java
- src/main/java/org/akaza/openclinica/control/admin/PauseJobServlet.java
- src/main/java/org/akaza/openclinica/control/admin/ScheduleJobServlet.java
- src/main/java/org/akaza/openclinica/control/admin/UpdateJobExportServlet.java
- src/main/java/org/akaza/openclinica/control/admin/ViewJobServlet.java
- src/main/java/org/akaza/openclinica/control/admin/ViewSingleJobServlet.java
- src/main/java/org/akaza/openclinica/control/core/SecureController.java
- src/main/java/org/akaza/openclinica/controller/ExtractController.java
- src/main/java/org/akaza/openclinica/controller/StudyParticipantController.java
- src/main/resources/org/akaza/openclinica/i18n/words.properties
- src/main/webapp/WEB-INF/jsp/admin/showJobRow.jsp
- src/main/webapp/WEB-INF/jsp/admin/viewAllJobs.jsp
- src/main/webapp/WEB-INF/jsp/admin/viewJobs.jsp
- src/main/webapp/WEB-INF/jsp/admin/viewSingleJob.jsp
- src/main/webapp/WEB-INF/jsp/include/navBar.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
1) Non admin type users cannot use any of the extract job functionality
2) Expose Jobs under extract data in the task menu
3) Create a scheduled export job
4) View a single export job
5) Edit a scheduled export job
6) Pause and resume a scheduled export job
7) Delete a scheduled export job
> OC-12637, OC-12638, OC-12639, OC-12645, OC-12682

- src/main/java/core/org/akaza/openclinica/dao/managestudy/StudyEventDAO.java
https://jira.openclinica.com/browse/OC-12696
> OC-12696 Common Event Form version migration not working

- src/main/java/core/org/akaza/openclinica/web/table/sdv/SDVUtil.java
https://jira.openclinica.com/browse/OC-12662
> OC-12662 Error when opening Item Data table

- src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
https://jira.openclinica.com/browse/OC-12260
> OC-12260 Center SDV Status icons vertically within row

- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp
[OC-12685](https://jira.openclinica.com/browse/OC-12685)
> OC-12685 Cannot add Common Event Forms for Signed Participant

- src/main/java/core/org/akaza/openclinica/dao/EventCRFSDVFilter.java
- src/main/java/core/org/akaza/openclinica/web/table/sdv/CrfNameMatcher.java
- src/main/java/core/org/akaza/openclinica/web/table/sdv/SDVUtil.java
https://jira.openclinica.com/browse/OC-12732
> fix OC-12732: SDV page table filter by CRF name crashes RT

- web/src/main/java/org/akaza/openclinica/control/submit/CreateDiscrepancyNoteServlet.java
Notes about this specific fix found in the ticket.
> OC-7166 Complete

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
- src/main/resources/org/akaza/openclinica/i18n/words.properties
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
Remove/Restore button is missing for common event for signed participant
> OC-12715 Remove/Restore button is missing for common event for signed participant

- src/main/java/core/org/akaza/openclinica/web/table/sdv/SDVUtil.java
- src/main/webapp/includes/styles.css
(Jigyasa's feedback)
https://jira.openclinica.com/browse/OC-12244?focusedCommentId=202487&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-202487
> OC-12244: SDV Table adjustment for smaller screen size

- src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
- src/main/webapp/includes/styles.css
https://jira.openclinica.com/browse/OC-12260
> OC-12260  Center SDV Status icons vertically within row

- src/main/java/org/akaza/openclinica/control/managestudy/SignStudySubjectServlet.java
- src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/signStudySubject.jsp
[OC-12713](https://jira.openclinica.com/browse/OC-12713)
> OC-12713 Sign Visit Events from the Participant Details Page

- core/src/main/java/org/akaza/openclinica/job/XsltTransformJob.java
- core/src/main/resources/properties/xslt/odm1.3_to_1.2_extensions.xsl
- core/src/main/resources/properties/xslt/odm_spss_dat.xsl
- core/src/main/resources/properties/xslt/odm_spss_sps.xsl
- core/src/main/resources/properties/xslt/xml_convert_sas_data.xsl
- core/src/main/resources/properties/xslt/xml_convert_sas_map.xsl
SPSS, SAS, and ODM1.2 with Extensions Extracts now include YearOfBirth
> OC-4783 Complete

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- src/main/java/core/org/akaza/openclinica/dao/core/EntityDAO.java
- src/main/java/core/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
- src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java
- src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectAudit.jsp
Oops error is reported when changing event statuses through UI
> OC-12785 Oops error is reported when changing event statuses through UI

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- src/main/java/core/org/akaza/openclinica/dao/core/EntityDAO.java
- src/main/java/core/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
- src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java
- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectAudit.jsp
New Audit Log Event Types for Status Refactoring
> OC-12650 New Audit Log Event Types for Status Refactoring

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
[OC-12712](https://jira.openclinica.com/browse/OC-12712)
> OC-12712 Sign Common Events from the Participant Details Page

- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp
[OC-12707](https://jira.openclinica.com/browse/OC-12707)
> OC-12707 Workflow Status Display - Common Events

- src/main/webapp/WEB-INF/jsp/managestudy/removeEventCRF.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/removeStudyEvent.jsp
[OC-12759](https://jira.openclinica.com/browse/OC-12759)
> OC-12759 Remove/Restore Event/CRF should show workflow status in confirm action page.

- src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
https://jira.openclinica.com/browse/OC-12674
> OC-12674 SDV Item Details Table calculate item handling

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- src/main/java/org/akaza/openclinica/control/managestudy/SignStudySubjectServlet.java
- src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
- src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp
[OC-12710](https://jira.openclinica.com/browse/OC-12710)
> OC 12710 Lock/Unlock Common Events from the Participant Details Page

- src/main/webapp/WEB-INF/jsp/include/sideInfo.jsp
- src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
https://jira.openclinica.com/browse/OC-10729
> OC-10729 Make Queries Assigned to Me Link more prominent

- web/src/main/java/org/akaza/openclinica/control/admin/SpreadSheetTableClassic.java
- web/src/main/java/org/akaza/openclinica/control/admin/SpreadSheetTableRepeating.java
Removed the stripQuotes method out of SpreadSheetTableClassic and 'Repeating.
> OC-12778 Strip quotes method

- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
[OC-12784](https://jira.openclinica.com/browse/OC-12784)
> OC-12784 Show Least complete event status for repeating events in Participant Matrix

- src/main/java/core/org/akaza/openclinica/bean/admin/TriggerBean.java
- src/main/java/core/org/akaza/openclinica/dao/extract/ArchivedDatasetFileDAO.java
- src/main/java/core/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
- src/main/java/core/org/akaza/openclinica/logic/odmExport/MetadataUnit.java
- src/main/java/core/org/akaza/openclinica/service/extract/XsltTriggerService.java
- src/main/java/core/org/akaza/openclinica/web/bean/TriggerRow.java
- src/main/java/org/akaza/openclinica/control/admin/CreateJobExportServlet.java
- src/main/java/org/akaza/openclinica/control/admin/PauseJobServlet.java
- src/main/java/org/akaza/openclinica/control/admin/ScheduleJobServlet.java
- src/main/java/org/akaza/openclinica/control/admin/UpdateJobExportServlet.java
- src/main/java/org/akaza/openclinica/control/admin/ViewJobServlet.java
- src/main/java/org/akaza/openclinica/control/admin/ViewLogMessageServlet.java
- src/main/java/org/akaza/openclinica/control/admin/ViewSingleJobServlet.java
- src/main/java/org/akaza/openclinica/controller/ScheduledExtractController.java
- src/main/resources/core/properties/archived_dataset_file_dao.xml
- src/main/resources/migration/tenant/4.0-2020-05-13-OC-12682-2.xml
- src/main/resources/migration/tenant/release.xml
- src/main/resources/org/akaza/openclinica/i18n/words.properties
- src/main/webapp/WEB-INF/jsp/admin/createExportJob.jsp
- src/main/webapp/WEB-INF/jsp/admin/showJobRow.jsp
- src/main/webapp/WEB-INF/jsp/admin/updateExportJob.jsp
- src/main/webapp/WEB-INF/jsp/admin/viewSingleJob.jsp
OC-12828: Change job detail identifier to job_uuid and change API to use job uuid instead of job name. 
OC-12830: Add job uuid to single jobs page. 
OC-12765: Fix oops error when editing job name. 
OC-12857: Show validation errors on update job page
> OC-12828, OC-12830, OC-12765 and OC-12857

- src/main/java/core/org/akaza/openclinica/domain/xform/XformParserHelper.java
Removing Repeating groups from a form throws " Failed to Save changes " error
> OC-12847     Removing Repeating groups from a form throws " Failed to Save changes " error

- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
- src/main/java/org/akaza/openclinica/control/submit/ListDiscNotesForCRFTableFactory.java
- src/main/java/org/akaza/openclinica/control/submit/ListDiscNotesSubjectTableFactory.java
- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/submit/eventLayer.jsp
https://jira.openclinica.com/browse/OC-12831
> OC-12831 Remove option to Delete/Clear Visit Based Events

- src/main/java/core/org/akaza/openclinica/bean/managestudy/DisplayStudyEventBean.java
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
[#OC-12827](https://jira.openclinica.com/browse/OC-12827)
> OC 12827 Sign action should not be shown for visit events when forms in the event is still in data entry started

- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp
https://jira.openclinica.com/browse/OC-12697
> OC-12697 Refactor Participant Details Page filter to work with new statuses

- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
[OC-12880](https://jira.openclinica.com/browse/OC-12880)
> OC-12880 Workflow Status Display - Visit Event Forms on Participant Matrix

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- src/main/java/core/org/akaza/openclinica/bean/submit/EventCRFBean.java
- src/main/java/core/org/akaza/openclinica/dao/EventCRFSDVFilter.java
- src/main/java/core/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
- src/main/java/core/org/akaza/openclinica/dao/hibernate/EventCrfDao.java
- src/main/java/core/org/akaza/openclinica/dao/submit/EventCRFDAO.java
- src/main/java/core/org/akaza/openclinica/service/DataImportService.java
- src/main/java/core/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- src/main/java/core/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
- src/main/java/core/org/akaza/openclinica/web/table/sdv/SDVUtil.java
- src/main/java/core/org/akaza/openclinica/web/table/sdv/SdvStatusMatcher.java
- src/main/java/org/akaza/openclinica/controller/BatchCRFMigrationController.java
- src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
- src/main/java/org/akaza/openclinica/controller/openrosa/processor/EventProcessor.java
- src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
- src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- src/main/resources/migration/tenant/4.0-2020-05-27-OC-12716.xml
- src/main/resources/migration/tenant/functions.xml
- src/main/resources/migration/tenant/release.xml
- src/main/resources/org/akaza/openclinica/i18n/terms.properties
- src/main/resources/org/akaza/openclinica/i18n/words.properties
- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectAudit.jsp
OC-12716: Sdv status is changed to null when the event is created and then changed to corresponding sdv status after first sdv verifcation
OC-12747: Altered the audit page to get the correct sdvStatus values.
> OC-12716 & OC-12747: Changed the default sdv value as null and changed the auditpage for accessing the correct sdv values

- src/main/java/org/akaza/openclinica/control/admin/EventStatusStatisticsTableFactory.java
Event status on home page is all Caps
> OC-12904 Event status on home page is all Caps

- src/main/java/org/akaza/openclinica/control/managestudy/RemoveStudyEventServlet.java
Removing Common event is not unsigning a signed common event
> OC-12918 Removing Common event is not unsigning a signed common event

- src/main/java/core/org/akaza/openclinica/dao/core/EntityDAO.java
- src/main/java/core/org/akaza/openclinica/dao/login/UserAccountDAO.java
- src/main/java/core/org/akaza/openclinica/job/XsltTransformJob.java
- src/main/java/core/org/akaza/openclinica/web/job/TriggerService.java
- src/main/java/org/akaza/openclinica/control/admin/CreateJobExportServlet.java
- src/main/java/org/akaza/openclinica/control/admin/UpdateJobExportServlet.java
1. Added job name to the email error message
2. Removed delete archived dataset file functionality for scheduled jobs
3. Show failed when job fails instead of leave IN_PROGRESS
4. Use local HashMap variable to retrieve user roles instead of global variable thats causing confusion in variable type
> OC-12789: Fix scheduled extract errors

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- src/main/java/core/org/akaza/openclinica/service/DiscrepancyNoteUtil.java
- src/main/java/org/akaza/openclinica/control/managestudy/SignStudySubjectServlet.java
- src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
- src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/signStudySubject.jsp
[OC-12906](https://jira.openclinica.com/browse/OC-12906)
> OC 12906 signing event brings signing participant page instead of signing events page in QE Dev

- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
[OC-12875](https://jira.openclinica.com/browse/OC-12875)
> OC-12875 Status Attribute Display - Visit Events on Participant Details Page

- src/main/java/core/org/akaza/openclinica/service/DiscrepancyNoteUtil.java
- src/main/java/org/akaza/openclinica/control/managestudy/SignStudySubjectServlet.java
- src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
- src/main/resources/core/org/akaza/openclinica/applicationContext-core-service.xml
[OC-12963](https://jira.openclinica.com/browse/OC-12963)
> OC-12963 signing participant from participant matrix page is causing oops error

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
[OC-12962](https://jira.openclinica.com/browse/OC-12962)
> OC-12962 A locked common event is missing sign icon.

- src/main/webapp/WEB-INF/jsp/managestudy/signStudySubject.jsp
[OC-12907](https://jira.openclinica.com/browse/OC-12907)
> OC-12907 Edit button is not present on signing page in QE dev

- src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
- src/main/resources/core/org/akaza/openclinica/applicationContext-core-service.xml
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/includes/styles.css
[OC-12906](https://jira.openclinica.com/browse/OC-12906)
> OC-12906 signing event brings signing participant page instead of signing events page in QE Dev

- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
[OC-12878](https://jira.openclinica.com/browse/OC-12878)
> OC 12878 Status Attribute Display - Visit Event Forms on Single Event Page

- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
[OC-12877](https://jira.openclinica.com/browse/OC-12877)
> OC-12877 Status Attribute Display - Visit Events on Single Event Page

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
[OC-12971](https://jira.openclinica.com/browse/OC-12971)
> OC-12971 Incorrect alert message when user lands on sign event page

- core/pom.xml
- pom.xml
- web/pom.xml
- web/src/main/java/org/akaza/openclinica/control/admin/SpreadSheetTableClassic.java
- web/src/main/java/org/akaza/openclinica/control/admin/SpreadSheetTableRepeating.java
- ws/pom.xml
Variables that are placed inside a SqlParameter are meant to accept single quotes as an valid character.
> OC-12973 Complete

- src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
[OC-12932](https://jira.openclinica.com/browse/OC-12932)
> OC-12932 Support multiple signatures per event

- src/main/webapp/WEB-INF/jsp/managestudy/updateStudyEventSigned.jsp
[OC-12970](https://jira.openclinica.com/browse/OC-12970)
> OC-12970 Clicking cancel on sign event page should bring user back to participant's details page

- src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
- src/main/webapp/WEB-INF/jsp/managestudy/updateStudyEventSigned.jsp
[OC-12969](https://jira.openclinica.com/browse/OC-12969)
> OC-12969 Status not  correctly shown on signing event page in QE dev

- src/main/webapp/WEB-INF/jsp/managestudy/updateStudyEventSigned.jsp
[OC-13007](https://jira.openclinica.com/browse/OC-13007)
> OC-13007 Remove Edit from links from Signature page

- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectsServlet.java
Signing Participants from Participant Matrix with refactored event statuses
> OC-12761 Signing Participants from Participant Matrix with refactored event statuses

- src/main/webapp/WEB-INF/jsp/managestudy/removeEventCRF.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/removeStudyEvent.jsp
[OC-12759](https://jira.openclinica.com/browse/OC-12759)
> OC-12759 Remove/Restore Event/CRF should show workflow status in confirm action page.(feedback)

- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
[OC-12799](https://jira.openclinica.com/browse/OC-12799)
> OC-12799 Edit Action on forms needs to be removed when the corresponding event status is Stopped

- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
Reverts OpenClinica/OpenClinica#3073
> Revert "OC-12799 Edit Action on forms needs to be removed when the corresponding event status is Stopped"

- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
[OC-12759](https://jira.openclinica.com/browse/OC-12759)
> OC-12799 Edit Action on forms needs to be removed when the corresponding event status is Stopped(feedback)

- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
[OC-13020](https://jira.openclinica.com/browse/OC-13020)
> OC-13020 Status Attribute Display - Visit Events on Participant Matrix

- src/main/java/core/org/akaza/openclinica/dao/submit/ItemDataDAO.java
- src/main/java/org/akaza/openclinica/control/core/SecureController.java
- src/main/java/org/akaza/openclinica/control/submit/CreateDiscrepancyNoteServlet.java
- src/main/webapp/WEB-INF/web.xml
[OC-12342](https://jira.openclinica.com/browse/OC-12342)
> OC-12342 OOPS error page thrown when the query icon next to Event Start Date and End Date is clicked

- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
[OC-13021](https://jira.openclinica.com/browse/OC-13021)
> OC-13021 Status Attribute Display - Visit Event Forms on Participant Matrix

- src/main/webapp/WEB-INF/jsp/include/sideIconsSubject.jsp
https://jira.openclinica.com/browse/OC-13037
> OC-13037 Update icon key for new statuses and actions

- src/main/java/core/org/akaza/openclinica/service/ParticipantEventService.java
- src/main/java/core/org/akaza/openclinica/service/ParticipateServiceImpl.java
[OC-12783](https://jira.openclinica.com/browse/OC-12783)
> OC-12783 Update Participate Dashboard to use refactored statuses

- pom.xml
- src/main/java/core/org/akaza/openclinica/service/ParticipateServiceImpl.java
- src/main/resources/migration/tenant/4.0-2020-07-06-OC-12650.xml
- src/main/resources/migration/tenant/release.xml
- src/main/resources/org/akaza/openclinica/i18n/words.properties
Add new event and form statuses to ODM
> OC-12729 Add new event and form statuses to ODM

- src/main/java/com/openclinica/kafka/KafkaService.java
[OC-12910](https://jira.openclinica.com/browse/OC-12910)
> OC-12910 Issues observed in common event/visit event reserve keyword forms

- src/main/java/core/org/akaza/openclinica/service/StudyBuildServiceImpl.java
https://gist.githubusercontent.com/jmcinerney/11969626606659e2fd9179d1da85e159/raw/32aca64b176d4f1d3723ba27242427b470ca2814/gistfile1.txt
> OC-12802: Add logging for debugging

- src/main/resources/org/akaza/openclinica/i18n/words.properties
- src/main/webapp/WEB-INF/jsp/admin/viewCRF.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/viewCRFVersion.jsp
[OC-13125](https://jira.openclinica.com/browse/OC-13125)
> OC 13125 Update Form Metadata page tables

- src/main/resources/org/akaza/openclinica/i18n/words.properties
- src/main/webapp/WEB-INF/jsp/admin/viewCRF.jsp
[OC-13126](https://jira.openclinica.com/browse/OC-13126)
> OC-13126 Update Form Details tables

- src/main/webapp/WEB-INF/jsp/extract/itemDetail.jsp
https://jira.openclinica.com/browse/OC-12813
> OC-12813 Fix appearance of /ViewItemDetail page

- src/main/java/core/org/akaza/openclinica/service/crfdata/BeanPropertyService.java
[OC-12829](https://jira.openclinica.com/browse/OC-12829)
> OC-12829 Status not updated after Event Action Rule is triggered

- src/main/java/core/org/akaza/openclinica/bean/extract/DownloadDiscrepancyNote.java
- src/main/java/core/org/akaza/openclinica/service/DiscrepancyNoteUtil.java
- src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
- src/main/webapp/WEB-INF/jsp/managestudy/viewNotesPrint.jsp
Reverted: https://github.com/OpenClinica/OpenClinica/pull/3096
> OC-13058: Reverted previous OC-13058 code because Removed status is not an EventCrfWorkflowStatus and crfStatus is set from WorkflowStatus

- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
- src/main/webapp/includes/styles.css
[OC-13158](https://jira.openclinica.com/browse/OC-13158)
> OC-13158 Align form status icons

- src/main/resources/org/akaza/openclinica/i18n/workflow.properties
- src/main/webapp/WEB-INF/jsp/managestudy/importData.jsp
https://jira.openclinica.com/browse/OC-13104?focusedCommentId=206518&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-206518
> OC-13104 Add Import Data landing page

- src/main/resources/migration/tenant/4.0-2020-07-13-OC-12663.xml
- src/main/resources/migration/tenant/4.0-2020-07-13-OC-13114.xml
- src/main/resources/migration/tenant/release.xml
Migrate existing event records to new status model
> OC-12663 Migrate existing event records to new status model

- src/main/java/core/org/akaza/openclinica/domain/datamap/Study.java
- src/main/java/core/org/akaza/openclinica/service/StudyBuildServiceImpl.java
- src/main/java/org/akaza/openclinica/control/core/SecureController.java
- src/main/java/org/akaza/openclinica/control/login/ChangeStudyServlet.java
- src/main/webapp/WEB-INF/jsp/include/navBar.jsp
Fix for 404 when on Site level:
https://gist.githubusercontent.com/jmcinerney/11969626606659e2fd9179d1da85e159/raw/32aca64b176d4f1d3723ba27242427b470ca2814/gistfile1.txt
> OC-12802 Add navigation to SBS from Runtime: fix for Site level

- src/main/webapp/WEB-INF/jsp/include/navBar.jsp
[OC-13156](https://jira.openclinica.com/browse/OC-13156)
> OC-13156 Fix border style issues in latest Chrome

- src/main/webapp/WEB-INF/jsp/include/sideIcons.jsp
https://jira.openclinica.com/browse/OC-13134
> OC-13134 Update icon key on SDV page to match other pages

- web/src/main/java/org/akaza/openclinica/control/admin/DeleteEventCRFServlet.java
resolved a secondary bug that is explained in the ticket.
> OC12177 Complete

- src/main/resources/core/properties/audit_dao.xml
- src/main/resources/migration/tenant/4.0-2020-07-06-OC-12650.xml
- src/main/resources/migration/tenant/4.0-2020-07-13-OC-12663.xml
- src/main/resources/migration/tenant/4.0-2020-07-13-OC-13114.xml
- src/main/resources/migration/tenant/4.0-2020-07-15-OC-12650.xml
- src/main/resources/migration/tenant/release.xml
- src/main/resources/org/akaza/openclinica/i18n/words.properties
New Audit Log Event Types for Status Refactoring
> OC-12650     New Audit Log Event Types for Status Refactoring

- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
[OC-13163](https://jira.openclinica.com/browse/OC-13163)
> OC-13163 Display Removed instead of Event Workflow Status on Participant Matrix Event Popup

- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
[OC-13021](https://jira.openclinica.com/browse/OC-13021)
> OC 13021 Status Attribute Display - Visit Event Forms on Participant Matrix(Feedback AC2)

- src/main/resources/org/akaza/openclinica/i18n/notes.properties
- src/main/resources/org/akaza/openclinica/i18n/words.properties
- src/main/resources/org/akaza/openclinica/i18n/workflow.properties
- src/main/webapp/WEB-INF/jsp/submit/uploadFileToMirth.jsp
https://jira.openclinica.com/browse/OC-13139
> OC-13139 Update text on the Flat File Import page

- src/main/resources/migration/tenant/4.0-2020-07-21-OC-13182.xml
- src/main/resources/migration/tenant/functions.xml
- src/main/resources/migration/tenant/release.xml
Reverting https://github.com/OpenClinica/OpenClinica/pull/2968 functions.xml
> OC-13182: Reverting OC-12716 and added in separate xml for liquibase proper working

- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
[OC-13164](https://jira.openclinica.com/browse/OC-13164)
> OC-13164 Display Removed instead of Form Workflow Status on Participant Matrix Form Popup

- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
https://jira.openclinica.com/browse/OC-13160
> OC-13160 Update Removed icon hovertext to "Removed"

- src/main/java/org/akaza/openclinica/control/login/ChangeStudyServlet.java
https://jira.openclinica.com/browse/OC-13192
> fix OC-13192 Oops: A user is unable to switch to Site.

- src/main/webapp/WEB-INF/jsp/include/navBar.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp
- src/main/webapp/includes/jmesa/jquery.jmesa.js
[OC-13156](https://jira.openclinica.com/browse/OC-13156)
> OC-13156 Fix border style issues in latest Chrome(update)

- src/main/java/core/org/akaza/openclinica/dao/managestudy/StudySubjectDAO.java
- src/main/resources/core/properties/study_subject_dao.xml
Column filters don't work on single event Participant Matrix
> OC-13137 Column filters don't work on single event Participant Matrix

- src/main/java/core/org/akaza/openclinica/bean/managestudy/DisplayStudyEventBean.java
[OC-13172](https://jira.openclinica.com/browse/OC-13172)
> OC-13172 Cleared/Archived/Removed form is preventing an event from being signed.

- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
[OC-13186](https://jira.openclinica.com/browse/OC-13186)
> OC-13186 Do not show Signed icon for Removed or Archived Forms

- src/main/resources/core/properties/eventcrf_dao.xml
> OC-13226: Added the query condition to check for non-archived and non-removed form/event for sdvPage

- src/main/webapp/WEB-INF/jsp/include/navBar.jsp
[OC-13156](https://jira.openclinica.com/browse/OC-13156)
> OC-13156 Fix border style issues in latest Chrome(update textarea)

- src/main/java/core/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
- src/main/java/core/org/akaza/openclinica/service/EventService.java
- src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java
- src/main/resources/migration/tenant/4.0-2020-07-13-OC-12663.xml
- src/main/resources/migration/tenant/4.0-2020-07-13-OC-13114.xml
- src/main/resources/migration/tenant/4.0-2020-07-27-OC-13224.xml
- src/main/resources/migration/tenant/release.xml
- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectAudit.jsp
Archiving/Unarchiving forms or events should unsign Events and Participants
> OC-13188 Archiving/Unarchiving forms or events should unsign Events and Participants

- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp
[OC-13228](https://jira.openclinica.com/browse/OC-13228)
> OC-13228 Common Event Archive icon

- src/main/webapp/WEB-INF/jsp/managestudy/signStudySubject.jsp
[OC-13007](https://jira.openclinica.com/browse/OC-13007)
> OC-13007 Remove Edit from links from Signature page(feedback)

- src/main/resources/core/properties/study_subject_dao.xml
Participant Matrix single event view is only showing first Participant duplicated many times.
> OC-13242 Participant Matrix single event view is only showing first Participant duplicated many times.

- src/main/resources/migration/tenant/4.0-2020-07-13-OC-13114.xml
Migrate existing form records to new status model
> OC-13114 Migrate existing form records to new status model

- src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java
Signature attestation is not appearing with correct case in audit log download.
> OC-13265 Signature attestation is not appearing with correct case in audit log download.

- src/main/java/core/org/akaza/openclinica/dao/core/AuditableEntityDAO.java
- src/main/java/core/org/akaza/openclinica/dao/managestudy/ListDiscNotesForCRFFilter.java
- src/main/java/core/org/akaza/openclinica/dao/managestudy/StudyEventDAO.java
- src/main/java/core/org/akaza/openclinica/dao/submit/EventCRFDAO.java
- src/main/java/core/org/akaza/openclinica/domain/datamap/EventCrf.java
- src/main/java/core/org/akaza/openclinica/domain/datamap/StudyEvent.java
- src/main/java/core/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- src/main/java/org/akaza/openclinica/control/admin/DeleteEventCRFServlet.java
- src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
- src/main/java/org/akaza/openclinica/controller/openrosa/processor/EventProcessor.java
- src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
- src/main/resources/core/properties/eventcrf_dao.xml
- src/main/resources/core/properties/study_event_dao.xml
- src/main/resources/migration/tenant/4.0-2020-08-03-OC-13203.xml
- src/main/resources/migration/tenant/release.xml
Remove old status columns from DB
> OC-13203 Remove old status columns from DB

- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
https://jira.openclinica.com/browse/OC-13217
> OC-13217 Event status column auto adjust to accommodate all the icons

- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
[OC-13202](https://jira.openclinica.com/browse/OC-13202)
> OC-13202 Events that are Removed and also Locked should be able to be unlocked

- src/main/resources/migration/tenant/4.0-2020-07-27-OC-13224.xml
Migrate existing event, form, and form version definitions to new status model
> OC-13224 Migrate existing event, form, and form version definitions to new status model

- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
[OC-13164](https://jira.openclinica.com/browse/OC-13164)
> OC-13164 Display Removed instead of Form Workflow Status on Participant Matrix Form Popup(AC2,AC5 update)

- src/main/resources/migration/tenant/4.0-2020-08-04-OC-12932.xml
- src/main/resources/migration/tenant/release.xml
[OC-12932](https://jira.openclinica.com/browse/OC-12932)
> OC-12932 Support multiple signatures per event(update AC4)

- src/main/java/core/org/akaza/openclinica/logic/importdata/ImportDataHelper.java
- src/main/java/core/org/akaza/openclinica/logic/importdata/PipeDelimitedDataHelper.java
- src/main/java/org/akaza/openclinica/controller/DataController.java
- src/main/java/org/akaza/openclinica/controller/helper/RestfulServiceHelper.java
- src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
- Logfile is created before calling before xml request
- Added unexpected_error_occured msg for all the unresolved errors
- Error message for ParticipantId header not matching the mappingFile, if available
> OC-13270: Logfile is created before calling before xml request

- src/main/webapp/WEB-INF/jsp/managestudy/updateStudyEventSigned.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp
[OC-13186](https://jira.openclinica.com/browse/OC-13186)
> OC 13186 Do not show Signed icon for Removed or Archived Forms

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- src/main/java/core/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
OC-13298 Audit log is not preserving old value and new value in some scenarios in ODM after migration
OC-12520  Maintain old status after refactor
This PR includes fix for both above issues
> OC-13298 Audit log is not preserving old value and new value in some scenarios in ODM after migration

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
Audit log is not preserving old value and new value in some scenarios in ODM after migration
> OC-13298 https://jira.openclinica.com/browse/OC-13298

- src/main/resources/migration/tenant/4.0-2020-08-07-OC-12932.xml
- src/main/resources/migration/tenant/release.xml
[OC-12932](https://jira.openclinica.com/browse/OC-12932)
> OC-12932 Support multiple signatures per event(update feedback)

- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
[OC-13185](https://jira.openclinica.com/browse/OC-13185)
> OC-13185 Logic fix for Signing Participants from Participant Matrix with refactored event statuses

- src/main/java/core/org/akaza/openclinica/domain/datamap/Study.java
Remove "nullable = false" constraint as studyEnvUuid is not set for sites (which are stored as study objects).
> Update Study.java nullable constraint on studyEnvUuid

- src/main/webapp/WEB-INF/jsp/managestudy/restoreEventCRF.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/restoreStudyEvent.jsp
[OC-12759](https://jira.openclinica.com/browse/OC-12759)
> OC-12759 Remove/Restore Event/CRF should show workflow status in confirm action page.(update feedback)

- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
- src/main/webapp/includes/Tabs.js
- src/main/webapp/includes/styles.css
https://jira.openclinica.com/browse/OC-13269
> OC-13269 Left/Right arrows on Participant Matrix pop-up do not work in QE.DEV

- src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
- src/main/webapp/WEB-INF/jsp/managestudy/updateStudyEvent.jsp
[OC-13198](https://jira.openclinica.com/browse/OC-13198)
> OC-13198 Allow Locking and Signing of Events via the Update Study Event page

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
Maintain old status after refactor
> OC-12520 Maintain old status after refactor

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
Caused By OC-10160 Terms.properties
> OC-13305:  Altered jsp to check Removed instead of removed & also added check for Removed studySubject status on other places

- src/main/java/core/org/akaza/openclinica/service/EventService.java
Archiving Events/Forms sets RFCs to Closed-Modified
> OC-13318 Archiving Events/Forms sets RFCs to Closed-Modified

- src/main/webapp/WEB-INF/jsp/managestudy/signStudySubject.jsp
[OC-13291](https://jira.openclinica.com/browse/OC-13291)
> OC-13291 Sign Participant page is missing Form Status icons

- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
[OC-13176](https://jira.openclinica.com/browse/OC-13176)
> OC-13176 Not Started Forms in Removed Events should not get Removed status(feedback)

- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp
[OC-13228](https://jira.openclinica.com/browse/OC-13228)
> OC-13228 Common Event Archive icon(update)

- src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
[OC-13176](https://jira.openclinica.com/browse/OC-13176)
> OC-13176 Not Started Forms in Removed Events should not get Removed status(feedback update)

- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
https://jira.openclinica.com/browse/OC-13320
> OC-13320 Error in console when on EnterDataForStudyEvent page

- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
[OC-13185](https://jira.openclinica.com/browse/OC-13185)
> OC-13185 Logic fix for Signing Participants from Participant Matrix with refactored event statuses(update)

- src/main/webapp/WEB-INF/jsp/managestudy/signStudySubject.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/updateStudyEventSigned.jsp
[OC-13291](https://jira.openclinica.com/browse/OC-13291)
> OC-13291 Sign Participant page is missing Form Status icons(feedback)

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- src/main/java/core/org/akaza/openclinica/dao/managestudy/FindSubjectsFilter.java
- src/main/java/core/org/akaza/openclinica/dao/managestudy/ListEventsForSubjectFilter.java
- src/main/java/core/org/akaza/openclinica/dao/managestudy/StudySubjectDAO.java
- src/main/resources/core/properties/study_subject_dao.xml
Filtering by event status or form status columns do not appear to be working properly on Participant Matrix
> OC 13271 Filtering by event status or form status columns do not appear to be working properly on Participant Matrix

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
Sign button missing on common events after participant is signed
> OC-13352 Sign button missing on common events after participant is signed

- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp
https://jira.openclinica.com/browse/OC-13306
> OC-13306 Studies and Sites with Design/Frozen/Locked Status have Add New buttons for Common Events

- src/main/webapp/WEB-INF/jsp/managestudy/signStudySubject.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/updateStudyEventSigned.jsp
[OC-13340](https://jira.openclinica.com/browse/OC-13340)
> OC-13340 Workflow Status Display - Sign Event and Sign Participant Pages

- src/main/java/core/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
- src/main/java/core/org/akaza/openclinica/dao/managestudy/StudyEventDAO.java
- src/main/java/core/org/akaza/openclinica/domain/datamap/StudyEvent.java
- src/main/java/core/org/akaza/openclinica/logic/expressionTree/EqualityOpNode.java
- src/main/java/core/org/akaza/openclinica/logic/expressionTree/OpenClinicaVariableNode.java
- src/main/java/core/org/akaza/openclinica/service/rule/expression/ExpressionService.java
Update Rules to work with new event statuses
> OC-13326 Update Rules to work with new event statuses

- src/main/webapp/WEB-INF/jsp/managestudy/removeStudySubject.jsp
https://jira.openclinica.com/browse/OC-13335
> OC-13335 In Remove participant confirmation page, the status of the events is missing

- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp
https://jira.openclinica.com/browse/OC-13331
> OC-13331 common events that are removed are maintaining their workflow status, though they have attribute removed=yes set

- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
[OC-13337](https://jira.openclinica.com/browse/OC-13337)
> OC-13337 Incorrect icon displayed  in Enter or Validate event page, for not started forms, when a participant is removed

- src/main/java/core/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
- src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
Openclinica:EventName is missing in Full ODM extract after study migration to Stack 12
> OC-13378 Openclinica:EventName is missing in Full ODM extract after study migration to Stack 12

- src/main/java/org/akaza/openclinica/service/ImportServiceImpl.java
User could import data in second occurrence of a non-repeating common event.
> OC-13317 User could import data in second occurrence of a non-repeating common event.

- src/main/java/core/org/akaza/openclinica/dao/EventCRFSDVFilter.java
- src/main/java/core/org/akaza/openclinica/dao/managestudy/CriteriaCommand.java
- src/main/java/core/org/akaza/openclinica/dao/managestudy/FindSubjectsFilter.java
- src/main/java/core/org/akaza/openclinica/dao/managestudy/ListEventsForSubjectFilter.java
- src/main/java/core/org/akaza/openclinica/dao/managestudy/StudyEventDAO.java
- src/main/java/core/org/akaza/openclinica/web/table/sdv/SubjectEventStatusFilter.java
- src/main/java/org/akaza/openclinica/control/AbstractTableFactory.java
- src/main/java/org/akaza/openclinica/control/core/SecureController.java
- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
- src/main/java/org/akaza/openclinica/control/managestudy/ViewStudyEventsServlet.java
- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
- src/main/resources/org/akaza/openclinica/i18n/terms.properties
Add Signed and Locked to status filters to Participant Matrix Events columns and View Events page
> OC-13311 Add Signed and Locked to status filters to Participant Matrix Events columns and View Events page

- src/main/resources/org/akaza/openclinica/i18n/words.properties
https://jira.openclinica.com/browse/OC-13381
> OC-13381 Update Casebook UI text on Participant Details Page

- src/main/webapp/WEB-INF/jsp/admin/restoreSubject.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/restoreStudySubject.jsp
https://jira.openclinica.com/browse/OC-13399
> OC-13399: fix Restore Participant page missing workflow status

- src/main/java/core/org/akaza/openclinica/service/ParticipantEventService.java
[OC-13314](https://jira.openclinica.com/browse/OC-13314)
> OC-13314 Participant dash board is "Lets move on" is not working correctly after all forms are completed

- src/main/java/org/akaza/openclinica/control/managestudy/SignStudySubjectServlet.java
- src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/signStudySubject.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/updateStudyEvent.jsp
- src/main/webapp/WEB-INF/jsp/managestudy/updateStudyEventSigned.jsp
- src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
[OC-13403](https://jira.openclinica.com/browse/OC-13403)
> OC-13403 All actions are listed on forms for removed participant  on Enter or Validate Data page

- src/main/webapp/WEB-INF/jsp/managestudy/signStudySubject.jsp
[OC-13409](https://jira.openclinica.com/browse/OC-13409)
> OC-13409 Wrong form version number appears on Sign Participant page

- src/main/webapp/WEB-INF/jsp/managestudy/removeStudySubject.jsp
https://jira.openclinica.com/browse/OC-13414
> fix OC-13414: Site name missing on Remove Participant page

- src/main/webapp/WEB-INF/jsp/managestudy/signStudySubject.jsp
This reverts commit d1d1d2ec05b871fdc17625ad8fde70aab6ece936.
> Revert "OC-13409 Wrong form version number appears on Sign Participant page"

- src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
https://jira.openclinica.com/browse/OC-13417
> fix OC-13417: Event can be marked Complete when Required form is Removed

- src/main/java/core/org/akaza/openclinica/service/EventService.java
- src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
Should be able to complete event if required form is archived
> OC-13452 Should be able to complete event if required form is archived

- src/main/java/core/org/akaza/openclinica/service/EventService.java
Unarchiving a Not Started form should not unsign the event it is in
> OC-13450 Unarchiving a Not Started form should not unsign the event it is in

- src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
- src/main/java/org/akaza/openclinica/control/managestudy/SignStudySubjectServlet.java
Monitors getting oops error when filtering single events in staging
> OC-13478 Monitors getting oops error when filtering single events in staging

- src/main/java/org/akaza/openclinica/control/managestudy/SignStudySubjectServlet.java
Removed or Archived events should not be signed when signing participants
> OC-13472 Removed or Archived events should not be signed when signing participants

- src/main/java/core/org/akaza/openclinica/dao/hibernate/StudyDao.java
- src/main/java/core/org/akaza/openclinica/domain/datamap/Study.java
- src/main/java/org/akaza/openclinica/config/BoardUrlConfig.java
- src/main/java/org/akaza/openclinica/control/core/SecureController.java
- src/main/java/org/akaza/openclinica/control/login/ChangeStudyServlet.java
- src/main/webapp/WEB-INF/jsp/include/navBar.jsp
Reverts OpenClinica/OpenClinica#3374
> Undoing Revert for OC-13457

- src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
Unable to sign participant if archived common form in data entry started present
> OC-13497 Unable to sign participant if archived common form in data entry started present

- src/main/java/core/org/akaza/openclinica/service/ParticipateServiceImpl.java
[OC-13517](https://jira.openclinica.com/browse/OC-13517)
> OC-13517 Prefilled Contact Form prevents Participate to move to next Event

- src/main/java/org/akaza/openclinica/control/managestudy/SignStudySubjectServlet.java
- src/main/webapp/WEB-INF/jsp/managestudy/signStudySubject.jsp
https://jira.openclinica.com/browse/OC-13474
> fix OC-13474: Site name is missing on Sign Participant page

- src/main/java/org/akaza/openclinica/control/submit/CreateDiscrepancyNoteServlet.java
[OC-13460](https://jira.openclinica.com/browse/OC-13460)
> OC-13460 Unable to assign new query to user for Start Date/End Date from Enter or Validate Data page if participant/event is assigned to site ID

- src/main/java/org/akaza/openclinica/control/submit/ViewDiscrepancyNoteServlet.java
[OC-13461](https://jira.openclinica.com/browse/OC-13461)
> OC-13461 Oops error appears if updating existing query for Start Date/End Date if query wasn't assigned to a user

- src/main/java/org/akaza/openclinica/control/admin/DeleteEventCRFServlet.java
- src/main/resources/org/akaza/openclinica/i18n/notes.properties
- src/main/resources/org/akaza/openclinica/i18n/words.properties
- src/main/webapp/WEB-INF/jsp/admin/deleteEventCRF.jsp
https://jira.openclinica.com/browse/OC-12832
> OC-12832 Update "Clear Event CRF" confirmation page

- src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp
https://jira.openclinica.com/browse/OC-12131
> fix OC-12131: Event Header should be hidden when all forms are hidden

- src/main/java/core/org/akaza/openclinica/dao/admin/AuditDAO.java
- src/main/java/core/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
- src/main/resources/core/properties/audit_dao.xml
[OC-12389](https://jira.openclinica.com/browse/OC-12389)
> OC-12389 Update Participate button to open form that has already been started

- core/src/main/java/org/akaza/openclinica/dao/managestudy/StudyEventDAO.java
> when only 1 occurrence is scheduled and has data entered, still be able to be changed to non repeating

- web/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFDataService.java
- web/src/main/java/org/akaza/openclinica/web/filter/OpenClinicaUsernamePasswordAuthenticationFilter.java
- ws/src/main/java/org/akaza/openclinica/web/crfdata/DataImportService.java
Please see #3152 
and this PR need to merge after #3472 merged, because they share some code
> OC-8239:WS CRF import creates duplicate event CRF if a different CRF version already has been started for that event.

- core/src/main/java/org/akaza/openclinica/dao/managestudy/StudyEventDAO.java
it needs to still be able to be changed to non repeating
> OC-12780:when only 1 occurrence is scheduled and has data entered

- core/src/main/java/org/akaza/openclinica/dao/submit/EventCRFDAO.java
- core/src/main/resources/properties/eventcrf_dao.xml
- web/src/main/java/org/akaza/openclinica/control/submit/ImportCRFInfoContainer.java
- web/src/main/java/org/akaza/openclinica/control/submit/VerifyImportedCRFDataServlet.java
- web/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFDataService.java
- web/src/main/webapp/WEB-INF/jsp/managestudy/chooseCRFVersion.jsp
> OC-8255:Manual CRF import creates duplicate event CRF if a different CRF version already has been started for that event.

- core/src/main/java/org/akaza/openclinica/dao/core/OCContextLoaderListener.java
- core/src/main/resources/org/akaza/openclinica/applicationContext-core-db.xml
- pom.xml
upgrade liquibase to latest version to fix reported issue
> OC-14264:Upgrade OC 3.16 Postgres to 11

- web/src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpressNew.jsp
Reverts OpenClinica/OpenClinica#3379
> Revert " .OC-13471:Duplicate Subjects Created"

- web/src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpressNew.jsp
Reverts OpenClinica/OpenClinica#3520
> Revert "OC-14134:fixed--Create subject from the subject matrix page is failing"

- web/src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpressNew.jsp
Reverts OpenClinica/OpenClinica#3380
> Revert " OC-13471:Duplicate Subjects Created"
