OpenClinica/OpenClinica

core/pom.xml
web/pom.xml
web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyServletNew.java
web/src/main/java/org/akaza/openclinica/controller/ParticipantPortalRegController.java
web/src/main/java/org/akaza/openclinica/web/pmanage/Authorization.java
web/src/main/java/org/akaza/openclinica/web/pmanage/AuthorizationStatus.java
web/src/main/java/org/akaza/openclinica/web/pmanage/Organization.java
web/src/main/java/org/akaza/openclinica/web/pmanage/Study.java
web/src/main/webapp/WEB-INF/jsp/admin/viewFullStudy.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudyNew.jsp
web/src/main/webapp/WEB-INF/pages-servlet.xml

A study designer can view the status of PP study access request

OC-5769: A study designer can view the status of PP study access request

---

web/src/main/java/org/akaza/openclinica/controller/AccountController.java

adding a dummy password when creating participant user

OC-6132a Registering a participant stores the participants info in OC

---

web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaXmlGenerator.java
web/src/main/java/org/akaza/openclinica/web/pform/widget/BaseWidget.java

I have converted the datatype from 'integer' into 'int' to resolve this
issue as Martin suggested that might be the cause.
I also added temporarily logger.info for the whole body , 
1. for rendering
2. saving

OC-6216  OCForm: Integer field validation fails

---

core/src/main/java/org/akaza/openclinica/service/PformSubmissionService.java

Commented out the methods and their call that creates a new user account
in case if it does not exist during PForm data submission

OC-6202 Removing the implementation of creating new user accounts during PForm Data Submission

---

web/src/main/java/org/akaza/openclinica/controller/AccountController.java
web/src/main/java/org/akaza/openclinica/controller/OdmController.java
web/src/main/java/org/akaza/openclinica/controller/OdmStudySubjectController.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

checking in implementation code for OC-6167 .6168 ,6169,6170 
adding access permission to requests

OC-6167 Preview PForm is available if a study has (any) status

---

web/src/main/java/org/akaza/openclinica/control/managestudy/AddCRFToDefinitionServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/DefineStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/InitUpdateEventDefinitionServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/RemoveEventDefinitionServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/RestoreEventDefinitionServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateEventDefinitionServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewEventDefinitionReadOnlyServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewEventDefinitionServlet.java
web/src/main/java/org/akaza/openclinica/controller/OdmController.java
web/src/main/webapp/WEB-INF/jsp/managestudy/defineStudyEvent3.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/defineStudyEventConfirm.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/removeDefinition.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/restoreDefinition.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateEventDefinition1.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateEventDefinitionConfirm.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewEventDefinition.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewEventDefinitionNoSidebar.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewEventDefinitionReadOnly.jsp

I ignored Hiden CRFs by removing the filtering condition on site and
study level subjects
Cosmetic change :Hide CRF : (update to remove the space) 
Change “true / false” to “Yes, No” on all CRUD operations

OC - 6229 Tagging related bug fixes

---

web/src/main/java/org/akaza/openclinica/controller/AccountController.java

Issues with authentication to OCUI
1. Site level users (CRC and Data Entry) are being rejected by OCUI
2. If an authorized user (CRC or Data Entry (Site and Study) is removed then he can still log in to OCUI

OC-6273: Issues with authentication to OCUI

---

web/src/main/java/org/akaza/openclinica/controller/AccountController.java

OC-6288 Site Level User is able to find subjects assigned to a site other than his in OCUI

---

web/src/main/webapp/WEB-INF/jsp/submit/administrativeEditing.jsp
web/src/main/webapp/WEB-INF/jsp/submit/doubleDataEntry.jsp
web/src/main/webapp/WEB-INF/jsp/submit/initialDataEntryNw.jsp

OC-6101: Disable Save in CRF until page renders.  Initial checkin.

---

web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaXmlGenerator.java

OC:6164 - Deny access to Participate specific OC APIs when Participate is not Enabled
Current_Date error in ocForm

Fixing bugs & enhancing Security:

---

core/src/main/java/org/akaza/openclinica/service/PformSubmissionService.java

Fix for Oops error , also added a statement not to show fields with
empty records

OC-showhideBug

---

web/src/main/java/org/akaza/openclinica/control/submit/ParticipantFormServlet.java
web/src/main/java/org/akaza/openclinica/web/pform/EnketoAPI.java
web/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties

when PManage and/or PForm is not available
System should gracefully handle the absence of these systems

OC-6277 Fix Oops page errors in OpenClinica

---

core/src/main/java/org/akaza/openclinica/bean/login/UserDTO.java
web/src/main/java/org/akaza/openclinica/controller/AccountController.java

OC-6373	Send email to participant
OC-6372	Persist email address (APIs)
OC-6371	Add email to registration UI

OC-6323 Email based authentication

---

core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java

OC-6425 Order of Events in Print CRF TOC is changed.

---

web/src/main/java/org/akaza/openclinica/control/admin/DeleteEventCRFServlet.java

status
Updated the code to address AC2 regarding to signed events

OC-6412 Deleting event CRF will have status checks / updates Event

---

web/src/main/java/org/akaza/openclinica/control/admin/DeleteEventCRFServlet.java

Event 
Updated the User for Event audit log record

OC-6412  OC-6412 Deleting event CRF will have status checks / updates

---

web/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFDataService.java
web/src/main/java/org/akaza/openclinica/web/job/ImportSpringJob.java
web/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
ws/src/main/java/org/akaza/openclinica/web/crfdata/DataImportService.java
ws/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFDataService.java
ws/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFInfo.java
ws/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFInfoContainer.java
ws/src/main/java/org/akaza/openclinica/web/job/CrfBusinessLogicHelper.java
ws/src/main/java/org/akaza/openclinica/ws/DataEndpoint.java
ws/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
ws/src/main/resources/org/akaza/openclinica/i18n/ws_messages.properties

OC-6441: Import jobs should fail file when hard validation errors encountered.

---

core/src/main/java/org/akaza/openclinica/service/rule/RulesPostImportContainerService.java
core/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
web/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties

<Subject> elements generate Oops Error

OC-6483 Notification Rule with more than 255 characters in <Message> and

---

web/src/main/java/org/akaza/openclinica/control/submit/ViewRuleAssignmentTableToolbar.java

OC-6485 Rule Name and Rule OID columns now missing from default view of

---

web/src/main/java/org/akaza/openclinica/controller/AccountController.java

I'm using the Etc/GMT+X and Etc/GMT-X entries of the pg_timezone_names (the pg_timezone_names part is per Joe's direction)

OC-6472 OCUI captures participant's time zone and sends it to OC

---

core/src/main/resources/migration/3.6/2015-05-21-OC-5994.xml

user_name has different lengths

OC-5994 Unable to asign user role due to data base column definition for

---

web/src/main/java/org/akaza/openclinica/controller/RuleController.java

OC 6509 Issues with new rule designer

---

core/src/main/java/org/akaza/openclinica/bean/rule/EmailHandler.java

This reverts commit 5de3433a7ebd4c690f32489f7f3bd8a5f1b8e07e, reversing
changes made to 3ad718929f3fb4db3386cc18f4462daca2a14958.

Revert "Merge pull request #218 from jkeremian/OC-6521"

---

web/src/main/java/org/akaza/openclinica/controller/AccountController.java
web/src/main/java/org/akaza/openclinica/controller/AnonymousFormController.java

Fix for AC1 , added mayProceed() method to block non participant studies
to be accessed

OC-6611   API: GET anonymous form URL

---

web/src/main/java/org/akaza/openclinica/controller/AnonymousFormController.java

Fix for site level form not loading

OC-6611  API: GET anonymous form URL

---

core/src/main/java/org/akaza/openclinica/dao/login/UserAccountDAO.java

Root user cannot log in to study that is made available in Japanese

OC-6670 Root user cannot log in to study that is made available in Japanese

---

web/src/main/java/org/akaza/openclinica/controller/DiscrepancyNoteController.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaXmlGenerator.java

OC-6571: Create OC endpoint to persist follow up
OC-6468: OC Participate - Item Header appears left-aligned with break lines

OC-6571 & OC-6468

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectAuditLogServlet.java
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectAudit.jsp

Date of Birth configuration effect on audit log

OC-6677  Date of Birth configuration effect on audit log

---

core/src/main/java/org/akaza/openclinica/dao/managestudy/EventDefinitionCRFDAO.java
core/src/main/resources/org/akaza/openclinica/i18n/exceptions.properties
web/src/main/java/org/akaza/openclinica/control/managestudy/DefineStudyEventServlet.java
web/src/main/resources/org/akaza/openclinica/i18n/exceptions.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/defineStudyEventConfirm.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateEventDefinitionConfirm.jsp

Minor bug fixes for anonymous submission
Fixes for 3 bugs reported in the ticket

OC-6681 Minor bug fixes for anonymous submission

---

web/src/main/java/org/akaza/openclinica/control/form/Validator.java

Internationalization Date Error in OpenClinica 3.7

OC-6733a Internationalization Date Error in OpenClinica 3.7

---

web/src/main/java/org/akaza/openclinica/control/form/Validator.java
web/src/main/java/org/akaza/openclinica/controller/UserAccountController.java

OC-6733a i18n issue  request.getLocale

---

web/src/main/java/org/akaza/openclinica/control/form/Validator.java
web/src/main/java/org/akaza/openclinica/controller/UserAccountController.java

i18n issue with LocaleResolver

OC-6733b i18n issue with LocaleResolver

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/RuleSetRuleDao.java
core/src/main/java/org/akaza/openclinica/dao/hibernate/ViewRuleAssignmentFilter.java
core/src/main/java/org/akaza/openclinica/dao/hibernate/ViewRuleAssignmentSort.java
web/src/main/java/org/akaza/openclinica/control/submit/ViewRuleAssignmentTableFactory.java

Manage rules table search by RunOnSchedule attributes not working

OC-6585 Manage rules table search by RunOnSchedule attributes not working

---

web/src/main/java/org/akaza/openclinica/controller/StudyController.java

API to Create Event won't create repeating group events
minor change in code to fix this issue

OC-6798 API to Create Event won't create repeating group events

---

core/src/main/java/org/akaza/openclinica/bean/login/ParticipantDTO.java

Notification action should send email via ocui when Participate is
enabled

OC-6738 Notification action should send email via ocui when Participate is enabled

---

web/src/main/webapp/WEB-INF/jsp/include/showSideMessage.jsp

DEV BUG: Missing content in div.alert

OC-6800 DEV BUG: Missing content in div.alert

---

web/src/main/java/org/akaza/openclinica/control/admin/ListCRFServlet.java

OC-6807 Link to CRF Library is Broken

---

core/src/main/resources/migration/3.9/2015-11-12-OC-6820.xml
core/src/main/resources/migration/3.9/release.xml
core/src/main/resources/migration/master.xml

Apply Uniqueness Constraint to study event table

OC-6820 Apply Uniqueness Constraint to study event table

---

web/src/main/webapp/WEB-INF/jsp/include/home-header.jsp
web/src/main/webapp/WEB-INF/jsp/login-include/login-header.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewSectionDataEntry.jsp
web/src/main/webapp/WEB-INF/jsp/submit/addDiscrepancyNote.jsp

This is the fix for years long issue open in jira correcting how resources are referenced in jsf files (fixing issues in reverse proxy environment).

OC-3334: Fix URI for css, js and images for reverse proxy setups

---

core/src/main/java/org/akaza/openclinica/domain/rule/action/InsertActionProcessor.java

OC-6854 Fix for Jenkins fail

---

core/pom.xml

OC-6854 Fix for Test Failure issue

---

core/src/main/java/org/akaza/openclinica/domain/rule/action/RandomizeActionProcessor.java
core/src/main/java/org/akaza/openclinica/service/RandomizeService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/DynamicsMetadataService.java

OC-6853 Run randomization on import

---

core/src/main/java/org/akaza/openclinica/domain/rule/action/RuleActionBean.java

Rule upload doesn't update exixting Run On

OC-6874 Rule upload doesn't update exixting Run On

---

core/src/main/java/org/akaza/openclinica/service/rule/RulesPostImportContainerService.java

DEV BUG: Valid Event Action rule is getting a NullPointer Exception when
attempting to validate or save in Rule Designer

OC-6877 DEV BUG: Valid Event Action rule is getting a NullPointer Exception when attempting to validate or save in Rule Designer

---

core/src/main/java/org/akaza/openclinica/service/crfdata/DynamicsMetadataService.java

Running InsertAction rules in batch on a CRF that has been marked
complete

OC-6883 Running InsertAction rules in batch on a CRF that has been marked complete

---

web/src/main/resources/datainfo.properties
web/src/main/resources/org/akaza/openclinica/i18n/licensing.properties
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/includes/styles.css

fixing the OC-6885

---

core/src/main/java/org/akaza/openclinica/domain/rule/action/RandomizeActionProcessor.java
core/src/main/java/org/akaza/openclinica/service/RandomizeService.java
web/src/main/java/org/akaza/openclinica/controller/StudyModuleController.java
web/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties

OCUI get Randomization configuration from OCUI

OC-6850 OCUI get Randomization configuration from OCUI

---

core/src/main/java/org/akaza/openclinica/bean/odmbeans/StudyParameterConfigurationBean.java
core/src/main/java/org/akaza/openclinica/bean/service/StudyParameterConfig.java
web/src/main/java/org/akaza/openclinica/control/admin/ViewStudyServlet.java
web/src/main/webapp/WEB-INF/jsp/admin/viewFullStudy.jsp

Study Page if Participant Portal is not Enabled 
&
OC-6893
Randomization Study Configuration Should appear on the View Study Page

OC-6649 Participate Study Configuration & OC-6893 Randomization Study Configuration Should appear on the View Study Page

---

core/src/main/java/org/akaza/openclinica/service/pmanage/RandomizationRegistrar.java
core/src/main/java/org/akaza/openclinica/service/pmanage/SeRandomizationDTO.java
web/src/main/java/org/akaza/openclinica/controller/StudyModuleController.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/studymodule.jsp

Add new module UI section in build study page

OC-6847  Add new module UI section in build study page

---

web/src/main/java/org/akaza/openclinica/controller/StudyModuleController.java

Update the URL from dataInfo into  Sealed envelope URL

OC-6847 Add new module UI section in build study page

---

core/src/main/java/org/akaza/openclinica/service/rule/expression/ExpressionService.java

DEV BUG: Discrepancy Notes Action on Cross Events not working
This dev-bug ticket was introduced with the fix code merge of OC-2047
story. I'm reverting that code that will resolve automatically this issue
and re-address OC-2047 separately.

OC-6888 DEV BUG: Discrepancy Notes Action on Cross Events not working

---

core/src/main/java/org/akaza/openclinica/service/pmanage/Study.java

DEVBUG: Requesting Access to Participate

OC-6903 DEVBUG: Requesting Access to Participate

---

core/src/main/java/org/akaza/openclinica/service/pmanage/RandomizationRegistrar.java
core/src/main/java/org/akaza/openclinica/service/pmanage/SeRandomizationDTO.java

DEVBUG: Requesting Access to Participate

OC-6903 Status change bug for Randomization

---

core/src/main/java/org/akaza/openclinica/service/rule/expression/ExpressionService.java
web/src/main/resources/org/akaza/openclinica/i18n/notes.properties

Rules not working when absolute paths (versus relative paths) are used
in the expression or action

OC-2047 Absolute vs Relative Rule Expression

---

core/src/main/java/org/akaza/openclinica/service/pmanage/RandomizationRegistrar.java

DEV BUG: Remove exception from register randomize module

OC-6913 DEV BUG: Remove exception from register randomize module

---

core/src/main/java/org/akaza/openclinica/service/rule/expression/ExpressionService.java

Validate item belongs to item group in rule experssions

OC-6925 Validate item belongs to item group in rule experssions

---

core/src/main/java/org/akaza/openclinica/bean/managestudy/EventDefinitionCRFBean.java
web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
web/src/main/java/org/akaza/openclinica/control/managestudy/CreateSubStudyServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/DefineStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/InitUpdateEventDefinitionServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/InitUpdateSubStudyServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/RemoveEventDefinitionServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/RestoreEventDefinitionServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateEventDefinitionServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateSubStudyServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewEventDefinitionReadOnlyServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewEventDefinitionServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewSiteServlet.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/createSubStudy.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/createSubStudyConfirm.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/defineStudyEvent3.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/defineStudyEvent4.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/defineStudyEventConfirm.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/removeDefinition.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/restoreDefinition.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateEventDefinition1.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateEventDefinitionConfirm.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateSubStudy.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewEventDefinition.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewEventDefinitionNoSidebar.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewEventDefinitionReadOnly.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewSite.jsp

Study designer can mark form as PForm AND Anonymous AND Offline

OC-6989 Study designer can mark form as PForm AND Anonymous AND Offline

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/MetaDataReportBean.java
core/src/main/java/org/akaza/openclinica/bean/odmbeans/PresentInEventDefinitionBean.java
core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
ws/src/main/java/org/akaza/openclinica/ws/StudyEventDefinitionEndpoint.java
ws/src/main/webapp/WEB-INF/schemas/beans.xsd

Show offline option(s) in all representations of study metadata

OC-6990 Show offline option(s) in all representations of study metadata

---

core/src/main/java/org/akaza/openclinica/domain/xform/dto/Upload.java
core/src/main/java/org/akaza/openclinica/service/crfdata/ResponseSetService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java

Upload Xform with an image type

OC-7012 Upload Xform with an image type

---

web/src/main/webapp/WEB-INF/jsp/managestudy/defineStudyEvent3.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateEventDefinitionConfirm.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewEventDefinitionReadOnly.jsp

fix for event definition page table borders

OC-7012 fix for event definition page table borders

---

web/src/main/webapp/WEB-INF/jsp/managestudy/updateEventDefinition1.jsp

OC-6990 Offline Tagging

---

core/src/main/java/org/akaza/openclinica/service/rule/expression/ExpressionService.java

Rule Validation with itemGroup

OC-6925 Rule Validation with itemGroup

---

web/src/main/webapp/WEB-INF/jsp/managestudy/createSubStudy.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/createSubStudyConfirm.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/defineStudyEvent3.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/defineStudyEvent4.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateEventDefinition1.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateSubStudy.jsp

OC-7027 Site Creation not working

---

web/src/main/java/org/akaza/openclinica/control/submit/UploadFileServlet.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionService.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/PformValidator.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/SubmissionContainer.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/ItemProcessor.java

Subject can capture an image in the questionnaire

Oc 7013 Subject can capture an image in the questionnaire 

---

core/src/main/java/org/akaza/openclinica/domain/xform/dto/Input.java
core/src/main/java/org/akaza/openclinica/domain/xform/dto/Select.java
core/src/main/java/org/akaza/openclinica/domain/xform/dto/Select1.java
core/src/main/java/org/akaza/openclinica/domain/xform/dto/UserControl.java
core/src/main/java/org/akaza/openclinica/service/crfdata/ResponseSetService.java
core/src/main/java/org/akaza/openclinica/validator/xform/ResponseSetValidator.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/viewEventDefinition.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewEventDefinitionNoSidebar.jsp

Subject can capture an image in the questionnaire 
-Fix for uploading any image file supported by enketto
-added validation at upload time for non image Upload mediatypes
-also fix for view_event_definition page table mis-aligned

OC-7013 Subject can capture an image in the questionnaire 

---

web/src/main/java/org/akaza/openclinica/control/admin/SpreadSheetTableRepeating.java

Postgres 9.5 - CRF Upload Issue

OC-7023 Postgres 9.5 - CRF Upload Issue

---

web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateEventDefinitionServlet.java

Devbug: Enabling Offline Status

OC-7035 Devbug: Enabling Offline Status

---

core/src/main/java/org/akaza/openclinica/bean/service/SqlProcessingFunction.java

DEVBUG: Datamart extract not working

OC-7042 DEVBUG: Datamart extract not working

---

web/src/main/resources/org/akaza/openclinica/i18n/notes.properties
web/src/main/webapp/WEB-INF/jsp/login/login.jsp

Update messaging for browser use

OC-6968 Update messaging for browser use

---

web/src/main/java/org/akaza/openclinica/controller/IdtViewController.java

Blocking Rest Calls for non authenticated users

OC-6932 Blocking Monitoring related Rest Calls for non authenticated users

---

core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java
web/src/main/java/org/akaza/openclinica/controller/StudyController.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/ItemProcessor.java

Define reserved term for confirming study subject ID

OC-7060 Define reserved term for confirming study subject ID

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java

Item validation for DATE/INT treats whitespace as empty/null but saves
the value anyway

OC-6587 Item validation for DATE/INT treats whitespace as empty/null but saves the value anyway

---

web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateEventDefinitionServlet.java
web/src/main/webapp/WEB-INF/jsp/managestudy/defineStudyEvent3.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateEventDefinition1.jsp

For an event to have an anonymous form it must be repeating

OC-7066 For an event to have an anonymous form it must be repeating

---

core/src/main/resources/migration/master.xml

OC does not record correct user for CRF Version Migration in Audit Logs

OC-6711 OC does not record correct user for CRF Version Migration in Audit Logs

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/DynamicsItemFormMetadataDao.java

Rule ShowAction/HideAction not behaving properly after CRF migration

OC-5918 Rule ShowAction/HideAction not behaving properly after CRF migration

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ChangeDefinitionOrdinalServlet.java
web/src/main/webapp/WEB-INF/jsp/include/showTableForEventDefinition.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventDefinitionRow.jsp

Remove sort link in the manage event definition page

OC-7100 Remove sort link in the manage event definition page

---

web/src/main/java/org/akaza/openclinica/controller/StudyController.java

API must not include secondaryProtocolID

OC-7095 API must not include secondaryProtocolID

---

web/src/main/java/org/akaza/openclinica/controller/ScheduledJobController.java

Removing (Pausing) an Export Job Results in the Job Still Running at the
Scheduled Time

OC-6879 Removing (Pausing) an Export Job Results in the Job Still Running at the Scheduled Time

---

core/src/main/resources/properties/itemdata_dao.xml

CRF can be marked complete without all required fields being completed

OC-7083 CRF can be marked complete without all required fields being completed

---

web/src/main/java/org/akaza/openclinica/controller/AnonymousFormControllerV2.java

return name and description of crf along with enketo url

for OC-7086 Load offline dashboard

---

core/src/main/java/org/akaza/openclinica/service/rule/expression/ExpressionService.java

Non-existent ItemOID causes Ops error on Rule Upload

OC-7122 Non-existent ItemOID causes Ops error on Rule Upload

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/DynamicsItemFormMetadataDao.java
core/src/main/java/org/akaza/openclinica/dao/submit/ItemFormMetadataDAO.java
core/src/main/resources/properties/item_form_metadata_dao.xml
core/src/main/resources/properties/itemdata_dao.xml
web/src/main/java/org/akaza/openclinica/control/submit/DataEntryServlet.java

Hidden required fields prevent CRF from being marked compete after CRF
version migration

OC-3465 Hidden required fields prevent CRF from being marked compete after CRF version migration

---

web/src/main/webapp/js/com/openclinica/renderer/StudyDataLoader.js

Devbug: Issue Opening PrintCRF

OC-7128 Devbug: Issue Opening PrintCRF

---

web/src/main/java/org/akaza/openclinica/control/submit/ViewRuleAssignmentTableFactory.java

XLS Export of rules overview does not work with an Event Action rule
uploaded

OC-6902 XLS Export of rules overview does not work with an Event Action rule uploaded

---

web/src/main/java/org/akaza/openclinica/control/managestudy/RemoveEventCRFServlet.java

E-mails to administrators following removal of CRF from Event

OC-6620 E-mails to administrators following removal of CRF from Event

---

web/src/main/webapp/WEB-INF/web.xml

Failure exporting Discrepancy Notes - 404 error

OC-6433 https://jira.openclinica.com/browse/OC-6433

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java

Dataset creation fails in Regression Test

OC-7134 Dataset creation fails in Regression Test

---

core/src/main/java/org/akaza/openclinica/domain/technicaladmin/AuditUserLoginBean.java
core/src/main/java/org/akaza/openclinica/domain/technicaladmin/LoginStatus.java
core/src/main/resources/migration/master.xml
core/src/main/resources/org/akaza/openclinica/i18n/terms.properties
web/src/main/java/org/akaza/openclinica/control/admin/AuditUserLoginTableFactory.java
web/src/main/java/org/akaza/openclinica/controller/AccountController.java
web/src/main/resources/org/akaza/openclinica/i18n/terms.properties

CRC can see access code after connecting a participant

OC-7118 CRC can see access code after connecting a participant

---

web/src/main/java/org/akaza/openclinica/controller/OdmController.java

Open Participant form in OpenClinica but not saving makes form invalid
for participant

OC-7137 Open Participant form in OpenClinica but not saving makes form invalid for participant

---

.gitignore
core/src/main/java/org/akaza/openclinica/dao/submit/ListSubjectFilter.java
web/src/main/java/org/akaza/openclinica/control/admin/ListSubjectTableFactory.java

The subject table in Tasks->Administer->Subjects has its filter stopped working.

OC-2183 Bugfix, filters at Administer Subjects

---

web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/ItemProcessor.java

OpenClinica adding incorrect audit entries for repeating groups
submitted through a Participant Form

OC-7115 OpenClinica adding incorrect audit entries for repeating groups submitted through a Participant Form

---

web/src/main/java/org/akaza/openclinica/control/submit/CreateDiscrepancyNoteServlet.java

No properties for new items after CRF version migration

OC-7119 No properties for new items after CRF version migration

---

core/src/main/java/org/akaza/openclinica/i18n/util/ResourceBundleProvider.java
pom.xml
web/src/main/java/org/akaza/openclinica/controller/ReportController.java

REST Endpoint that produces OC specific configuration information

OC-7160 REST Endpoint that produces OC specific configuration information

---

core/src/main/java/org/akaza/openclinica/dao/managestudy/StudySubjectDAO.java
pom.xml
web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudySubjectServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectAuditLogServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/AddNewSubjectServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/CreateNewStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/EnterDataForStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/resources/esapi/ESAPI.properties
web/src/main/resources/esapi/validation.properties
web/src/main/resources/org/akaza/openclinica/i18n/exceptions.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudySubject.jsp
ws/src/main/resources/org/akaza/openclinica/i18n/exceptions.properties
ws/src/main/webapp/WEB-INF/jsp/managestudy/updateStudySubject.jsp

OC-7271 Fix issue with AddNewSubject page
https://jira.openclinica.com/browse/OC-7271
This branch uses the OWASP library, so PR #588 no longer needed.

OC-7271 (using owasp library)

---

web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaXmlGenerator.java

https://jira.openclinica.com/browse/OC-7271

DEVBUG: Anonymous offline form submission not working

---

web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/ItemProcessor.java

DEVBUG: File Upload not working with PForms

OC-7219  DEVBUG: File Upload not working with PForms 

---

web/src/main/java/org/akaza/openclinica/controller/SystemController.java

https://jira.openclinica.com/browse/OC-7313

7313 FacName is not included in JSON output from healthcheck API

---

web/src/main/java/org/akaza/openclinica/controller/SystemController.java

https://jira.openclinica.com/browse/OC-7319

7319 RoleName should not be exposed by API

---

core/src/main/java/org/akaza/openclinica/dao/submit/EventCRFDAO.java
core/src/main/resources/properties/eventcrf_dao.xml
pom.xml
web/src/main/java/org/akaza/openclinica/controller/CRFVersionMigrationBatchController.java
web/src/main/resources/org/akaza/openclinica/applicationContext-security.xml

Run batch CRF version migration as an api

OC-7343 Run batch CRF version migration as an api

---

web/src/main/java/org/akaza/openclinica/controller/SystemController.java
web/src/main/resources/org/akaza/openclinica/applicationContext-security.xml

OC-7351 Secure IQ/OQ endpoints

---

core/src/main/resources/properties/subject_dao.xml

The original pull request was merged into the Master branch. Making this change in 3.12 now.
OC-7358

The original pull request was merged into the Master branch. Making this change in 3.12 now. OC-7358

---

core/src/main/resources/migration/3.12/2016-08-12-OC-5891.xml
core/src/main/resources/migration/3.12/release.xml
core/src/main/resources/migration/master.xml

OpenClinica silently fails to create a DN when the rule message is greater than 255 characters long

Oc 5891 OpenClinica silently fails to create a DN when the rule message is greater than 255 characters long

---

web/src/main/resources/extract.properties

Capitalize the word "data" and "syntax" in "SPSS data and syntax" so it reads "SPSS Data and Syntax"?

Oc 7200 Capitalize the word "data" and "syntax" in "SPSS data and syntax" so it reads "SPSS Data and Syntax"?

---

web/src/main/java/org/akaza/openclinica/control/form/Validator.java
web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudySubjectServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/AddNewSubjectServlet.java
web/src/main/resources/org/akaza/openclinica/i18n/exceptions.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudySubject.jsp

Fix issue with AddNewSubject page
Added validation at subject create and update time not to allow saving
html less than or greater than elements

OC-7271 Fix issue with AddNewSubject page

---

core/src/main/java/org/akaza/openclinica/dao/managestudy/StudySubjectDAO.java

Added missing import to studySubjectDAO file which was causing Jenkin fail

OC-3.12 Added missing import to studySubjectDAO file

---

web/src/main/java/org/akaza/openclinica/controller/BatchCRFMigrationController.java

Devbug: Batch CRF v. Migration API with Removed Sites/Events

OC-7397 Devbug: Batch CRF v. Migration API with Removed Sites/Events

---

web/src/main/java/org/akaza/openclinica/controller/SystemController.java

Create Documentation for HealthCheck APIs

OC-7368 Create Documentation for HealthCheck APIs

---

core/src/main/java/org/akaza/openclinica/service/rule/expression/ExpressionService.java

Devbug: Rule Upload/Insert Action

OC-7401 Devbug: Rule Upload/Insert Action

---

web/src/main/java/org/akaza/openclinica/controller/BatchCRFMigrationController.java

Devbug: Batch CRF v. Migration API with Removed/Archived CRFs
added formatting

OC-7406 Devbug: Batch CRF v. Migration API with Removed/Archived CRFs

---

web/src/main/resources/org/akaza/openclinica/i18n/words.properties

Correct instructions in CRF Version Migration UIs

OC-7425 Correct instructions in CRF Version Migration UIs

---

web/src/main/java/org/akaza/openclinica/control/admin/ListSubjectTableFactory.java

Administer Subjects slow page load
resolved system crushing when filetered by owner

OC-7358 Administer Subjects slow page load

---

web/src/main/java/org/akaza/openclinica/controller/SystemController.java

DEVBUG: API for filesystem is incorrect in API documentation

OC-7430 DEVBUG: API for filesystem is incorrect in API documentation

---

core/src/main/java/org/akaza/openclinica/domain/AbstractAuditableMutableDomainObject.java
core/src/main/java/org/akaza/openclinica/domain/AbstractMutableDomainObject.java

OC-7489: DEVBUG: Uploading the the same notificationAction rule x times causes system to send x emails 

---

ws/pom.xml

Have artifacts show up again in the target forlder for ws module

OC-7542: Have artifacts show up again in the target forlder for ws module

---

core/pom.xml
core/src/main/java/org/akaza/openclinica/dao/hibernate/DiscrepancyNoteDao.java
core/src/main/java/org/akaza/openclinica/dao/hibernate/ItemDataDao.java
core/src/main/java/org/akaza/openclinica/domain/datamap/ItemGroup.java
core/src/main/java/org/akaza/openclinica/domain/xform/XformParserHelper.java
core/src/main/java/org/akaza/openclinica/service/crfdata/Crf.java
core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/Version.java
core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java
core/src/main/resources/migration/4.0/2017-01-04-OC-7408.xml
core/src/main/resources/migration/4.0/release.xml
pom.xml
web/src/main/java/org/akaza/openclinica/control/admin/CreateXformCRFVersionServlet.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
web/src/main/java/org/akaza/openclinica/web/pform/formlist/ReasonForChangeFormDecorator.java
web/src/main/java/org/akaza/openclinica/web/pform/formlist/XFormObject.java

Field Submission and Edit Mode functionalities implementation

Oc 7408 Field Submission and Edit Mode functionalities implementation

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoAPI.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoEditURLRequest.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoURLResponse.java

Mark CRFs complete AC1 thru AC4.

OC-7693 Mark CRFs complete AC1 thru AC4.

---

core/src/main/java/org/akaza/openclinica/core/form/xform/QueryBean.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp

Administrative Edit Data in Enketo Forms.

OC-7712 Administrative Edit Data in Enketo Forms.

---

core/src/main/java/org/akaza/openclinica/bean/managestudy/EventDefinitionCrfTagBean.java
core/src/main/java/org/akaza/openclinica/dao/core/SQLFactory.java
core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
core/src/main/java/org/akaza/openclinica/dao/managestudy/EventDefinitionCrfTagDAO.java
core/src/main/resources/properties/event_definition_crf_tag_dao.xml

Fix a dev bug issue with Offline Configuration Parameter in Protocol
Metadata

OC-7794 As a protocol manager I want to get the protocol's metadata

---

web/src/main/java/org/akaza/openclinica/control/admin/CreateXformCRFVersionServlet.java

OC-7841 Refactor ODM

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/bean/extract/odm/MetaDataReportBean.java

OC-7847 minor changes to ODM report

---

core/src/main/java/org/akaza/openclinica/domain/datamap/ItemData.java
core/src/main/resources/migration/4.0/2017-02-13-OC-7861.xml
core/src/main/resources/migration/4.0/release.xml
web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionService.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/SubmissionContainer.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/AbstractItemProcessor.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/ItemProcessor.java

Capture Enketo instance_id when saving

OC-7861 Capture Enketo instance_id when saving

---

core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java

Rest API for form metadata needs to be updated for new ODM structure

OC-7862 Rest API for form metadata needs to be updated for new ODM structure

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java

OC-7863 Compilation Issue

---

core/src/main/resources/migration/4.0/2017-02-13-OC-7861.xml
web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp

Event CRF Administrative Edit URL is not working in Chrome or IE
Also, fix for one of Jenkin's test fail

OC-7782 Event CRF Administrative Edit URL is not working in Chrome or IE

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoAPI.java
core/src/main/java/org/akaza/openclinica/service/pmanage/Submission.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
web/src/main/java/org/akaza/openclinica/controller/EditFormController.java
web/src/main/java/org/akaza/openclinica/controller/OdmController.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/PformSubmissionNotificationService.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
web/src/main/java/org/akaza/openclinica/web/pform/PFormCache.java

Modify participate to work with form layouts, form layout versions &
vanilla xform definitions

OC-7864 Modify participate to work with form layouts, form layout versions & vanilla xform definitions

---

core/src/main/java/org/akaza/openclinica/service/pmanage/ParticipantPortalRegistrar.java

@sdibona please review and make changes as appropriate. This is why notification actions were not actually sending an email.

OC-7897: DEVBUG Notification action

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/VersioningMapDao.java
core/src/main/java/org/akaza/openclinica/service/crfdata/CrfMetaDataObject.java
core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

OCForm saves a duplicate of a Query if user clicks away from Form URL during saving

Oc 7874 OCForm saves a duplicate of a Query if user clicks away from Form URL during saving

---

web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java

OCForm saves a duplicate of a Query if user clicks away from Form URL
during saving

OC-7874 code review feedback changes

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java

Query Widget losing Type column and Time when re-opening form

OC-7913 Query Widget losing Type column and Time when re-opening form

---

web/src/main/java/org/akaza/openclinica/control/managestudy/RemoveStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/RestoreStudyEventServlet.java
web/src/main/webapp/WEB-INF/jsp/managestudy/removeStudyEvent.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/restoreStudyEvent.jsp

Fix study attr in /RestoreStudyEvent & /RemoveStudyEvent
(cherry picked from commit 3031028)

3.13 oc 7567

---

core/src/main/java/org/akaza/openclinica/dao/login/UserAccountDAO.java
core/src/main/resources/properties/useraccount_dao.xml
web/src/main/java/org/akaza/openclinica/control/managestudy/ListStudyUserServlet.java
web/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/showUserInStudyRow.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewUserInStudy.jsp

Fix i18n for @sdibona comments

3.13 oc 7568

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
web/src/main/java/org/akaza/openclinica/web/pform/formlist/QueryFormDecorator.java

Add Automatic Queries when the form is closed

OC-7919 Add Automatic Queries when the form is closed

---

web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/EventProcessor.java

Completed forms remain completed when data is modified

OC-7939 Completed forms remain completed when data is modified

---

web/src/main/java/org/akaza/openclinica/control/admin/CreateXformCRFVersionServlet.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/admin/createXformCRFVersion.jsp

OC-7938 Validate XForm on upload

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java

OCForm is not rendering saved selections in a checkbox when form is
closed and re-opened

OC-7943 OCForm is not rendering saved selections in a checkbox when form is closed and re-opened

---

core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java

Calculated read-only fields can have queries

OC-7888 Calculated read-only fields can have queries

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java

Field History on form shows items in reverse chronological order

OC-7953 Field History on form shows items in reverse chronological order

---

web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java

OCForm not assigning Auto-generated Query to data entry user

OC-7968 OCForm not assigning Auto-generated Query to data entry user 

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/VersioningMapDao.java
core/src/main/java/org/akaza/openclinica/dao/submit/EventCRFDAO.java
core/src/main/java/org/akaza/openclinica/dao/submit/ItemDAO.java
core/src/main/resources/properties/eventcrf_dao.xml
core/src/main/resources/properties/item_dao.xml
web/src/main/java/org/akaza/openclinica/control/submit/VariableSubstitutionHelper.java
web/src/main/java/org/akaza/openclinica/controller/ChangeCRFVersionController.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/chooseCRFVersion.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/confirmCRFVersionChange.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp

Versions of XForm CRF in Reassign CRF Version page not populating in the
drop-down list

OC-7971 Versions of XForm CRF in Reassign CRF Version page not populating in the drop-down list

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/UserAccountDao.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
web/src/main/java/org/akaza/openclinica/web/pform/PFormCache.java

Populate user lists for Enketo Discrepancy Notes

OC-7282 Populate user lists for Enketo Discrepancy Notes

---

web/src/main/java/org/akaza/openclinica/control/admin/ViewCRFServlet.java

View CRF Details Page needs to be updated to reflect change from Version
to FormLayout concept

OC-7974 View CRF Details Page needs to be updated to reflect change from Version to FormLayout concept

---

core/src/main/java/org/akaza/openclinica/domain/xform/XformGroup.java
core/src/main/java/org/akaza/openclinica/domain/xform/XformParserHelper.java
core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/admin/createXformCRFVersion.jsp

OC-7671 CRF business rules

---

web/src/main/java/org/akaza/openclinica/control/admin/CreateXformCRFVersionServlet.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

Form upload shows many warning messages if they are any error messages

OC-8042 Form upload shows many warning messages if they are any error messages

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties

Default User for Query Assignee List

OC-7307 Default User for Query Assignee List

---

pom.xml

Updated pom to point to https://openclinica.jfrog.io/openclinica

Updating pom for new Artifactory

---

core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java
web/src/main/java/org/akaza/openclinica/control/admin/CreateXformCRFVersionServlet.java

FormOID/Form Name issue at Upload in Form Manager

OC-8122 FormOID/Form Name issue at Upload in Form Manager

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java

Non-alphanumeric characters not saved in repeating groups in XForms

OC-8101 Non-alphanumeric characters not saved in repeating groups in XForms

---

core/src/main/java/org/akaza/openclinica/domain/xform/XformItem.java

OC-8097 Replace existing form version

---

web/src/main/java/org/akaza/openclinica/control/admin/CreateXformCRFVersionServlet.java

Oops Error occurs when attempting to upload a new XForm version

OC-8127 Oops Error occurs when attempting to upload a new XForm version

---

core/src/main/resources/migration/3.7/2015-08-18-OC-2886.xml
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectAuditLogServlet.java
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectAudit.jsp

Oc 8071 CRF Version in Audit Logs

---

web/src/main/java/org/akaza/openclinica/controller/DiscrepancyNoteController.java

OC-8115 Disc. Note API at Event Level

---

core/src/main/java/org/akaza/openclinica/bean/submit/ItemGroupBean.java
core/src/main/java/org/akaza/openclinica/dao/submit/ItemGroupDAO.java
core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoAPI.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoEditURLRequest.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoURLResponse.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/PFormCacheSubjectContextEntry.java
web/src/main/java/org/akaza/openclinica/control/admin/CreateXformCRFVersionServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
web/src/main/webapp/WEB-INF/jsp/submit/enketoFormServlet.jsp

View within Record opens form directly at Query

OC-7999 View within Record opens form directly at Query

---

core/src/main/resources/migration/3.14/2017-05-23-OC-8124.xml
core/src/main/resources/migration/3.14/release.xml
core/src/main/resources/migration/master.xml

OC-8124: SUPPORT: To debug University of Michigan production instance performance issue

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java

SDV Status not reset on data change

OC-8157  SDV Status not reset on data change

---

core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java

Reverts OpenClinica/OpenClinica#675

Revert "OC-7417a Dev Bug crf version creation in web"

---

web/src/main/java/org/akaza/openclinica/controller/ODMClinicalDataController.java

REST API call for clinical data returning 500 error

OC-8164 REST API call for clinical data returning 500 error

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java

View Within Record opens form in the same window

OC-8188 View Within Record opens form in the same window

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ViewEventDefinitionServlet.java

OCB not populating correct formLayoutOID (version) on View Event
Defintion Page

OC-8187 OCB not populating correct formLayoutOID (version) on View Event Defintion Page

---

core/src/main/java/org/akaza/openclinica/logic/importdata/ImportDataHelper.java
core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java
core/src/main/resources/properties/form_layout_dao.xml
web/src/main/java/org/akaza/openclinica/control/submit/TableOfContentsServlet.java

Oops Error when opening a form in nightly

OC-8193 Oops Error when opening a form in nightly

---

ws/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFDataService.java

Oops Error after REST call to subject data after SOAP data import

OC-8052 Oops Error after REST call to subject data after SOAP data import

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java

View within Record for hidden/deleted fields
Reverted some code to allow forwarding deleted repeating rows queries to
Enketo page.

OC-8165 View within Record for hidden/deleted fields

---

core/src/main/resources/migration/4.0/2017-06-19-OC-8195.xml
core/src/main/resources/migration/4.0/release.xml

Update Notes & Discrepancies View tables in database to use form layout
version

OC-8195 Update Notes & Discrepancies View tables in database to use form layout version

---

web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

OC-8228 Support Image Map fields

---

web/src/main/java/org/akaza/openclinica/control/admin/CreateXformCRFVersionServlet.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties

Error message handling when NAMESPACE column is missing in XLS form

Oc 8256 Error message handling when NAMESPACE column is missing in XLS form

---

web/src/main/resources/org/akaza/openclinica/i18n/words.properties

Upload error if there is not exactly 1 Excel file

OC-8249 Upload error if there is not exactly 1 Excel file

---

nano.save
web/src/main/java/org/akaza/openclinica/control/admin/AuditUserLoginTableFactory.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/view/StudyInfoPanel.java
web/src/main/webapp/WEB-INF/jsp/admin/auditUserActivity.jsp
web/src/main/webapp/WEB-INF/jsp/admin/showCRFRow.jsp
web/src/main/webapp/WEB-INF/jsp/admin/viewFullStudy.jsp
web/src/main/webapp/WEB-INF/jsp/extract/createDatasetStep2.jsp
web/src/main/webapp/WEB-INF/jsp/include/createDatasetSideInfo.jsp
web/src/main/webapp/WEB-INF/jsp/include/eventOverviewSideInfo.jsp
web/src/main/webapp/WEB-INF/jsp/login/login.jsp
web/src/main/webapp/WEB-INF/jsp/login/requestPasswordPop.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/setUserRoleInStudy.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/showEventByDefinitionRow.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
web/src/main/webapp/WEB-INF/jsp/menu.jsp
web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
web/src/main/webapp/includes/css/oc2017_styles.css
web/src/main/webapp/includes/scss/oc2017_styles.scss

https://jira.openclinica.com/browse/OC-8179 (update ui header style)
https://jira.openclinica.com/browse/OC-8180 (update table style)
https://jira.openclinica.com/browse/OC-8181 (update icon style)

Reskinning feedback

---

web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/admin/listuseraccounts.jsp
web/src/main/webapp/WEB-INF/jsp/admin/viewAllJobs.jsp
web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp

https://jira.openclinica.com/browse/OC-8261

OC-8261 Move Bridge Admin functions

---

web/src/main/java/org/akaza/openclinica/control/submit/CreateNewStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableToolbar.java
web/src/main/webapp/WEB-INF/jsp/include/eventOverviewSideInfo.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/createStudy1.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/createStudy2.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/createStudy3.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/createStudy4.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/createStudy5.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/createStudy6.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/createStudy7.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/createStudy8.jsp
web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp

https://jira.openclinica.com/browse/OC-8263

OC-8263 Change Add New Subject link destination for Subject Matrix

---

web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/resources/org/akaza/openclinica/i18n/workflow.properties
web/src/main/webapp/WEB-INF/jsp/include/viewRuleAssignmentSideInfo.jsp
web/src/main/webapp/WEB-INF/jsp/submit/listRuleSets2.jsp
web/src/main/webapp/WEB-INF/jsp/submit/viewRules.jsp

https://jira.openclinica.com/browse/OC-8265

OC-8265 Manage Rules page has Add Rules link

---

core/src/main/java/org/akaza/openclinica/domain/xform/dto/Form.java
core/src/main/java/org/akaza/openclinica/domain/xform/dto/Input.java
core/src/main/java/org/akaza/openclinica/domain/xform/dto/Instance.java
core/src/main/java/org/akaza/openclinica/domain/xform/dto/Root.java
core/src/main/java/org/akaza/openclinica/domain/xform/dto/RootItem.java
core/src/main/java/org/akaza/openclinica/domain/xform/dto/Upload.java
core/src/main/java/org/akaza/openclinica/domain/xform/dto/UserControl.java
core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoAPI.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoURLResponse.java
core/src/main/resources/properties/xformMapping.xml
web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

View Query opens Query Widget the selected Query for cascading select
field

OC-8259 View Query opens Query Widget the selected Query for cascading select field

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoAPI.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoURLResponse.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/PFormCacheSubjectContextEntry.java
web/src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
web/src/main/java/org/akaza/openclinica/controller/AnonymousFormControllerV2.java
web/src/main/java/org/akaza/openclinica/controller/EditFormController.java
web/src/main/java/org/akaza/openclinica/controller/OdmController.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
web/src/main/java/org/akaza/openclinica/web/pform/PFormCache.java
web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp

OC-7655 Form renders in View Mode.
OC-8238 View Query opens Query Widget editable but field read-only

Oc 8268 Close Query from View Query page

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java

Loading Error message when opening View Query

OC-8286 Loading Error message when opening View Query

---

web/src/main/java/org/akaza/openclinica/control/admin/ListCRFServlet.java
web/src/main/java/org/akaza/openclinica/control/admin/ViewCRFServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
web/src/main/webapp/WEB-INF/jsp/admin/showCRFRow.jsp
web/src/main/webapp/WEB-INF/jsp/admin/viewCRF.jsp

Existing Form renders in View Mode.

OC-7655 Existing Form renders in View Mode.

---

web/src/main/java/org/akaza/openclinica/config/AppConfig.java
web/src/main/java/org/akaza/openclinica/controller/LogoutController.java
web/src/main/resources/sso.properties
web/src/main/webapp/WEB-INF/jsp/home.jsp
web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
web/src/main/webapp/WEB-INF/jsp/login/logout.jsp
ws/src/main/java/org/akaza/openclinica/ws/StudySubjectEndpoint.java
ws/src/main/resources/auth0.properties

- Fixed the Logout

---

core/src/main/resources/migration/3.14/2017-07-27-OC-7877.xml
core/src/main/resources/migration/3.14/release.xml

OC-7877: Duplicates in the study event definition page

---

web/src/main/java/org/akaza/openclinica/control/submit/ParticipantFormServlet.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
web/src/main/webapp/WEB-INF/jsp/admin/showCRFRow.jsp

OC forms user previews form from Manage CRF page

OC-8291 OC forms user previews form from Manage CRF page

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties

View Query link for From Query opens Enketo with "View Query" as Form
Title

OC-8301 View Query link for From Query opens Enketo with "View Query" as Form Title

---

core/src/main/resources/migration/tenant/db.xml

- Removed is_stateful column that was not needed

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
web/src/main/resources/org/akaza/openclinica/i18n/notes.properties
web/src/main/resources/org/akaza/openclinica/i18n/workflow.properties
web/src/main/webapp/WEB-INF/jsp/admin/viewCRF.jsp
web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewCRFVersion.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewNotes.jsp

https://github.com/OpenClinica/requirements/issues/32

Reskinning feedback from Paul

---

core/src/main/java/org/akaza/openclinica/bean/login/SiteDTO.java
core/src/main/java/org/akaza/openclinica/dao/managestudy/StudyDAO.java
web/src/main/java/org/akaza/openclinica/controller/StudyController.java
web/src/main/java/org/akaza/openclinica/service/LiquibaseOnDemandServiceImpl.java

- site related changes

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/view/StudyInfoPanel.java
web/src/main/webapp/WEB-INF/jsp/admin/showImportJobRow.jsp
web/src/main/webapp/WEB-INF/jsp/admin/showJobRow.jsp
web/src/main/webapp/WEB-INF/jsp/admin/showSubjectRow.jsp
web/src/main/webapp/WEB-INF/jsp/admin/viewSubject.jsp
web/src/main/webapp/WEB-INF/jsp/extract/applyFilterRow.jsp
web/src/main/webapp/WEB-INF/jsp/extract/createDatasetStep3.jsp
web/src/main/webapp/WEB-INF/jsp/extract/createDatasetStep4.jsp
web/src/main/webapp/WEB-INF/jsp/extract/selectCRFAttributes.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewNotes.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp

https://github.com/OpenClinica/requirements/issues/32
also:
https://docs.google.com/document/d/1R-eFvIhUuZGcopE2FhM0TaeckjrdBb-CBhyrxp_jlIM/edit?ts=5993b833

Bridge reskin, issue #32

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java

View Query link for From Query opens Enketo with Query info

OC-8302 View Query link for From Query opens Enketo with Query info

---

core/src/main/java/org/akaza/openclinica/bean/core/ResolutionStatus.java
web/src/main/java/org/akaza/openclinica/control/submit/CreateNewStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
web/src/main/webapp/WEB-INF/jsp/extract/createDatasetConfirmMetadata.jsp
web/src/main/webapp/WEB-INF/jsp/extract/selectEventAttribute.jsp
web/src/main/webapp/WEB-INF/jsp/extract/selectSubAttribute.jsp
web/src/main/webapp/WEB-INF/jsp/include/createDatasetSide.jsp
web/src/main/webapp/WEB-INF/jsp/include/createDatasetSideInfo.jsp
web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
web/src/main/webapp/WEB-INF/jsp/login/changeStudy.jsp
web/src/main/webapp/WEB-INF/jsp/submit/createNewStudyEvent.jsp
web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
web/src/main/webapp/includes/styles.css

https://github.com/OpenClinica/requirements/issues/32
https://docs.google.com/document/d/1R-eFvIhUuZGcopE2FhM0TaeckjrdBb-CBhyrxp_jlIM/edit?ts=5993b833

Issue #32 & Bridge UX - Take 2

---

web/src/main/java/org/akaza/openclinica/control/login/ChangeStudyServlet.java
web/src/main/java/org/akaza/openclinica/controller/StudyController.java

- removed showSecondaryId for the study settings

- Fixed the bug to show study name for a site

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
web/src/main/webapp/WEB-INF/jsp/extract/createDatasetConfirmMetadata.jsp
web/src/main/webapp/WEB-INF/jsp/include/showDateTimeInput.jsp
web/src/main/webapp/WEB-INF/jsp/include/showTable.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/submit/addNewSubject.jsp
web/src/main/webapp/WEB-INF/jsp/submit/createNewStudyEvent.jsp
web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp

Bridge UX - Take 2: https://docs.google.com/document/d/1R-eFvIhUuZGcopE2FhM0TaeckjrdBb-CBhyrxp_jlIM/edit?ts=5993b833
issue #32: https://github.com/OpenClinica/requirements/issues/32

Bridge UX - Take 2 & github issue #32

---

web/src/main/java/org/akaza/openclinica/control/submit/ParticipantFormServlet.java

Preview CRF button does not open a preview of the form

OC-8325 Preview CRF button does not open a preview of the form

---

web/src/main/java/org/akaza/openclinica/view/StudyInfoPanel.java
web/src/main/webapp/WEB-INF/jsp/include/showDateTimeInput.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectAudit.jsp
web/src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpress.jsp
web/src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpressNew.jsp
web/src/main/webapp/WEB-INF/jsp/submit/createNewStudyEvent.jsp
ws/src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpressNew.jsp

https://docs.google.com/document/d/1R-eFvIhUuZGcopE2FhM0TaeckjrdBb-CBhyrxp_jlIM/edit?ts=5993b833

Bridge UX - Take 2

---

web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java

Unable to Update query in View Query mode from Queries table when the
study is Frozen

OC-8333 Unable to Update query in View Query mode from Queries table when the study is Frozen

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/SchemaServiceDao.java
web/src/main/java/org/akaza/openclinica/controller/StudyController.java
web/src/main/java/org/akaza/openclinica/service/StudyBuildServiceImpl.java

- remove schemaPrefix property from datainfo.properties

- Name the schema from study oid and env type

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/StudyUserRoleDao.java
pom.xml
web/src/main/java/org/akaza/openclinica/control/login/ChangeStudyServlet.java
web/src/main/java/org/akaza/openclinica/service/StudyBuildServiceImpl.java

- Prepend "s_" to the schema name
- Update site roles

- Use the latest Postgres jar

---

core/src/main/java/org/akaza/openclinica/service/EventService.java
core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java
core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/EventProcessor.java

Publish an archived event
Publish an archived crf
Publish an archived crf versions

Oc 8320 Publish an archived event

---

web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java

Error when deleting repeating group

Oc 8335 Error when deleting repeating group

---

core/src/main/java/org/akaza/openclinica/dao/submit/EventCRFDAO.java
core/src/main/java/org/akaza/openclinica/service/EventService.java
core/src/main/resources/properties/eventcrf_dao.xml

OC-8335 Archiving form version

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/StudyUserRoleDao.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
pom.xml
web/src/main/java/org/akaza/openclinica/service/StudyBuildServiceImpl.java
web/src/main/resources/datainfo.properties
ws/pom.xml

- Added methods to get study roles with user and study combo

- Site role deletion

---

web/src/main/java/org/akaza/openclinica/control/managestudy/RestoreStudyEventServlet.java

Restoring Study Event changes an archived existing form into availabe
for data entry..

OC-8337 Restoring Study Event changes an archived existing form into availabe for data entry..

---

core/src/main/java/org/akaza/openclinica/bean/core/ResolutionStatus.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectServlet.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/include/eventOverviewSideInfo.jsp
web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
web/src/main/webapp/WEB-INF/jsp/include/studySideInfo.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/submit/addDiscrepancyNote.jsp
web/src/main/webapp/includes/font-awesome-4.7.0/css/font-awesome.css

https://github.com/OpenClinica/requirements/issues/32#issuecomment-322854911

Reskinning feedback (issue #32) -- cosmetic changes

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/FormLayoutMediaDao.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

Image preview not rendered in OCForm when a CRF with an uploaded image
is re-opened by user

OC-8339 Image preview not rendered in OCForm when a CRF with an uploaded image is re-opened by user

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/multitenant/DataSourceBasedMultiTenantConnectionProviderImpl.java
core/src/main/java/org/akaza/openclinica/dao/hibernate/multitenant/MultiTenantFilter.java
core/src/main/java/org/akaza/openclinica/web/filter/ApiSecurityFilter.java
web/src/main/webapp/WEB-INF/web.xml
ws/src/main/java/org/akaza/openclinica/ws/SpringPlainTextPasswordValidationCallbackHandler.java

- More debug for WS call failure

---

web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp

Blank page error when attempting to open a CRF from the Event Page

OC-8347 Blank page error when attempting to open a CRF from the Event Page

---

web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/siteList.jsp
web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp

https://github.com/OpenClinica/requirements/issues/32#issuecomment-322854911

Isssue #32 cosmetic changes

---

web/src/main/webapp/includes/css/icomoon-style.css
web/src/main/webapp/includes/styles.css

Revert styles

---

web/src/main/java/org/akaza/openclinica/view/StudyInfoPanel.java
web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp
web/src/main/webapp/includes/css/icomoon-style.css
web/src/main/webapp/includes/styles.css

Adi's progress of today on:
https://github.com/OpenClinica/requirements/issues/32#issuecomment-322854911

Requirements #32 -- cosmetic changes

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/ResponseSetService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EditUrlObject.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoAPI.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/ParticipantFormServlet.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

Also, resolves the issue with loading the original version in Test when the form version is overwritten.
Latest form version layout definition appears in the extract for each
element

OC-8099 Latest form version layout definition appears in the extract for each element

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

Old form definition is loaded in Enketo after the version is overwritten
and published

OC-8372 Old form definition is loaded in Enketo after the version is overwritten and published

---

core/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/java/org/akaza/openclinica/controller/SDVController.java
web/src/main/java/org/akaza/openclinica/web/table/sdv/SDVUtil.java
web/src/main/resources/org/akaza/openclinica/i18n/format.properties
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/admin/viewFullStudy.jsp
web/src/main/webapp/WEB-INF/jsp/admin/viewImportJobs.jsp
web/src/main/webapp/WEB-INF/jsp/extract/createDatasetStep2.jsp
web/src/main/webapp/WEB-INF/jsp/extract/createDatasetStep3.jsp
web/src/main/webapp/WEB-INF/jsp/extract/createDatasetStep4.jsp
web/src/main/webapp/WEB-INF/jsp/include/submitDataSide.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/siteList.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudyEvents.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
web/src/main/webapp/includes/css/oc2017_styles.css
web/src/main/webapp/includes/styles.css

https://docs.google.com/spreadsheets/d/1KN_vTvIj7EwuPji6A9dNe999RfiWEyU45mlRwicLAl4

OC4 Copy Edits

---

web/src/main/resources/org/akaza/openclinica/i18n/terms.properties
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/extract/createDatasetStep2.jsp
web/src/main/webapp/WEB-INF/jsp/extract/exportDatasets.jsp
web/src/main/webapp/WEB-INF/jsp/extract/selectCRFAttributes.jsp
web/src/main/webapp/WEB-INF/jsp/extract/selectEventAttribute.jsp
web/src/main/webapp/WEB-INF/jsp/extract/selectSubAttribute.jsp
web/src/main/webapp/WEB-INF/jsp/extract/viewSelected.jsp
web/src/main/webapp/WEB-INF/jsp/include/showTable.jsp
web/src/main/webapp/includes/styles.css

https://docs.google.com/spreadsheets/d/1KN_vTvIj7EwuPji6A9dNe999RfiWEyU45mlRwicLAl4

OC4 Copy Edits (Sept 20 progress)

---

core/src/main/java/org/akaza/openclinica/bean/core/Utils.java
core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java
core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

For this to work properly , Forms need to be republished and picture files within forms should be re uploaded to the form.
Thanks

OC-8376 Form metadata file locations in data folder

---

core/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
web/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties
web/src/main/webapp/WEB-INF/jsp/admin/viewStudy.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/createSubStudyConfirm.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpressNew.jsp
web/src/main/webapp/WEB-INF/jsp/submit/viewDiscrepancyNote.jsp
web/src/main/webapp/includes/css/icomoon-style.css
web/src/main/webapp/includes/styles.css

https://docs.google.com/spreadsheets/d/1KN_vTvIj7EwuPji6A9dNe999RfiWEyU45mlRwicLAl4/edit#gid=0
https://docs.google.com/document/d/1Giw-P59ibTuTaryeYcLKl9XohX9LFRFVnmKjZ5Gr2OM/edit?ts=59bffd44#heading=h.4xvrlfa2uf4h

OC4 Copy Edits and Manual Testing/Bug Fixing - Misc Cosmetic Issues

---

core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java

Form metadata file locations in data folder

OC-8736 Form metadata file locations in data folder 

---

web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/webapp/WEB-INF/jsp/include/studySideInfo.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/reassignStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/studySubject/casebookGenerationForm.jsp
web/src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpressNew.jsp
web/src/main/webapp/includes/css/icomoon-style.css
web/src/main/webapp/includes/styles.css

https://docs.google.com/document/d/1Giw-P59ibTuTaryeYcLKl9XohX9LFRFVnmKjZ5Gr2OM/edit?ts=59bffd44#

Manual Testing/Bug Fixing - Misc Cosmetic Issues (Sept 22 progress)

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java

Clicking View Query in Queries Table at the Site-level generates Oops
Error

OC-8381 Clicking View Query in Queries Table at the Site-level generates Oops Error

---

core/src/main/java/org/akaza/openclinica/service/crfdata/ResponseSetService.java

Error checking for missing code labels

OC-8384 Error checking for missing code labels

---

core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java
core/src/main/java/org/akaza/openclinica/service/crfdata/ResponseSetService.java

updated error messages and got rid of "<" and ">" characters

OC-8393 updated error messages and exluded < and > characters

---

web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/deleteStudyEvent.jsp
web/src/main/webapp/WEB-INF/jsp/submit/addDiscrepancyNote.jsp
web/src/main/webapp/WEB-INF/jsp/submit/createNewStudyEvent.jsp
web/src/main/webapp/WEB-INF/jsp/submit/importRules.jsp
web/src/main/webapp/WEB-INF/jsp/submit/viewDiscrepancyNote.jsp

https://docs.google.com/document/d/1Giw-P59ibTuTaryeYcLKl9XohX9LFRFVnmKjZ5Gr2OM/edit?ts=59bffd44#

Manual Testing/Bug Fixing - Misc Cosmetic Issues (Oct 2 progress)

---

web/src/main/resources/org/akaza/openclinica/i18n/notes.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/viewEventDefinitionReadOnly.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
web/src/main/webapp/includes/styles.css

Manual Testing/Bug Fixing - Misc Cosmetic Issues (Oct 3 progress)

---

core/src/main/java/org/akaza/openclinica/logic/rulerunner/ImportDataRuleRunnerContainer.java
web/src/main/webapp/includes/styles.css

Run rules when importing data

---

web/src/main/webapp/WEB-INF/jsp/admin/viewStudy.jsp
web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateSubStudy.jsp
web/src/main/webapp/WEB-INF/jsp/submit/viewDiscrepancyNote.jsp

Manual Testing/Bug Fixing - Misc Cosmetic Issues (Oct 4 progress)

---

core/src/main/java/org/akaza/openclinica/service/CustomRuntimeException.java
core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java

Updated Error object To pass error messages at publishing time into SBS

OC-8395a Updated Error object To pass error messages at publishing time into SBS

---

web/src/main/webapp/WEB-INF/jsp/admin/viewFullStudy.jsp
web/src/main/webapp/WEB-INF/jsp/admin/viewStudy.jsp
web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp

Manual Testing/Bug Fixing - Misc Cosmetic Issues (Oct 9 progress)

---

web/src/main/webapp/WEB-INF/jsp/admin/viewCRF.jsp

Remove versions column for View CRF Details for a CRF with multiple versions

Remove versions column for View CRF Details for a CRF with multiple versions

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/ParticipantFormServlet.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

Queries - Assign To User List Incorrectly Populated

OC-8411 Queries - Assign To User List Incorrectly Populated

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/view/StudyInfoPanel.java
web/src/main/resources/org/akaza/openclinica/i18n/notes.properties
web/src/main/webapp/WEB-INF/jsp/include/home-header.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewSite.jsp
web/src/main/webapp/WEB-INF/jsp/menu.jsp
web/src/main/webapp/WEB-INF/jsp/submit/addDiscrepancyNoteSaveDone.jsp
web/src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpressNew.jsp

Manual Testing/Bug Fixing - Misc Cosmetic Issues (Oct 10 progress)

---

web/src/main/webapp/WEB-INF/jsp/admin/showCRFRow.jsp
web/src/main/webapp/WEB-INF/jsp/admin/studyAuditLog.jsp
web/src/main/webapp/WEB-INF/jsp/include/extract-header.jsp
web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/findSubjects.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewNotes.jsp
web/src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpressNew.jsp

- The Favicon needs to be updated to the OC Logo and the tab title needs to be updated to “OpenClinica” (View link for a form version from Tasks > Monitor and Manage Data > CRFs)
Using preview servlet(take a look at the url [&originatingPage=ListCRF%3Fmodule%3Dmanage&mode=view] the preview comes from ListCRF)

Preview an Enketo form (from Study Designer or Bridge)

---

web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/EnterDataForStudyEventServlet.java

Event-level query status carries over to other events

OC-8418 Event-level query status carries over to other events

---

web/src/main/webapp/WEB-INF/jsp/include/home-header.jsp

Remove wrong modal window showing locked status

Remove wrong modal window showing locked status

---

web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/webapp/WEB-INF/jsp/include/managestudy_top_pages.jsp
web/src/main/webapp/WEB-INF/jsp/menu.jsp
web/src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpressNew.jsp
web/src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp

From Adi's:
https://github.com/OpenClinica/OpenClinica/pull/1084

Manual Testing/Bug Fixing - Misc Cosmetic Issues (Oct 12 progress)

---

web/src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpressNew.jsp
web/src/main/webapp/includes/new_cal/calendar-setup.js
web/src/main/webapp/includes/new_cal/calendar.js

The calendar icons in Add New Subject, Schedule Event, etc, are not doing anything. I click them and nothing happens
I think this issue happen because duplicate element id so I try make the id more unique by adding some random number to solved this issue.

Bug on calendar 

---

core/src/main/java/org/akaza/openclinica/dao/core/CoreResources.java
core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java

OC-8373 Show Publish Failure Messages

---

web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/webapp/WEB-INF/jsp/admin/viewFullStudy.jsp
web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/findSubjects.jsp

Manual Testing/Bug Fixing - Misc Cosmetic Issues (Oct 13 progress)

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/SchemaServiceDao.java
web/src/main/java/org/akaza/openclinica/service/StudyBuildServiceImpl.java

Fixing issue with creating studies & hardcoded dependency on dbUser clinica

Fixing issue with creating studies & hardcoded dependency on dbUser

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewNotes.jsp
web/src/main/webapp/includes/global_functions_javascript.js
web/src/main/webapp/includes/styles.css

Edge/Win10 missing horizontal scrollbar to reach icons(feedback)

---

web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp

SDV page: Main subject search has 404 error

OC-8432 SDV page: Main subject search has 404 error

---

web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/submit/discrepancyNote.jsp

Subject matrix >view a subject. Expanded "Other Info" in left banner-it shows another “information” section.  When I clicked to expand the “new” information section, it disappeared. Then when I expand any other topics, they disappear. See: https://drive.google.com/a/openclinica.com/file/d/0B2y6V_16uXZXWVFnSUw2SkJzN1E/view?usp=sharing
after:
https://drive.google.com/file/d/0B_8NRNK0fZNUNWxZVzVmSWpYbHM/view?usp=sharing
Update Event-level query window is squished - needs more space between Assign to User and Email Assigned User
before:
after:

Manual Testing/Bug Fixing - Misc Cosmetic Issues (25/10/17 progress)

---

web/src/main/webapp/WEB-INF/jsp/managestudy/updateSubStudy.jsp

Enable Site-level SDV configuration in Bridge

OC-8459 Enable Site-level SDV configuration in Bridge

---

web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableToolbar.java
web/src/main/java/org/akaza/openclinica/controller/SDVController.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/viewNotesPrint.jsp

SDV Page - Enter a new form. Mark is Complete. It should now appear in the SDV list. Go to the SDV Page. The form is not shown. Click Clear Filter in the SDV table. Now the form appears in the list.  The form should have appeared right away. Please investigate why it is not appearing. Also, what is the Clear Filter link doing to make it appear?

OC Cosmetic

---

core/src/main/java/org/akaza/openclinica/core/form/xform/QueryType.java
core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java

Bridge consumes Reason for Change submitted from Enketo

OC-8491 Bridge consumes Reason for Change submitted from Enketo

---

web/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFDataService.java

OC-8494 Error with Manual Data Import

---

core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java

Publish event-form SDV configurations

OC-8482 Publish event-form SDV configurations

---

core/src/main/java/org/akaza/openclinica/bean/admin/AuditBean.java
core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/bean/odmbeans/AuditLogBean.java
core/src/main/java/org/akaza/openclinica/dao/admin/AuditDAO.java
core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
core/src/main/resources/migration/tenant/4.0-2017-11-07.xml
core/src/main/resources/migration/tenant/release.xml
core/src/main/resources/properties/audit_dao.xml
web/src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectAudit.jsp

Display signature text in audit log

OC-8488     Display signature text in audit log

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java

Change capitalization on value change text

Oc 8503     Change capitalization on value change text

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/ParticipantFormServlet.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

Display user's name for history in the current session

Oc 8504 Display user's name for history in the current session

---

web/pom.xml

Subject Casebook json format report throws Oops error page

OC-8505     Subject Casebook json format report throws Oops error page

---

core/src/main/resources/migration/tenant/functions.xml
web/src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java

Different values between HTML and XLS audit logs present after CRF
migration

OC-8515     Different values between HTML and XLS audit logs present after CRF migration

---

core/src/main/java/org/akaza/openclinica/bean/managestudy/StudyEventBean.java
core/src/main/java/org/akaza/openclinica/dao/managestudy/StudyEventDAO.java
core/src/main/resources/migration/tenant/4.0-2017-11-08-OC-8483.xml
core/src/main/resources/migration/tenant/functions.xml
core/src/main/resources/migration/tenant/release.xml
core/src/main/resources/properties/study_event_dao.xml
web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/StudySubjectProcessor.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudyEventSigned.jsp

Track the full signature in the audit log

OC-8483     Track the full signature in the audit log

---

web/src/main/webapp/WEB-INF/jsp/login/changeStudy.jsp

Change Study page - Do not show Sites that are in Design (pending) status.
before:
after:

Edit Manual Testing/Bug Fixing - Misc Cosmetic Issues (18/11/17 progress)

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/DiscrepancyNoteDao.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java

Save Queries and Reasons for Change in separate threads

OC-8522 Save Queries and Reasons for Change in separate threads

---

web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
web/src/main/webapp/includes/styles.css

The commit screenshot shows the status in a green box for a Production study. The status should be in an orange box for Production studies - it should be the same orange color used for Test studies.
before:
after:

Edit Manual Testing/Bug Fixing - Misc Cosmetic Issues (21/11/17 progress)

---

web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp

Edit icon for Complete forms is missing

OC-8555.     Edit icon for Complete forms is missing

---

web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java

View Query Within Record icon is missing

OC-8556     View Query Within Record icon is missing

---

web/src/main/java/org/akaza/openclinica/control/MainMenuServlet.java
web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectsServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectsServlet.java
web/src/main/java/org/akaza/openclinica/web/table/sdv/SDVUtil.java
web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
web/src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp

- OC-8550 Add Subject Study Event dropdown does not populate if the user is not on the Subject Matrix page

OC-Cosmetic-Master

---

web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java

Form Update Date updated by opening form in edit mode even with no
changes made

OC-8541 Form Update Date updated by opening form in edit mode even with no changes made

---

web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/signStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudyEventSigned.jsp

View and Edit icons from Signature Page (Update Study Event Page) are
opening the reset password page

OC-8541 View and Edit icons from Signature Page (Update Study Event Page) are opening the reset password page

---

web/src/main/java/org/akaza/openclinica/control/managestudy/SignStudySubjectServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java

Failed signature kicks user out to a mostly blank page

OC-8563 Failed signature kicks user out to a mostly blank page

---

web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudyEventSigned.jsp

View and Edit icons from Signature Page (Update Study Event Page) are
opening the reset password page

OC-8551 View and Edit icons from Signature Page (Update Study Event Page) are opening the reset password page

---

core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java
web/src/main/java/org/akaza/openclinica/controller/OdmImportController.java
web/src/main/java/org/akaza/openclinica/controller/StudyController.java
web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
web/src/main/webapp/includes/sessionTimeout.js

- Added code for CrossStorage
- Added code for status change access for DataMonitor

- Changes for publish... removed redundant code

---

core/src/main/java/org/akaza/openclinica/service/DiscrepancyNoteUtil.java
web/src/main/webapp/WEB-INF/jsp/managestudy/signStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudyEventSigned.jsp

Signature page updated the closed query color to black.
Also added Closed-Modified column for both Subject and Event Sign pages.

OC-8551 Signature page updates

---

core/src/main/java/org/akaza/openclinica/dao/managestudy/DiscrepancyNoteDAO.java
core/src/main/java/org/akaza/openclinica/service/DiscrepancyNoteUtil.java
core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
core/src/main/resources/properties/discrepancy_note_dao.xml
web/src/main/java/org/akaza/openclinica/control/managestudy/SignStudySubjectServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
web/src/main/webapp/WEB-INF/jsp/managestudy/signStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudyEventSigned.jsp

Show count of queries by form and status on Signature Page

OC-8565 Show count of queries by form and status on Signature Page

---

web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java

reverting     Form Update Date updated by opening form using
repeat_count in edit mode even with no changes made

OC-8541  Form Update Date updated by opening form using repeat_count in edit mode even with no changes made

---

web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
web/src/main/webapp/WEB-INF/jsp/extract/showDatasetRow.jsp
web/src/main/webapp/WEB-INF/jsp/home.jsp
web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
web/src/main/webapp/includes/jmesa/jquery-migrate-1.1.1.js
web/src/main/webapp/includes/sessionTimeout.js
web/src/main/webapp/js/util.js

Errors in terminal:
1. https://drive.google.com/file/d/19lWoGFXDsD4c-psTQZ7i2PubHp5i0iwv/view?usp=sharing
2. https://drive.google.com/file/d/1BC8yDG_vcOhPmTV_19ZCSKjO-wXob4Kj/view?usp=sharing
3. https://drive.google.com/file/d/1pC1OuAGY2pkq0dw72At0ail2UIsNgS3e/view?usp=sharing
4. https://drive.google.com/file/d/1VUtFHZdSe2G4kP6dkQ-hMDU7JDXCwUd2/view?usp=sharing
5. https://drive.google.com/file/d/1tX_dHhkhvSzfr2MR4R_vThiJO45mid7C/view?usp=sharing

05-06/12/2017 progress and Edit Manual Testing/Bug Fixing - Misc Cosmetic Issues (01/12/17 progress)

---

web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudySubject.jsp

fixed view update study subject details
before:
after:

fixed view update study subject details

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java

Extract should contain full timestamp for queries and reasons for change

OC-8519 Extract should contain full timestamp for queries and reasons for change

---

web/src/main/resources/org/akaza/openclinica/i18n/workflow.properties
web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp

OC-8616 Users can access My Profile page in Runtime

---

web/src/main/java/org/akaza/openclinica/controller/AccountController.java

Incorrect user assignment list when executing the "Retrieve a user
account" API call

OC-8598 Incorrect user assignment list when executing the "Retrieve a user account" API call

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ListStudyServlet.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/studyList.jsp

Add ‘Start Study in the new OpenClinica’ feature

OC-8540 Add ‘Start Study in the new OpenClinica’ feature

---

core/src/main/java/org/akaza/openclinica/bean/admin/NewCRFBean.java
core/src/main/java/org/akaza/openclinica/dao/core/EntityDAO.java
core/src/main/java/org/akaza/openclinica/dao/hibernate/EventDefinitionCrfTagDao.java
web/src/main/java/org/akaza/openclinica/controller/SystemController.java

SQL Injection Vulnerability in ViewNotes

OC-8441 SQL Injection Vulnerability in ViewNotes

---

web/src/main/webapp/WEB-INF/jsp/managestudy/studyList.jsp

Add ‘Start Study in the new OpenClinica’ feature

Oc 8540 Add ‘Start Study in the new OpenClinica’ feature

---

web/src/main/java/org/akaza/openclinica/controller/SystemController.java

Investigate why New Qualification testing fails for URLs with _

OC-8636 Investigate why New Qualification testing fails for URLs with _

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/ItemDataDao.java

Fix for participate data submission with repeating groups

---

core/src/main/java/org/akaza/openclinica/dao/managestudy/DiscrepancyNoteDAO.java
core/src/main/java/org/akaza/openclinica/dao/managestudy/ListNotesFilter.java

SQL Injection Vulnerability in ViewNotes

OC-8441  SQL Injection Vulnerability in ViewNotes

---

web/src/main/java/org/akaza/openclinica/control/submit/ImportCRFDataServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/VerifyImportedCRFDataServlet.java
web/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFDataService.java
web/src/main/java/org/akaza/openclinica/web/job/ImportSpringJob.java

Set EventCRF Status on Data Import bug

OC-8578 Set EventCRF Status on Data Import bug

---

core/src/main/java/org/akaza/openclinica/bean/managestudy/DiscrepancyNoteBean.java
web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java

View Within Record button is missing from the Queries Table when the
Study is Locked

OC-8573     View Within Record button is missing from the Queries Table when the Study is Locked

---

web/src/main/java/org/akaza/openclinica/control/core/SecureController.java

OC-8626 OCB does not populate Study Events pulldown on the Add Subject modal when opened on the Change  Study Page

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/ParticipantFormServlet.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

Query Widget - Assign to User List not Populating

OC-8514 Query Widget - Assign to User List not Populating

---

web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp

OC-8660: View Within Record for Subject Query should expand Subject Record section
fix in demo video: https://drive.google.com/file/d/1lLsLSqQTUT7FBw9zYkHmm3aGsD3rsfUQ/view?usp=sharing

OC-8660 Progress

---

web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
web/src/main/java/org/akaza/openclinica/web/restful/ODMClinicaDataResource.java

Query Widget - Assign to User List not Populating
Load external values with XPath function

OC-8514 and OC-8622

---

web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
web/src/main/java/org/akaza/openclinica/control/submit/ViewRuleAssignmentTableFactory.java
web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudySubject.jsp

OC-8695: Type column in Query Table in incorrect location
demo: https://drive.google.com/file/d/1i6e0WAfYiSe5mnwmdTpA2ppzd0UiITr7/view?usp=sharing

OC-8685, OC-8664, OC-8603 Progress

---

web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

Load external values with XPath function

OC-8662 Fix for loading Preview without error message with clinicaldata instance

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoAPI.java

OC-8701     Remove resetting Enketo cache

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/StudyDao.java
web/src/main/java/org/akaza/openclinica/controller/StudyController.java

- Also increased the name limit check to 255 in the code as in the database

OC-8717: Adding duplicate site fails with generic error in Study Manager but still creates a site in Runtime

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/StudySubjectDao.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/StudySubjectProcessor.java

Correcting study subject label auto generation algorithm when doing anonymous submission or offline submission

Correcting study subject label auto generation algorithm

---

web/src/main/webapp/WEB-INF/jsp/menu.jsp

OC-8605 demo in: https://drive.google.com/file/d/1zyf4klxTCyTWO2gL1sb98gZnXp1ds4S1/view?usp=sharing

OC-8605: Home Page for Data Manager does not have scrollbars

---

core/src/main/java/org/akaza/openclinica/bean/core/ResolutionStatus.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/viewNotes.jsp

demo in: https://drive.google.com/file/d/1R7-w-x1Oy1dSYa3U5-gGedP6Y0zmPMhe/view?usp=sharing

OC-8693: Add Reason for Change to Queries page summary table

---

web/src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpressNew.jsp

demo in: https://drive.google.com/file/d/1sKCAjgBpphvLZ8ar9pZfAbM_HZ7dPO2S/view?usp=sharing

OC-8736: Add Subject modal - start date should be required when an event is selected

---

web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp

demo in: https://drive.google.com/file/d/1pvf0-5FgXrLPhn5qswY9il1JLgBN1klj/view?usp=sharing

OC-8650: Site and Study Monitors have Edit icon and link for Study Events

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/bean/submit/crfdata/ExportFormDataBean.java
core/src/main/java/org/akaza/openclinica/bean/submit/crfdata/ExportStudyEventDataBean.java
core/src/main/java/org/akaza/openclinica/bean/submit/crfdata/ImportItemDataBean.java
core/src/main/java/org/akaza/openclinica/bean/submit/crfdata/ImportItemGroupDataBean.java
core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
core/src/main/java/org/akaza/openclinica/dao/hibernate/EventCrfDao.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
core/src/main/resources/org/akaza/openclinica/applicationContext-core-service.xml
web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/EventProcessor.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

Reference External Data in forms using object names in the XPath

OC-8725 Reference External Data in forms using object names in the XPath

---

web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java

This code merge will fix issue with DE Started only,cause it was
broken  in OC4. With respect to Scheduled events, OC4 has the same behavior
as   OC3 today.

OC-8673     Can sign events that have a status of Scheduled and DE Started

---

web/src/main/webapp/WEB-INF/jsp/submit/addNewSubjectExpressNew.jsp

demo in: https://drive.google.com/file/d/1XwdTGJrONI6tJUFYUX0cp6IQCG8zeEST/view?usp=sharing

OC-8736-2: Add Subject modal 

---

web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp

demo in: https://drive.google.com/file/d/10GorzPPVvG5GgDizxXxlbQlfL5k6vvgO/view?usp=sharing

OC-8650-2: Site and Study Monitors have Edit icon and link for Study Events

---

web/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFDataService.java
web/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties

Data Import Issue with Incorrect OIDs

OC-8622 Data Import Issue with Incorrect OIDs

---

web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

Update OpenClinica namespace in Clinical Data file sent to Enketo

OC-8758 Update OpenClinica namespace in Clinical Data file sent to Enketo

---

core/src/main/java/org/akaza/openclinica/dao/core/EntityDAO.java
core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java

If Study subjects enrollement date has been removed you can not extract that study subject

OC-6322: If Study subjects enrollement date has been removed you can not extract that study subject

---

core/pom.xml
core/src/main/java/org/akaza/openclinica/job/XsltTransformJob.java
core/src/main/resources/properties/xslt/xml_convert_sas_data.xsl
core/src/main/resources/properties/xslt/xml_convert_sas_format.xsl
core/src/main/resources/properties/xslt/xml_convert_sas_map.xsl

Extract fix, force saxon to do transformation. Change SAS transformation xslts to escape paranthesis in study oid

Extract fix, force saxon to do transformation. Change SAS transformation xslts to escape paranthesis in study oid

---

web/src/main/java/org/akaza/openclinica/control/submit/ListDiscNotesSubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java

demo in: https://drive.google.com/file/d/1K57LDJvHFpskON2-QhccizEJrIS1hbzb/view?usp=sharing

OC-8575: Locked study still has Add Occurrence link for repeating events

---

web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

Enketo Bad Request error when trying to view archived form version

OC-8767 Enketo Bad Request error when trying to view archived form version

---

web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

Adding Logger to OpenRosaServices also for performance , added code to
return HEAD method types without going through whole method

OC-AddingLoggers. Adding Logger to OpenRosaServices also for performance , added code to return HEAD method types without going through whole method

---

web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

To formID , formLayoutOut , formLayout obj and crf

OC-AddingLoggers. To formID , formLayoutOut , formLayout obj and crf

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

added loggers and made modification to View Query call and Instance
template

OC-AddingLoggers.  added loggers and made modification to View Query call and Instance template

---

core/src/main/java/org/akaza/openclinica/dao/core/CoreResources.java
core/src/main/resources/properties/import_template.xml
web/src/main/java/org/akaza/openclinica/control/submit/ImportRuleServlet.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/submit/import.jsp

Demo in: https://drive.google.com/file/d/1WZQeS5x3SaCrPU-N3vN0zpbfXqSqmlpa/view?usp=sharing

OC-8667-2: Download Import Template

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/AdminDataReportBean.java
core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/bean/extract/odm/FullReportBean.java
core/src/main/java/org/akaza/openclinica/bean/extract/odm/MetaDataReportBean.java
core/src/main/java/org/akaza/openclinica/bean/extract/odm/OdmXmlReportBean.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
web/src/main/java/org/akaza/openclinica/web/restful/MetadataCollectorResource.java
web/src/main/java/org/akaza/openclinica/web/restful/ODMClinicaDataResource.java

Send only clinical data to Enketo when a form with cross-form logic is
opened

OC-8753 Send only clinical data to Enketo when a form with cross-form logic is opened

---

web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

CRC user gets error opening form with cross-form logic

OC-8840 CRC user gets error opening form with cross-form logic

---

web/src/main/java/org/akaza/openclinica/controller/StudySubjectOverhaulController.java
web/src/main/java/org/akaza/openclinica/controller/dto/SSOverhaulDTO.java

Add new Event CRFs from the View Study Subject Overhaul page

OC-8821 Add new Event CRFs from the View Study Subject Overhaul page

---

web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableToolbar.java

Site ID column is only in the Detailed Queries view

OC-8817 Site ID column is only in the Detailed Queries view

---

web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudySubjectServlet.java

OC-8620 Data Entry Person cannot Update Study Subject Details when accessing a Subject at the Study-level

---

core/src/main/java/org/akaza/openclinica/bean/extract/ExtractBean.java
core/src/main/java/org/akaza/openclinica/dao/managestudy/StudyEventDAO.java
core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
core/src/main/java/org/akaza/openclinica/service/rule/expression/ExpressionService.java
web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
web/src/main/java/org/akaza/openclinica/control/extract/DiscrepancyNoteOutputServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudyEventsServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/CreateNewStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/ListDiscNotesSubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/control/submit/ListDiscNotesSubjectTableToolbar.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/control/submit/MarkEventCRFCompleteServlet.java
web/src/main/java/org/akaza/openclinica/controller/OdmController.java
web/src/main/java/org/akaza/openclinica/controller/StudySubjectOverhaulController.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/EventProcessor.java
web/src/main/java/org/akaza/openclinica/web/bean/DisplayStudyEventRow.java
web/src/main/java/org/akaza/openclinica/web/bean/DisplayStudySubjectEventsRow.java
web/src/main/java/org/akaza/openclinica/web/bean/StudyEventRow.java
web/src/main/java/org/akaza/openclinica/web/table/sdv/SDVUtil.java

Also include:
OC-8850:  Schedule Event page should not include Common Events
OC-8853:  Subject Matrix does not show Common Events
OC-8852:  Remove Common Events from View Events page

OC-8844 Common Events will not have Start Date

---

web/src/main/webapp/WEB-INF/jsp/subjects.jsp

- NPE fixes
- empty status fix

OC-8820 bugfixes

---

web/src/main/webapp/WEB-INF/jsp/subjects.jsp

- Column highlighting on mouseover
- Per-column filtering
- Text cutoff if > 200 characters

OC-8820 Datatables tweaks (Jing's email):

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/bean/submit/crfdata/FormDataBean.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java

Add Event CRF Created and Updated Dates to the ODM

OC-8836 Add Event CRF Created and Updated Dates to the ODM

---

web/src/main/java/org/akaza/openclinica/control/managestudy/RemoveStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/RestoreStudyEventServlet.java

-Oops error on Restore Event for Subject at a Site
-Remove/Restore Event at Site-Level Subject hides study name from the
title bar

OC-8845 & OC-8846 Oops error on Restore Event for Subject at a Site

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/AdminDataReportBean.java
core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/bean/extract/odm/FullReportBean.java
core/src/main/java/org/akaza/openclinica/bean/extract/odm/MetaDataReportBean.java
core/src/main/java/org/akaza/openclinica/bean/extract/odm/OdmXmlReportBean.java
core/src/main/java/org/akaza/openclinica/bean/submit/crfdata/ExportFormDataBean.java
core/src/main/java/org/akaza/openclinica/bean/submit/crfdata/ExportStudyEventDataBean.java
core/src/main/java/org/akaza/openclinica/bean/submit/crfdata/ExportSubjectDataBean.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
core/src/main/java/org/akaza/openclinica/service/extract/OdmFileCreation.java
core/src/main/resources/org/akaza/openclinica/applicationContext-core-service.xml
web/src/main/java/org/akaza/openclinica/web/restful/ODMClinicaDataResource.java

Actions for CRF Summary Tables for Common Events

OC-8861     Actions for CRF Summary Tables for Common Events

---

web/src/main/java/org/akaza/openclinica/controller/StudySubjectDetailsController.java
web/src/main/webapp/WEB-INF/jsp/subjects.jsp

Study Subject details page overhaul

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp

https://jira.openclinica.com/browse/OC-8819

OC-8819 integrate the Common Events view into the View Study Subject page

---

web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/include/showTable.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp

https://jira.openclinica.com/browse/OC-8819

OC-8819 View Subject - CRF Summary Tables

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp

https://jira.openclinica.com/browse/OC-8884

 OC-8884 View Subject page toggle to hide/show removed Events

---

web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/AbstractItemProcessor.java

Deleting a Repeating Group on a complete form is creating RFC with
status Closed

OC-8908 Deleting a Repeating Group on a complete form is creating RFC with status Closed

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoAPI.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoURLResponse.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/AbstractItemProcessor.java

Integrate with new Enketo APIs
Warning, merging this code requires new Enketo branch 'feature/oc-api' code to be merged as well. 
Otherwise, forms will not be loaded.

OC-8909 Warning, merging this code requires new Enketo branch 'feature/oc-api' code to be merged as well.

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java

Wrong redirect for the actions items in Common Event

OC-8932 Wrong redirect for the actions items in Common Event

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java

This will resolve also Oops error page when clicking reassign icon.

OC-8933 View Subject page is showing 1 table per CRF Version not 1 table per CRF

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoAPI.java

Update status of Common Events

OC-8942 Update status of Common Events

---

web/src/main/java/org/akaza/openclinica/control/MainMenuServlet.java
web/src/main/java/org/akaza/openclinica/controller/CallbackController.java
web/src/main/java/org/akaza/openclinica/controller/LogoutController.java

- Added some debug statements
- Added "return" statements where there was redirect/forward

OC-8729 Users get correct Runtime page on login

---

core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoAPI.java

Editing an existing Data Entry Started form is Marking it Complete and
triggering RFC

OC-8950 Editing an existing Data Entry Started form is Marking it Complete and triggering RFC

---

web/src/main/java/org/akaza/openclinica/controller/StudySubjectOverhaulController.java

fixed schema related issue for Get page_layout endpoint

OC-8913 fixed schema related issue for Get page endpoint

---

core/src/main/resources/properties/OpenClinica-ODM1-3-0-OC2-0-foundation.xsd
core/src/main/resources/properties/OpenClinica-ToODM1-3-0-OC2-0.xsd

1. change SectionDetailsDefinition to SectionDetails;
2. add EnrollmentDate attribue for  SubjectDataAttributeExtension;
3. add attribute AllowAnonymousSubmission under PresentInEventDefinitionAttributeDefinition;
4. add attribute Offline under PresentInEventDefinitionAttributeDefinition.

OC-8901: fix list

---

web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp

Span within the delete button had the same name as the remove button at the event level

Update Delete button name on viewSubjectPage

---

core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java

Issue calling clinical data if study subject OID is set to a wildcard

OC-8970 Issue calling clinical data if study subject OID is set to a wildcard

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java

OC-8979 Conflict issue

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java

fixed issue with page error , Hidden Crf and Archiving forms.

OC-8979 fixed issue with page error , Hidden Crf and Archiving forms.

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
web/src/main/java/org/akaza/openclinica/service/ViewStudySubjectServiceImpl.java

Hidden forms at the site level are also hidden on the study level

OC-8979     Hidden forms at the site level are also hidden on the study level

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/dao/hibernate/EventDefinitionCrfDao.java
core/src/main/java/org/akaza/openclinica/dao/managestudy/EventDefinitionCRFDAO.java
core/src/main/java/org/akaza/openclinica/service/EventService.java
core/src/main/java/org/akaza/openclinica/service/EventServiceInterface.java
core/src/main/java/org/akaza/openclinica/service/OdmImportService.java
core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java
core/src/main/resources/org/akaza/openclinica/applicationContext-core-service.xml
core/src/main/resources/properties/event_definition_crf_dao.xml
web/src/main/java/org/akaza/openclinica/controller/OdmImportController.java

New Link for Add new action in Common events

OC-8976 New Link for Add new action in Common events

---

core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java

fixed issue related to deploying

OC-8976 fixed issue related to deploying

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java

New Link for Add new action in Common events
Issues with Monitor View on View Study Subject Page

OC-8976b and OC-8991

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java

OC-8999 Cannot generate Extracts

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/dao/core/EntityDAO.java
core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java

issue with AddNew Button disappearing for non repeating events

OC-9003 issue with AddNew Button disappearing for non repeating events

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp
web/src/main/webapp/includes/css/icomoon-style.css
web/src/main/webapp/includes/scss/oc2017_styles.scss
web/src/main/webapp/includes/styles.css

- OC-8947
- OC-8944
- OC-9031
- OC-9032
- OC-9045

Common Events view updates

---

core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java

Add Connect and Read TimeOut Settings in Runtime for Form Service Calls.

OC-9026 Add Connect and Read TimeOut Settings in Runtime for Form Service Calls.

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java

Archived Form Versions in Common Events can be edited

OC-8982 Archived Form Versions in Common Events can be edited

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java

Junk characters appear in the ODM with degree symbol

OC-8997 Junk characters appear in the ODM with degree symbol

---

web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
web/src/main/java/org/akaza/openclinica/service/ViewStudySubjectServiceImpl.java

Stale forms links during concurrent usage scenarios

OC-9049 Stale forms links during concurrent usage scenarios

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/ItemFormMetadataDao.java
core/src/main/java/org/akaza/openclinica/dao/hibernate/ItemGroupMetadataDao.java
core/src/main/java/org/akaza/openclinica/dao/hibernate/ResponseSetDao.java
core/src/main/java/org/akaza/openclinica/dao/hibernate/VersioningMapDao.java
core/src/main/java/org/akaza/openclinica/service/crfdata/ResponseSetService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java

Publishing a study fails if taking mre than 390 seconds

OC-9074 Publishing a study fails if taking mre than 390 seconds

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ListEventsForSubjectTableFactory.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties

Subject Matrix is showing the same start date for multiple instances of a Repeating Event that are scheduled for different dates

OC-9068 Subject Matrix is showing the same start date for multiple instances of a Repeating Event that are scheduled for different dates

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp

https://jira.openclinica.com/browse/OC-9031
https://jira.openclinica.com/browse/OC-9032

"Reset Filters" bugfixes (OC-9031, OC-9032)

---

web/src/main/webapp/WEB-INF/jsp/managestudy/chooseCRFVersion.jsp

View form version link from CRF Migration page fails

OC-9110 View form version link from CRF Migration page fails

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp

https://jira.openclinica.com/browse/OC-9118

OC-9118 Remove the table-level Reset button from the View Subject Details page

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java

Include user role and username in cross-form logic clinical data

OC-8988 Include user role and username in cross-form logic clinicaldata

---

web/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties

[minor update from Paul](https://jira.openclinica.com/browse/OC-9098?focusedCommentId=157738&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-157738)

OC-9098 Change Subject to Participant on Rules UI

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

https://jira.openclinica.com/browse/OC-9134

OC-9134: Persistent Filters should be per study environment per subject

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp

https://jira.openclinica.com/browse/OC-9135

OC-9135 No table displayed at study level for hidden form

---

web/src/main/webapp/WEB-INF/jsp/submit/viewRules.jsp

https://jira.openclinica.com/browse/OC-9125

OC-9125 Rule designer icon should be removed from the manage rules page

---

web/src/main/webapp/WEB-INF/jsp/submit/enketoFormServlet.jsp

- Push back the changes that were overwritten by a merge from OC Master

OC-9064 User releases form lock

---

core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java

View Participant Details page does not load if a form has no items saved to the OC database

OC-9090 View Participant Details page does not load if a form has no items saved to the OC database

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp

https://jira.openclinica.com/browse/OC-9135

OC-9135: No table displayed at study level for hidden form (revised)

---

core/src/main/java/org/akaza/openclinica/job/XsltTransformJob.java

Success email not sent for extracts

OC-9157 Success email not sent for extracts

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp

OC4 A "Not Started" CRF can be edited in a locked event

OC-9169 OC4 A "Not Started" CRF can be edited in a locked event

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/service/managestudy/StudySubjectServiceImpl.java
web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectServlet.java
web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp

OC4 An existing CRF in a stopped event should be editable

OC-9164 OC4 An existing CRF in a stopped event should be editable

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
web/src/main/java/org/akaza/openclinica/control/managestudy/RemoveEventCRFServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/RemoveStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/RestoreEventCRFServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/RestoreStudyEventServlet.java
web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
web/src/main/webapp/WEB-INF/jsp/submit/enterDataForStudyEvent.jsp

All data entry users should be able to restore/remove CRFs and events

OC-8783 All data entry users should be able to restore/remove CRFs and events

---

web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp

https://jira.openclinica.com/browse/OC-9191

OC-9191 Add Privacy Policy link to user menu

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ListSiteServlet.java
web/src/main/webapp/WEB-INF/jsp/managestudy/viewSite.jsp

https://jira.openclinica.com/browse/OC-9140

OC-9140 Manage Sites & View Site screens do not label Site ID correctly

---

core/src/main/resources/logback.xml
web/src/main/java/org/akaza/openclinica/controller/OdmImportController.java

- Changed hashmap expiration to 24 hours

OC-9178 Make Publish call asycnhronous

---

core/src/main/java/org/akaza/openclinica/service/crfdata/ResponseSetService.java
web/src/main/java/org/akaza/openclinica/config/SwaggerConfig.java
web/src/main/java/org/akaza/openclinica/controller/ODMClinicalDataController.java
web/src/main/java/org/akaza/openclinica/controller/StudyController.java

Publish error message if codes are too long for an item
Also changes to API calls

OC-9188 Publish error message if codes are too long for an item

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/UserAccountDao.java
core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

OC-9112 Run external read calculations on view mode forms

OC 9178 Make Publish call asycnhronous , OC-9112 Run external read calculations on view mode forms

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/UserAccountDao.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java

OC-9183
Query notification shows wrong Updated By user
OC-9184
OC4 Deactivated Users can be assigned queries

OC-9183 Query notification shows wrong Updated By user , OC-9184 OC4 Deactivated Users can be assigned queries

---

web/src/main/webapp/WEB-INF/jsp/managestudy/siteList.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/updateSubStudy.jsp

https://jira.openclinica.com/browse/OC-9197

OC-9197 Update Site page broken CSS

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java

Export does not generate
This merge should resolve all the reported extract issues

OC-9205 Export does not generate

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/StudyAuditLogTableFactory.java
web/src/main/webapp/WEB-INF/jsp/admin/auditLogStudy.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectAudit.jsp
ws/src/main/webapp/WEB-INF/jsp/admin/auditLogStudy.jsp
ws/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectAudit.jsp

https://jira.openclinica.com/browse/OC-9216

OC-9216 Remove "Participant" from the string "Secondary Participant ID"

---

core/src/main/java/org/akaza/openclinica/bean/extract/ExtractBean.java
core/src/main/resources/properties/xslt/ODMToTAB.xsl
core/src/main/resources/properties/xslt/odm_to_html.xsl
web/src/main/java/org/akaza/openclinica/control/managestudy/ManageStudyServlet.java
web/src/main/java/org/akaza/openclinica/controller/SDVController.java
web/src/main/java/org/akaza/openclinica/web/job/TriggerService.java
web/src/main/webapp/WEB-INF/jsp/managestudy/managestudy_body.jsp
ws/src/main/java/org/akaza/openclinica/web/job/TriggerService.java
ws/src/main/webapp/WEB-INF/jsp/managestudy/managestudy_body.jsp
ws/src/main/webapp/WEB-INF/jsp/submit/verifyImport.jsp

https://jira.openclinica.com/browse/OC-9206

OC-9206 HTML Extract label remains Subject instead of Participant

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
web/src/main/webapp/WEB-INF/jsp/submit/enketoFormServlet.jsp

Add jini parameter to new/edit form URLs to enable jini module in form engine

OC-9201 Add jini parameter to new/edit form URLs to enable jini module in form engine

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp

System allows user to enter data into common forms to a removed participant

OC-9225 System allows user to enter data into common forms to a removed participant

---

web/src/main/webapp/WEB-INF/jsp/include/sideInfo.jsp

https://jira.openclinica.com/browse/OC-9196

OC-9196 Duplicate icon key shown for some user roles

---

web/src/main/webapp/WEB-INF/jsp/include/sideIconsSubject.jsp

https://jira.openclinica.com/browse/OC-9195

OC-9195 Icons missing/outdated in Icon Key

---

web/src/main/resources/org/akaza/openclinica/i18n/page_messages.properties

https://jira.openclinica.com/browse/OC-9226

OC-9226 Add Participant shows wrong mesage

---

core/src/main/java/org/akaza/openclinica/bean/extract/DownloadDiscrepancyNote.java
core/src/main/java/org/akaza/openclinica/bean/extract/ExtractBean.java
core/src/main/java/org/akaza/openclinica/bean/extract/odm/MetaDataReportBean.java
core/src/main/resources/properties/xslt/ODMToTAB.xsl
core/src/main/resources/properties/xslt/odm_spss_sps.xsl
core/src/main/resources/properties/xslt/odm_to_html.xsl
web/src/main/java/org/akaza/openclinica/web/job/TriggerService.java
web/src/main/webapp/WEB-INF/jsp/itemDataResult.jsp
web/src/main/webapp/WEB-INF/jsp/multiSchemaResult.jsp
ws/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
ws/src/main/webapp/WEB-INF/jsp/menu.jsp
ws/src/main/webapp/WEB-INF/jsp/submit/verifyImport.jsp
ws/src/main/webapp/WEB-INF/jsp/viewAllSubjectSDV.jsp
ws/src/main/webapp/WEB-INF/jsp/viewAllSubjectSDVtmp.jsp
ws/src/main/webapp/WEB-INF/jsp/viewSubjectAggregate.jsp
ws/src/main/webapp/WEB-INF/jsp/viewSubjectAggregateSDV.jsp
ws/src/main/webapp/WEB-INF/jsp/viewSubjectSDV.jsp

https://jira.openclinica.com/browse/OC-9206

OC-9206 (feedback) - HTML Extract label remains Subject instead of Participant

---

core/src/main/java/org/akaza/openclinica/core/EventCRFLocker.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java
web/src/main/java/org/akaza/openclinica/controller/StudyController.java

- OC-9141 Opening a Query in read-only mode should not lock the form
- Changed error from SEE_OTHER to BAD_REQUEST
- Added debug info for CRF locking

dataimport-problems

---

core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java

Intermittently Enketo erros on viewling an archived Event CRF

OC-9252 Intermittently Enketo erros on viewling an archived Event CRF

---

core/src/main/resources/properties/xslt/xml_convert_sas_format.xsl
core/src/main/resources/properties/xslt/xml_convert_sas_map.xsl

Merge SAS fixes for OC-7816 and OC-8304 into OC4 Runtime

OC-9126 Merge SAS fixes for OC-7816 and OC-8304 into OC4 Runtime

---

web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp

Archived Event CRF should not be able to be deleted in Runtime

OC-9258 Archived Event CRF should not be able to be deleted in Runtime

---

web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServiceImpl.java

OC-8818 Editing a user profile is not reflected in query widget dropdown
- Make user service timeout configurable

get-query-users-from-sbs

---

web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableToolbar.java

https://jira.openclinica.com/browse/OC-9276

OC-9276 Participant Matrix page update

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/UserAccountDao.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServiceImpl.java
web/src/main/resources/datainfo.properties

OC-9331 Site level users are displayed in query assignment drop down for a study level participant

OC-9331 Site level users are displayed in query assignment drop down for a study level participant

---

web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableToolbar.java

https://jira.openclinica.com/browse/OC-9276

OC-9276 Participant Matrix page update: Putting the OID back in

---

core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java

- added a debug statement to log schema name

OC-9279 Randomly getting manifest error when opening form in edit mode

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

https://jira.openclinica.com/browse/OC-9313

OC-9313 Participant page - fix Site name text link

---

web/src/main/java/org/akaza/openclinica/control/managestudy/RemoveStudySubjectServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectServlet.java
web/src/main/webapp/WEB-INF/jsp/managestudy/removeStudySubject.jsp

https://jira.openclinica.com/browse/OC-9277

OC-9277 Participant Remove page updates

---

web/src/main/java/org/akaza/openclinica/control/form/Validator.java
web/src/main/java/org/akaza/openclinica/control/submit/AddNewSubjectServlet.java
web/src/main/java/org/akaza/openclinica/controller/StudyController.java
web/src/main/java/org/akaza/openclinica/controller/dto/ParticipantIdModel.java

Participant ID duplicate check

OC-9336 Participant ID duplicate check

---

core/src/main/java/org/akaza/openclinica/dao/managestudy/StudySubjectDAO.java
core/src/main/resources/properties/study_subject_dao.xml
web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java

A user is able to add a Participant at a Site when the total number of Study-level Participants has reached Participant Cap

OC-9357 A user is able to add a Participant at a Site when the total number of Study-level Participants has reached Participant Cap

---

core/src/main/java/org/akaza/openclinica/dao/managestudy/StudySubjectDAO.java
core/src/main/resources/properties/study_subject_dao.xml
web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/controller/StudyController.java
web/src/main/java/org/akaza/openclinica/controller/dto/ParticipantIdModel.java

ID Template validation messsages

OC-9378 ID Template validation messsages

---

core/src/main/java/org/akaza/openclinica/dao/managestudy/StudySubjectDAO.java
core/src/main/resources/properties/study_subject_dao.xml
web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
web/src/main/java/org/akaza/openclinica/control/submit/AddNewSubjectServlet.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/controller/StudyController.java
web/src/main/java/org/akaza/openclinica/controller/dto/ParticipantIdModel.java

Participants with System-generated IDs may be created after the Enrollment Limit is reached

Oc 9379 Participants with System-generated IDs may be created after the Enrollment Limit is reached

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/dao/hibernate/EventDefinitionCrfPermissionTagDao.java
core/src/main/java/org/akaza/openclinica/domain/datamap/EventDefinitionCrfPermissionTag.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
core/src/main/resources/migration/tenant/4.0-2018-07-25-OC-9375.xml
core/src/main/resources/migration/tenant/release.xml
core/src/main/resources/org/akaza/openclinica/applicationContext-core-hibernate.xml
core/src/main/resources/org/akaza/openclinica/applicationContext-core-service.xml
core/src/main/resources/properties/event_definition_crf_dao.xml
core/src/main/resources/properties/eventcrf_dao.xml
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

Participant Details page doesn't show Common Event Forms the user doesn't have access to

OC-9375 Form Permission Tags

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/StudyAuditLogTableFactory.java
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectAudit.jsp

https://jira.openclinica.com/browse/OC-9278

OC-9278 Study Audit log and Participant Audit log updates to remove participant attributes

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/dao/hibernate/EventDefinitionCrfPermissionTagDao.java
core/src/main/java/org/akaza/openclinica/domain/datamap/EventDefinitionCrfPermissionTag.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
core/src/main/resources/migration/tenant/4.0-2018-07-25-OC-9375.xml
core/src/main/resources/migration/tenant/release.xml
core/src/main/resources/org/akaza/openclinica/applicationContext-core-hibernate.xml
core/src/main/resources/org/akaza/openclinica/applicationContext-core-service.xml
core/src/main/resources/properties/event_definition_crf_dao.xml
core/src/main/resources/properties/eventcrf_dao.xml
pom.xml
web/src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectAuditLogServlet.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

Participant Audit Log does not include data from forms the user doesn't have access to

OC-9385 Participant Audit Log does not include data from forms the user doesn't have access to

---

web/src/main/webapp/WEB-INF/jsp/extract/selectEventAttribute.jsp
web/src/main/webapp/WEB-INF/jsp/extract/selectSubAttribute.jsp
web/src/main/webapp/WEB-INF/jsp/extract/selected-inactive.jsp
web/src/main/webapp/WEB-INF/jsp/extract/selected.jsp

https://jira.openclinica.com/browse/OC-9280

OC-9280 Create and View Dataset page updates to remove participant attributes

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/EventDefinitionCrfPermissionTagDao.java
core/src/main/java/org/akaza/openclinica/domain/datamap/EventDefinitionCrfPermissionTag.java
core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java

Publish Form Permission Tags on Runtime part

OC-9375     Publish Form Permission Tags

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/dao/hibernate/EventDefinitionCrfPermissionTagDao.java
core/src/main/java/org/akaza/openclinica/dao/managestudy/EventDefinitionCRFDAO.java
core/src/main/java/org/akaza/openclinica/dao/submit/EventCRFDAO.java
core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
core/src/main/resources/properties/event_definition_crf_dao.xml
core/src/main/resources/properties/eventcrf_dao.xml
web/src/main/java/org/akaza/openclinica/control/MainMenuServlet.java
web/src/main/java/org/akaza/openclinica/control/login/ChangeStudyServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectAuditLogServlet.java
web/src/main/java/org/akaza/openclinica/controller/SDVController.java
web/src/main/java/org/akaza/openclinica/web/table/sdv/SDVUtil.java
web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp

Added TagIds to the scripts to filter out the Tagged forms for users who do not have permission tags.

OC-9385 Added TagIds to the scripts to filter out the Tagged forms for users who do not have permission tags.

---

web/src/main/java/org/akaza/openclinica/control/managestudy/RestoreStudySubjectServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectServlet.java
web/src/main/webapp/WEB-INF/jsp/managestudy/restoreStudySubject.jsp

Note: On screenshot the scheduled event status name is Available(if there any available scheduled event when participant removed) but based on the code, the scheduled event status will be set to auto-removed when it's participant is removed so I used Removed status name instead of Available for any scheduled event that show up on restored page.

OC-9290 Restore Participant page updates

---

web/src/main/webapp/WEB-INF/jsp/managestudy/reassignStudySubject.jsp

https://jira.openclinica.com/browse/OC-9289

OC-9289 Reassign Participant page updates

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/bean/managestudy/EventDefinitionCrfPermissionTagBean.java
core/src/main/java/org/akaza/openclinica/dao/core/EntityDAO.java
core/src/main/java/org/akaza/openclinica/dao/core/PreparedStatementFactory.java
core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
core/src/main/java/org/akaza/openclinica/dao/managestudy/EventDefinitionCRFDAO.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/ClinicalDataUnit.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/MetadataUnit.java
core/src/main/resources/properties/event_definition_crf_dao.xml
web/src/main/java/org/akaza/openclinica/control/MainMenuServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectAuditLogServlet.java

Dataset extracts do not include data from forms the user doesn't have access to

OC-9386 Dataset extracts do not include data from forms the user doesn't have access to

---

web/src/main/webapp/WEB-INF/jsp/managestudy/reassignStudySubject.jsp
web/src/main/webapp/includes/styles.css

https://jira.openclinica.com/browse/OC-9312

OC-9312 Reassign Participant UI Updates

---

web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/admin/viewFullStudy.jsp

OC-9384 Study Metadata details page update

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ResolveDiscrepancyServlet.java

https://jira.openclinica.com/browse/OC-9407

OC-9407 Query Manager table reloads without default filters

---

core/src/main/java/org/akaza/openclinica/dao/managestudy/ViewNotesDaoImpl.java
core/src/main/resources/queries/oracle/viewnotes.properties
core/src/main/resources/queries/postgres/viewnotes.properties

https://jira.openclinica.com/browse/OC-9405

OC-9405 Default Query sort order

---

web/src/main/webapp/WEB-INF/jsp/managestudy/reassignStudySubject.jsp

Feedback from Renuka:
- AC6
- Remove "Site" field from the table
https://jira.openclinica.com/browse/OC-9312?focusedCommentId=162713&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-162713

OC-9312 Feedbacks

---

web/src/main/webapp/WEB-INF/jsp/extract/createDatasetStep2.jsp
web/src/main/webapp/WEB-INF/jsp/extract/selected-inactive.jsp
web/src/main/webapp/WEB-INF/jsp/extract/selected.jsp

https://jira.openclinica.com/browse/OC-8576

OC-8576 Extract Page has extra columns that are no longer applicable

---

web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp

https://jira.openclinica.com/browse/OC-9459

OC-9459 Reassign CRF Page has javascript errors

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/bean/extract/odm/FullReportBean.java
core/src/main/java/org/akaza/openclinica/job/XsltTransformJob.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/ClinicalDataCollector.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/ClinicalDataUnit.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/MetaDataCollector.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/MetadataUnit.java
core/src/main/java/org/akaza/openclinica/service/PermissionServiceImpl.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateExtractFileService.java
core/src/main/java/org/akaza/openclinica/service/extract/OdmFileCreation.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ExportExcelStudySubjectAuditLogServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectAuditLogServlet.java
web/src/main/java/org/akaza/openclinica/web/restful/MetadataCollectorResource.java
web/src/main/java/org/akaza/openclinica/web/restful/ODMClinicaDataResource.java

Participant Details page doesn't show Common Event Forms the user doesn't have access to

OC-9369     Participant Details page doesn't show Common Event Forms the user doesn't have access to

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/dao/core/CoreResources.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/MetadataUnit.java
core/src/main/java/org/akaza/openclinica/service/PermissionServiceImpl.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
web/src/main/java/org/akaza/openclinica/control/MainMenuServlet.java
web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectsServlet.java
web/src/main/java/org/akaza/openclinica/controller/helper/EnrollmentInterceptor.java

- One person able to access another person's study
- EnrollmentCap Null pointer and logout issue
- Manifest error issue
- Sites not able to access

- Blank screen issue and several other issues

---

core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java

Participant Details page doesn't show Common Event Forms the user doesn't have access to

OC-9369 Participant Details page doesn't show Common Event Forms the user doesn't have access to

---

core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java

Participant Details Page doesn't load Visit or Common Events Sections

OC-9484     Participant Details Page doesn't load Visit or Common Events Sections

---

web/src/main/java/org/akaza/openclinica/controller/SDVController.java

SDV page doesn't show forms the user doesn't have access to

OC-9382 SDV page doesn't show forms the user doesn't have access to

---

core/src/main/java/org/akaza/openclinica/dao/hibernate/multitenant/MultiTenantFilter.java
web/src/main/java/org/akaza/openclinica/control/core/SecureController.java

Includes schema changes in MultiTenantFilter

OC-9396 fix

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
web/src/main/java/org/akaza/openclinica/control/form/Validator.java
web/src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java
web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudySubjectServlet.java
web/src/main/webapp/WEB-INF/jsp/managestudy/updateStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/submit/eventCrfLayer.jsp

OC-9479 Remove button is missing on Participant Matrix event view if permission tags are attached to a form.
OC-9474 Reassign button is inactive on participant view event page

OC-9479 Remove button is missing on Participant Matrix event view if permission tags are attached to a form.

---

web/src/main/java/org/akaza/openclinica/control/managestudy/EventCrfLayerBuilder.java

OC-9479 Remove button is missing on Participant Matrix event view if permission tags are attached to a form.

OC-9512 Two buttons missing on the Participant Matrix when sorted by Event

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/bean/extract/odm/FullReportBean.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/MetaDataCollector.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/MetadataUnit.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataService.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
core/src/main/java/org/akaza/openclinica/service/extract/OdmFileCreation.java
web/src/main/java/org/akaza/openclinica/control/admin/DownloadStudyMetadataServlet.java
web/src/main/java/org/akaza/openclinica/controller/RuleController.java
web/src/main/java/org/akaza/openclinica/controller/SDVController.java
web/src/main/java/org/akaza/openclinica/web/restful/ClinicalDataCollectorResource.java
web/src/main/java/org/akaza/openclinica/web/restful/MetadataCollectorResource.java
web/src/main/java/org/akaza/openclinica/web/restful/ODMClinicaDataResource.java
ws/src/main/java/org/akaza/openclinica/ws/StudyEndpoint.java

Cross-form clinical data includes all Form data

OC-9395 Cross-form clinical data includes all Form data

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/bean/extract/odm/FullReportBean.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/ClinicalDataUnit.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/MetaDataCollector.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/MetadataUnit.java
core/src/main/java/org/akaza/openclinica/service/PermissionService.java
core/src/main/java/org/akaza/openclinica/service/PermissionServiceImpl.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataService.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
core/src/main/java/org/akaza/openclinica/service/extract/OdmFileCreation.java
web/src/main/java/org/akaza/openclinica/control/admin/DownloadStudyMetadataServlet.java
web/src/main/java/org/akaza/openclinica/controller/RuleController.java
web/src/main/java/org/akaza/openclinica/controller/SDVController.java
web/src/main/java/org/akaza/openclinica/web/restful/ClinicalDataCollectorResource.java
web/src/main/java/org/akaza/openclinica/web/restful/MetadataCollectorResource.java
web/src/main/java/org/akaza/openclinica/web/restful/ODMClinicaDataResource.java
ws/src/main/java/org/akaza/openclinica/ws/StudyEndpoint.java

Tagged Common Event form does not show in Participant Detail Page

OC-9511 Tagged Common Event form does not show in Participant Detail Page

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/bean/extract/odm/FullReportBean.java
core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
core/src/main/java/org/akaza/openclinica/job/XsltTransformJob.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/ClinicalDataCollector.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/ClinicalDataUnit.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/MetaDataCollector.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/MetadataUnit.java
core/src/main/java/org/akaza/openclinica/service/PermissionService.java
core/src/main/java/org/akaza/openclinica/service/PermissionServiceImpl.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateExtractFileService.java
core/src/main/java/org/akaza/openclinica/service/extract/OdmFileCreation.java
web/src/main/java/org/akaza/openclinica/control/admin/DownloadStudyMetadataServlet.java
web/src/main/java/org/akaza/openclinica/control/extract/ExportDatasetServlet.java
web/src/main/java/org/akaza/openclinica/controller/ExtractController.java
web/src/main/java/org/akaza/openclinica/controller/RuleController.java
web/src/main/java/org/akaza/openclinica/web/job/ExampleSpringJob.java
web/src/main/java/org/akaza/openclinica/web/restful/MetadataCollectorResource.java
web/src/main/java/org/akaza/openclinica/web/restful/ODMClinicaDataResource.java
web/src/main/java/org/akaza/openclinica/web/restful/ODMMetadataRestResource.java
ws/src/main/java/org/akaza/openclinica/ws/StudyEndpoint.java

Dataset extracts do not include data from forms the user doesn't have access to

Oc 9386 Dataset extracts do not include data from forms the user doesn't have access to

---

web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/noAccess.jsp

https://jira.openclinica.com/browse/OC-9339?focusedCommentId=161368&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-161368

OC-9464: "No Access" page -- Paul's feedback

---

core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
core/src/main/java/org/akaza/openclinica/dao/hibernate/ArchivedDatasetFilePermissionTagDao.java
core/src/main/java/org/akaza/openclinica/dao/hibernate/EventDefinitionCrfPermissionTagDao.java
core/src/main/java/org/akaza/openclinica/domain/datamap/ArchivedDatasetFilePermissionTag.java
core/src/main/java/org/akaza/openclinica/job/XsltTransformJob.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/ClinicalDataUnit.java
core/src/main/java/org/akaza/openclinica/service/extract/GenerateExtractFileService.java
core/src/main/java/org/akaza/openclinica/service/extract/OdmFileCreation.java
core/src/main/resources/migration/tenant/4.0-2018-08-24-OC-9383.xml
core/src/main/resources/migration/tenant/release.xml
core/src/main/resources/org/akaza/openclinica/applicationContext-core-hibernate.xml
web/src/main/java/org/akaza/openclinica/control/extract/AccessFileServlet.java
web/src/main/java/org/akaza/openclinica/control/extract/ExportDatasetServlet.java
web/src/main/java/org/akaza/openclinica/controller/ExtractController.java

Add Permission Tags to Dataset zip files

OC-9383 Add Permission Tags to Dataset zip files

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

Participant Details Page doesn't load Visit or Common Events Sections

OC-9484 Participant Details Page doesn't load Visit or Common Events Sections

---

web/src/main/webapp/WEB-INF/jsp/submit/enketoFormServlet.jsp

https://jira.openclinica.com/browse/OC-9441

OC-9441 Enketo forms won't scroll on iOS devices

---

core/src/main/java/org/akaza/openclinica/service/EventService.java
core/src/main/resources/properties/discrepancy_note_dao.xml
web/src/main/java/org/akaza/openclinica/control/admin/DeleteEventCRFServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/RemoveEventCRFServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/RemoveStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateEventDefinitionServlet.java
web/src/main/java/org/akaza/openclinica/controller/DiscrepancyNoteController.java
web/src/main/java/org/akaza/openclinica/controller/SDVController.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/AbstractItemProcessor.java

OC-9267   Reasons For Change are being autoclosed by OC
OC-9268  Autoclosures of Queries initiated by OC are not appearing in the Query Manager table

OC-9267, OC-9268  Reasons For Change are being autoclosed by OC

---

core/src/main/java/org/akaza/openclinica/service/extract/GenerateClinicalDataServiceImpl.java
web/src/main/java/org/akaza/openclinica/controller/SDVController.java
web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp

Error on trying to delete event in Runtime

Oc 9557 Error on trying to delete event in Runtime

---

core/src/main/java/org/akaza/openclinica/dao/extract/OdmExtractDAO.java
core/src/main/java/org/akaza/openclinica/job/XsltTransformJob.java
core/src/main/java/org/akaza/openclinica/logic/odmExport/ClinicalDataCollector.java

Display when a dataset has been filtered due to user permissions

OC-9563 Display when a dataset has been filtered due to user permissions

---

web/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFDataService.java

OC-9540:Fixed error message null pointer error

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/XformMetaDataService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoAPI.java
web/src/main/java/org/akaza/openclinica/control/submit/EnketoFormServlet.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp

Create Participant XForm flavor at form upload time

OC-9602 Create Participant XForm flavor at form upload time

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/service/ParticipantEventService.java
core/src/main/java/org/akaza/openclinica/service/crfdata/xform/EnketoAPI.java
web/src/main/java/org/akaza/openclinica/controller/AnonymousFormControllerV2.java
web/src/main/java/org/akaza/openclinica/controller/EditFormController.java
web/src/main/java/org/akaza/openclinica/controller/OdmController.java
web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java
web/src/main/java/org/akaza/openclinica/web/pform/PFormCache.java
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp

Webservice to get scheduled participate event forms from OC for the given participant

OC-9646 Webservice to get scheduled participate event forms from OC for the given participant

---

core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java
core/src/main/resources/org/akaza/openclinica/applicationContext-core-service.xml
web/src/main/java/org/akaza/openclinica/controller/OdmController.java
web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
web/src/main/java/org/akaza/openclinica/service/ParticipateService.java
web/src/main/java/org/akaza/openclinica/service/ParticipateServiceImpl.java

Webservice to push form completion status to runtime

OC-9652  Webservice to push form completion status to runtime

---

web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableToolbar.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties

https://jira.openclinica.com/browse/OC-9691

OC-9691 Participant matrix page update to add participate status column

---

core/src/main/java/org/akaza/openclinica/web/filter/ApiSecurityFilter.java

Webservice to get scheduled participate event forms from OC for the given participant
Updated the logic ApiSecurityFilter.java file for the userBean property in request session.

OC-9646     Webservice to get scheduled participate event forms from OC for the given participant

---

web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

https://jira.openclinica.com/browse/OC-9447
https://jira.openclinica.com/browse/OC-9693

Participate UI

---

web/src/main/java/org/akaza/openclinica/controller/OdmController.java

Added Loggers to track issue with userAccount

OC-9646 Added Loggers to track issue with userAccount

---

web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/EventProcessor.java
web/src/main/java/org/akaza/openclinica/service/ParticipateServiceImpl.java
web/src/main/java/org/akaza/openclinica/web/pform/PFormCache.java

This code merge will resolve participate issue that saving to wrong participant.

OC 9665 resolve participate issue with loading and saving date to incorrect study subject

---

core/src/main/java/org/akaza/openclinica/domain/datamap/StudySubject.java
core/src/main/java/org/akaza/openclinica/service/OCParticipantDTO.java
core/src/main/java/org/akaza/openclinica/service/StudyEnvironmentRoleDTO.java
core/src/main/resources/migration/tenant/4.0-2018-10-03-OC-9665.xml
core/src/main/resources/migration/tenant/release.xml
core/src/main/resources/org/akaza/openclinica/applicationContext-core-service.xml
web/src/main/java/org/akaza/openclinica/controller/UserController.java
web/src/main/java/org/akaza/openclinica/service/UserService.java
web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java

Webservice to create and update participant user profile information

OC-9665 Webservice to create and update participant user profile information

---

web/src/main/java/org/akaza/openclinica/web/crfdata/ImportCRFDataService.java

OC-9756: Using Rest API I could import second occurrence in a non-repeating common event

---

pom.xml

Fixing security vulnerabilities in dependency manifest file based on github alerts

Fixing security vulnerabilities in dependency manifest file based on github alerts

---

core/src/main/java/org/akaza/openclinica/domain/rule/action/NotificationActionProcessor.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/controller/UserController.java
web/src/main/java/org/akaza/openclinica/service/UserService.java
web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java

Expose participant user's first name, email and phone number to runtime so that they could be used in the notification message

OC-9767 Expose participant user's first name, email and phone number to runtime so that they could be used in the notification message

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

https://jira.openclinica.com/browse/OC-9750

OC-9750 Audit Log link in the Participant Details Page does not work

---

web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectServlet.java
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

https://jira.openclinica.com/browse/OC-9664

OC-9664 Participant details related to Participate connect should appear based on participate module status

---

web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/controller/OdmController.java
web/src/main/java/org/akaza/openclinica/service/ParticipateService.java
web/src/main/java/org/akaza/openclinica/service/ParticipateServiceImpl.java
web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java

Site participants should see the participate forms on the dashboard only when the site is in available status

OC-9694 Site participants should see the participate forms on the dashboard only when the site is in available status

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/MetaDataReportBean.java

ODM fields for participant form property need to be changed to be called 'ParticipateForm'

OC-9770 ODM fields for participant form property need to be changed to be called 'ParticipateForm'

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/MetaDataReportBean.java
core/src/main/java/org/akaza/openclinica/service/OCUserDTO.java
web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java

Inviting a participant to the study

OC-9704 Inviting a participant to the study

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryService.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/processor/FSItemProcessor.java

Unable to create query in one of the study in Firefox browser.

OC-9807 Unable to create query in one of the study in Firefox browser.

---

core/src/main/java/org/akaza/openclinica/service/UserType.java
core/src/main/java/org/akaza/openclinica/web/filter/ApiSecurityFilter.java
core/src/main/resources/migration/publicSchemaOnly/4.0-2018-11-02-OC-9793.xml
core/src/main/resources/migration/publicSchemaOnly/release.xml
web/src/main/java/org/akaza/openclinica/controller/OdmController.java
web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java

Form data submission via Participate should be logged in the audit log with participant information

OC-9793 Form data submission via Participate should be logged in the audit log with participant information

---

core/src/main/java/org/akaza/openclinica/service/crfdata/EnketoUrlService.java
web/src/main/java/org/akaza/openclinica/control/core/SecureController.java

User can leave form without entering RFC

OC-9697 User can leave form without entering RFC

---

core/src/main/java/org/akaza/openclinica/domain/datamap/AuditLogEvent.java
core/src/main/resources/migration/tenant/inserts.xml
core/src/main/resources/org/akaza/openclinica/applicationContext-core-service.xml
core/src/main/resources/properties/audit_dao.xml
web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectsServlet.java
web/src/main/java/org/akaza/openclinica/controller/AuditLogEventController.java
web/src/main/java/org/akaza/openclinica/controller/EditFormController.java
web/src/main/java/org/akaza/openclinica/controller/OdmController.java
web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
web/src/main/java/org/akaza/openclinica/controller/UserController.java
web/src/main/java/org/akaza/openclinica/controller/dto/AuditLogEventDTO.java
web/src/main/java/org/akaza/openclinica/service/AuditLogEventService.java
web/src/main/java/org/akaza/openclinica/service/AuditLogEventServiceImpl.java
web/src/main/java/org/akaza/openclinica/service/ParticipateService.java
web/src/main/java/org/akaza/openclinica/service/ParticipateServiceImpl.java
web/src/main/java/org/akaza/openclinica/service/UserService.java
web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
web/src/main/java/org/akaza/openclinica/service/ViewStudySubjectServiceImpl.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties

View access link/code for the participant

OC-9695 View access link/code for the participant

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java

Cross-form data file should contain events if they have no forms

OC-9818 Cross-form data file should contain events if they have no forms

---

core/src/main/java/org/akaza/openclinica/bean/extract/odm/ClinicalDataReportBean.java
core/src/main/java/org/akaza/openclinica/service/EventDefinitionCrfDTO.java
core/src/main/java/org/akaza/openclinica/service/OdmImportServiceImpl.java

Update CRF Order in Study Designer and publish it to Runtime

OC-9851 Update CRF Order in Study Designer and publish it to Runtime

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

https://jira.openclinica.com/browse/OC-9447

OC-9447 Feedbacks

---

web/src/main/java/org/akaza/openclinica/config/AppConfig.java
web/src/main/java/org/akaza/openclinica/control/managestudy/SignStudySubjectServlet.java
web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/service/KeycloakUserServiceImpl.java

OC-9867 In Keycloak, signing off on the participant record causes an oops error
- Also removed "/pages/login from AppConfig"

OC-9869 In Keycloak, can sign an event using incorrect password

---

web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionService.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/QueryServiceImpl.java

Owner Id is not getting captured in the database when user adds a query to a field and then completes the form

OC-9868 Owner Id is not getting captured in the database when user adds a query to a field and then completes the form

---

web/src/main/java/org/akaza/openclinica/control/admin/DeleteEventCRFServlet.java
web/src/main/java/org/akaza/openclinica/controller/openrosa/OpenRosaSubmissionController.java

date_completed field in event_crf table does not always get populated when an event gets marked completed

OC-9853 date_completed field in event_crf table does not always get populated when an event gets marked completed

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp

https://jira.openclinica.com/browse/OC-9882?focusedCommentId=167653&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-167653

OC-9882 Renuka feedback (disallow closing dialog when validation fails)

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp

Reverts OpenClinica/OpenClinica#1741

Revert "OC-9882 Renuka feedback (disallow closing dialog when validation fails)"

---

core/src/main/java/org/akaza/openclinica/dao/managestudy/StudyDAO.java

Registering a participant with or without email address from Participant Details page

OC-9423 Bug fix when editing existing sites

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubjectCommon.jsp

https://jira.openclinica.com/browse/OC-9882

OC-9882 Feedback rework

---

core/src/main/java/org/akaza/openclinica/dao/managestudy/StudyDAO.java
core/src/main/java/org/akaza/openclinica/domain/datamap/Study.java

Registering a participant with or without email address from Participant Details page

OC-9423 Bug Fix for hibernate Fetch type

---

core/src/main/java/org/akaza/openclinica/bean/core/UserType.java
core/src/main/resources/migration/tenant/4.0-2018-11-29-OC-9423.xml
web/src/main/java/org/akaza/openclinica/controller/helper/RestfulServiceHelper.java
web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java

Registering a participant with or without email address from Participant Details page

OC-9423 Dropping not needed column in study_subject table

---

web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java

Participate Dashboard [Let's Move On] button dead

OC-9856 Participate Dashboard [Let's Move On] button dead

---

web/src/main/java/org/akaza/openclinica/service/StudyBuildServiceImpl.java
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

https://jira.openclinica.com/browse/OC-9919

OC-9919 RT CRC cannnot access Participate if custom role

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

https://jira.openclinica.com/browse/OC-9882?focusedCommentId=168137&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-168137

OC-9882 feedback: allow empty email address

---

core/src/main/java/org/akaza/openclinica/service/UserType.java
pom.xml
web/pom.xml
web/src/main/java/org/akaza/openclinica/controller/OdmController.java
web/src/main/java/org/akaza/openclinica/controller/StudyEventController.java
web/src/main/java/org/akaza/openclinica/controller/helper/RestfulServiceHelper.java
web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
web/src/main/java/org/akaza/openclinica/web/rest/client/auth/impl/KeycloakClientImpl.java
web/src/main/java/org/akaza/openclinica/web/rest/client/auth/impl/KeycloakConfig.java
web/src/main/java/org/akaza/openclinica/web/rest/client/auth/impl/KeycloakError.java
web/src/main/java/org/akaza/openclinica/web/rest/client/cs/dto/CustomerDTO.java
web/src/main/java/org/akaza/openclinica/web/rest/client/cs/impl/CustomerServiceClientImpl.java
web/src/main/java/org/akaza/openclinica/web/rest/client/us/impl/UserServiceClientImpl.java
web/src/main/resources/auth.properties

Register participant users in keycloak with a static access code

OC-9939 Register participant users in keycloak with a static access code

---

core/src/main/java/org/akaza/openclinica/web/filter/ApiSecurityFilter.java

Register participant users in keycloak with a static access code

OC-9973 Register participant users in keycloak with a static access code

---

core/src/main/java/org/akaza/openclinica/service/ParticipantAccessDTO.java
web/src/main/java/org/akaza/openclinica/controller/UserController.java
web/src/main/java/org/akaza/openclinica/controller/helper/RestfulServiceHelper.java
web/src/main/java/org/akaza/openclinica/service/StudyBuildService.java
web/src/main/java/org/akaza/openclinica/service/StudyBuildServiceImpl.java
web/src/main/java/org/akaza/openclinica/service/UserService.java
web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
web/src/main/java/org/akaza/openclinica/web/rest/client/auth/impl/KeycloakClientImpl.java

Show accessLink in Runtime UI & Email

OC-9973 Show accessLink in Runtime UI & Email

---

web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
web/src/main/java/org/akaza/openclinica/web/rest/client/auth/impl/KeycloakClientImpl.java

Generate 6-digit access code for participant user which is unique within the customer instance

OC-9666 Generate 6-digit access code for participant user which is unique within the customer instance

---

web/src/main/java/org/akaza/openclinica/web/pform/OpenRosaServices.java

Blocked calling user list in form when loading  participate flavor forms

OC-9608 Blocked calling user list in form when loading  participate flavor forms

---

web/src/main/webapp/WEB-INF/jsp/include/navBar.jsp
web/src/main/webapp/includes/styles.css

https://jira.openclinica.com/browse/OC-9959

OC-9959 RT Top Navigation buttons should be clickable

---

web/src/main/java/org/akaza/openclinica/control/submit/AddNewSubjectServlet.java
web/src/main/webapp/WEB-INF/jsp/managestudy/findSubjects.jsp

Moved the jQuery.blockUI function call into the onload function as it was being executed before the DOM was ready.

OC-9813 Add Participant Error Workflow fix

---

web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/service/StudyBuildService.java
web/src/main/java/org/akaza/openclinica/service/StudyBuildServiceImpl.java
web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java

Reverting changes
Also update moduleConfigDTO to return correct subdomain.

OC-9948 Forms are not available on the participate dashboard when the event status is changed from Skipped to Data Entry started

---

web/src/main/java/org/akaza/openclinica/control/managestudy/UpdateStudyEventServlet.java
web/src/main/java/org/akaza/openclinica/service/StudyBuildService.java
web/src/main/java/org/akaza/openclinica/service/StudyBuildServiceImpl.java
web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

Investigator is able to see the participant's details page for a removed participant

OC-10001 Investigator is able to see the participant's details page for a removed participant

---

web/src/main/java/org/akaza/openclinica/control/managestudy/StudyAuditLogTableFactory.java
web/src/main/java/org/akaza/openclinica/control/submit/ListNotesTableFactory.java
web/src/main/java/org/akaza/openclinica/control/submit/ListStudySubjectTableFactory.java
web/src/main/java/org/akaza/openclinica/web/table/sdv/SDVUtil.java

https://jira.openclinica.com/browse/OC-9952

OC-9952 Change the current table limit of 15 to 50 for all pages in runtime

---

web/src/main/webapp/WEB-INF/jsp/submit/enketoFormServlet.jsp

https://jira.openclinica.com/browse/OC-9993

OC-9993 Participate and RT Form won't scroll on Desktop browsers.

---

web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp

Remove Temporary Participant Form view link from Participant Details page

OC-9655 Remove Temporary Participant Form view link from Participant Details page

---

web/src/main/java/org/akaza/openclinica/control/MainMenuServlet.java
web/src/main/java/org/akaza/openclinica/control/core/SecureController.java
web/src/main/java/org/akaza/openclinica/control/login/ChangeStudyServlet.java
web/src/main/java/org/akaza/openclinica/controller/KeycloakController.java

OC-10033: New CRC taken to Change study page on first login
OC-10017: When a new configurable user role is created and assigned to a user, the role is not reflected correctly in runtime

OC-9953: Task Menu not rendering for DS and DEP users

---

web/src/main/java/org/akaza/openclinica/web/table/sdv/SDVUtil.java

https://jira.openclinica.com/browse/OC-9952

OC-9952 Change the current table limit of 15 to 50 for all pages in runtime(update)

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

Reverts OpenClinica/OpenClinica#1789

Revert "OC-9997 Access code in Participant Detail Page is empty until reload …"

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

https://jira.openclinica.com/browse/OC-9997
Sorry the previous PR lacked initial-page-load initialization.

Re-fix OC-9997 (Access code in Participant Detail Page is empty until reload the page)

---

web/src/main/java/org/akaza/openclinica/service/StudyBuildServiceImpl.java
web/src/main/java/org/akaza/openclinica/web/filter/XSSFilter.java
web/src/main/java/org/akaza/openclinica/web/filter/XSSRequestWrapper.java
web/src/main/webapp/WEB-INF/web.xml

Adding a filter that cleanses parameters at a global level

XSSFilter implementation

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

https://jira.openclinica.com/browse/OC-9695

OC-9695 feedback: View access code for the participant

---

web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

https://jira.openclinica.com/browse/OC-9695?focusedCommentId=169725&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-169725

OC-9695 feedback: copy change: "Access Link" to "Access Code"

---

web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

https://jira.openclinica.com/browse/OC-10091

OC-10091 'View access details' links and modal window changes

---

web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

https://jira.openclinica.com/browse/OC-10093

OC-10093 Invite modal window changes

---

web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java

Participant Invite email message

OC-10083 Participant Invite email message

---

web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

Audit text change for participant access code view event

OC-10125 Audit text change for participant access code view event

---

core/src/main/java/org/akaza/openclinica/service/managestudy/StudySubjectServiceImpl.java
web/src/main/java/org/akaza/openclinica/control/managestudy/ViewStudySubjectServlet.java
web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
web/src/main/resources/org/akaza/openclinica/i18n/words.properties
web/src/main/webapp/WEB-INF/jsp/managestudy/showStudyEventRow.jsp
web/src/main/webapp/WEB-INF/jsp/managestudy/viewStudySubject.jsp

RT: Skipped Event should not allow data entry

Oc 9949 RT: Skipped Event should not allow data entry

---

core/src/main/java/org/akaza/openclinica/domain/rule/action/NotificationActionProcessor.java
core/src/main/java/org/akaza/openclinica/logic/rulerunner/BeanPropertyRuleRunner.java
web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java

Notification Rule not firing on Participate participant

OC-10139 Notification Rule not firing on Participate participant

---

web/src/main/java/org/akaza/openclinica/service/UserServiceImpl.java
web/src/main/java/org/akaza/openclinica/web/rest/client/auth/impl/KeycloakClientImpl.java

Add studyEnvUuid to the attributes sent to keycloak at the time of the participant registration

OC-10158 Add studyEnvUuid to the attributes sent to keycloak at the time of the participant registration
